# WARNING - Generated by {fusen} from /dev/flat_data_filtre.Rmd: do not edit by hand

test_that("data_filtre works", {

  expect_s3_class(data_filtre(iris, "setosa", "Sepal.Length", "6.2"), "data.frame")
})
