flat_actionButton.Rmd:
  path: dev/flat_composants/flat_actionButton.Rmd
  state: active
  R:
  - R/actionbutton_dsfr.R
  - R/actionbutton_dsfr_template.R
  tests:
  - tests/testthat/test-actionbutton_dsfr_template.R
  - tests/testthat/test-actionbutton_dsfr.R
  vignettes: []
  inflate:
    pkg: shinygouv
    flat_file: dev/flat_composants/flat_actionButton.Rmd
    vignette_name: .na
    open_vignette: yes
    check: yes
    document: yes
    overwrite: ask
flat_tools.Rmd:
  path: dev/flat_tools.Rmd
  state: active
  R:
  - R/parse_html.R
  - R/parse_to_xml.R
  - R/render_node.R
  tests:
  - tests/testthat/test-parse_to_xml.R
  - tests/testthat/test-render_node.R
  - tests/testthat/test-parse_html.R
  vignettes: []
  inflate:
    pkg: shinygouv
    flat_file: dev/flat_tools.Rmd
    vignette_name: .na
    open_vignette: yes
    check: no
    document: yes
    overwrite: 'yes'
