flat_actionButton.Rmd:
  path: dev/flat_composants/flat_actionButton.Rmd
  state: active
  R:
  - R/actionbutton_dsfr.R
  - R/actionbutton_dsfr_template.R
  tests:
  - tests/testthat/test-actionbutton_dsfr_template.R
  - tests/testthat/test-actionbutton_dsfr.R
  vignettes: vignettes/actionbutton_dsfr.Rmd
  inflate:
    flat_file: dev/flat_composants/flat_actionButton.Rmd
    vignette_name: actionButton_dsfr
    open_vignette: yes
    check: no
    document: yes
    overwrite: ask
flat_convert_to_dsfr.Rmd:
  path: dev/flat_convert_to_dsfr.Rmd
  state: active
  R:
  - R/convert_file_to_dsfr.R
  - R/convert_to_dsfr.R
  - R/get_dsfr_version.R
  tests:
  - tests/testthat/test-convert_file_to_dsfr.R
  - tests/testthat/test-convert_to_dsfr.R
  - tests/testthat/test-get_dsfr_version.R
  vignettes: vignettes/convertir-une-app-shiny-en-app-shiny-dsfr.Rmd
  inflate:
    flat_file: dev/flat_convert_to_dsfr.Rmd
    vignette_name: Convertir une app shiny en app shiny dsfr
    open_vignette: yes
    check: yes
    document: yes
    overwrite: ask
flat_fluidpage.Rmd:
  path: dev/flat_composants/flat_fluidpage.Rmd
  state: active
  R:
  - R/column_dsfr.R
  - R/fluidpage_dsfr.R
  - R/fluidpage_dsfr_template.R
  - R/fluidrow_dsfr.R
  - R/layout_dsfr_template.R
  tests:
  - tests/testthat/test-fluidpage_dsfr_template.R
  - tests/testthat/test-fluidpage_dsfr.R
  - tests/testthat/test-layout_dsfr_template.R
  - tests/testthat/test-fluidrow_dsfr.R
  - tests/testthat/test-column_dsfr.R
  vignettes: []
  inflate:
    pkg: shinygouv
    flat_file: dev/flat_composants/flat_fluidpage.Rmd
    vignette_name: fluidPage_dsfr
    open_vignette: yes
    check: yes
    document: yes
    overwrite: ask
flat_modal.Rmd:
  path: dev/flat_composants/flat_modal.Rmd
  state: active
  R:
  - R/modaldialog_dsfr.R
  - R/modaldialog_dsfr_template.R
  tests:
  - tests/testthat/test-modaldialog_dsfr_template.R
  - tests/testthat/test-modaldialog_dsfr.R
  vignettes: []
  inflate:
    flat_file: dev/flat_composants/flat_modal.Rmd
    vignette_name: .na
    open_vignette: yes
    check: no
    document: yes
    overwrite: ask
flat_panels.Rmd:
  path: dev/flat_composants/flat_panels.Rmd
  state: active
  R:
  - R/tabpanel.R
  - R/tabsetpanel_dsfr_template.R
  tests:
  - tests/testthat/test-tabsetpanel_dsfr_template.R
  - tests/testthat/test-tabpanel.R
  vignettes: []
  inflate:
    pkg: shinygouv
    flat_file: dev/flat_composants/flat_panels.Rmd
    vignette_name: .na
    open_vignette: yes
    check: yes
    document: yes
    overwrite: ask
flat_radioButtons.Rmd:
  path: dev/flat_composants/flat_radioButtons.Rmd
  state: active
  R:
  - R/radiobuttons_dsfr.R
  - R/radiobuttons_dsfr_template.R
  - R/radiobuttons_unique_dsfr_template.R
  - R/updateradiobuttons_dsfr.R
  tests:
  - tests/testthat/test-radiobuttons_unique_dsfr_template.R
  - tests/testthat/test-radiobuttons_dsfr_template.R
  - tests/testthat/test-radiobuttons_dsfr.R
  - tests/testthat/test-updateradiobuttons_dsfr.R
  vignettes: vignettes/radiobuttons_dsfr.Rmd
  inflate:
    flat_file: dev/flat_composants/flat_radioButtons.Rmd
    vignette_name: radioButtons_dsfr
    open_vignette: no
    check: yes
    document: yes
    overwrite: ask
flat_selectInput.Rmd:
  path: dev/flat_composants/flat_selectInput.Rmd
  state: active
  R:
  - R/selectinput_dsfr.R
  - R/selectinput_dsfr_template.R
  - R/selectinput_options_dsfr_template.R
  - R/updateselectinput_dsfr.R
  tests:
  - tests/testthat/test-selectinput_options_dsfr_template.R
  - tests/testthat/test-selectinput_dsfr_template.R
  - tests/testthat/test-selectinput_dsfr.R
  - tests/testthat/test-updateselectinput_dsfr.R
  vignettes: vignettes/selectinput_dsfr.Rmd
  inflate:
    flat_file: dev/flat_composants/flat_selectInput.Rmd
    vignette_name: selectInput_dsfr
    open_vignette: yes
    check: no
    document: yes
    overwrite: ask
flat_toggleswitch.Rmd:
  path: dev/flat_composants/flat_toggleswitch.Rmd
  state: active
  R:
  - R/toggleswitch_dsfr.R
  - R/toggleswitch_dsfr_template.R
  - R/updatetoggleswitch_dsfr.R
  tests:
  - tests/testthat/test-toggleswitch_dsfr_template.R
  - tests/testthat/test-toggleswitch_dsfr.R
  vignettes: []
  inflate:
    flat_file: dev/flat_composants/flat_toggleswitch.Rmd
    vignette_name: .na
    open_vignette: yes
    check: no
    document: yes
    overwrite: ask
flat_withSpinner.Rmd:
  path: dev/flat_composants/flat_withSpinner.Rmd
  state: active
  R: R/withspinner_dsfr.R
  tests: tests/testthat/test-withspinner_dsfr.R
  vignettes: vignettes/withspinner_dsfr.Rmd
  inflate:
    flat_file: dev/flat_composants/flat_withSpinner.Rmd
    vignette_name: withSpinner_dsfr
    open_vignette: no
    check: no
    document: yes
    overwrite: 'yes'
