flat_convert_to_dsfr.Rmd:
  path: dev/flat_convert_to_dsfr.Rmd
  state: active
  R:
  - R/convert_file_to_dsfr.R
  - R/convert_to_dsfr.R
  - R/get_dsfr_version.R
  tests:
  - tests/testthat/test-convert_file_to_dsfr.R
  - tests/testthat/test-convert_to_dsfr.R
  - tests/testthat/test-get_dsfr_version.R
  vignettes: vignettes/convertir-une-app-shiny-en-app-shiny-dsfr.Rmd
  inflate:
    flat_file: dev/flat_convert_to_dsfr.Rmd
    vignette_name: Convertir une app shiny en app shiny dsfr
    open_vignette: yes
    check: yes
    document: yes
    overwrite: ask
flat_fluidpage.Rmd:
  path: dev/flat_composants/flat_fluidpage.Rmd
  state: active
  R:
  - R/column_dsfr.R
  - R/fluidpage_dsfr.R
  - R/fluidpage_dsfr_template.R
  - R/fluidrow_dsfr.R
  - R/layout_dsfr_template.R
  tests:
  - tests/testthat/test-fluidpage_dsfr_template.R
  - tests/testthat/test-fluidpage_dsfr.R
  - tests/testthat/test-layout_dsfr_template.R
  - tests/testthat/test-fluidrow_dsfr.R
  - tests/testthat/test-column_dsfr.R
  vignettes: []
  inflate:
    pkg: shinygouv
    flat_file: dev/flat_composants/flat_fluidpage.Rmd
    vignette_name: .na
    open_vignette: yes
    check: no
    document: yes
    overwrite: ask
flat_header.Rmd:
  path: dev/flat_composants/flat_header.Rmd
  state: active
  R:
  - R/header_dsfr.R
  - R/header_dsfr_template.R
  tests:
  - tests/testthat/test-header_dsfr_template.R
  - tests/testthat/test-header_dsfr.R
  vignettes: []
  inflate:
    pkg: shinygouv
    flat_file: dev/flat_composants/flat_header.Rmd
    vignette_name: .na
    open_vignette: no
    check: no
    document: yes
    overwrite: ask
flat_navbarPage.Rmd:
  path: dev/flat_composants/flat_navbarPage.Rmd
  state: active
  R: R/navbarpage_dsfr.R
  tests: tests/testthat/test-navbarpage_dsfr.R
  vignettes: vignettes/navbarpage_dsfr.Rmd
  inflate:
    pkg: shinygouv
    flat_file: dev/flat_composants/flat_navbarPage.Rmd
    vignette_name: navbarPage_dsfr
    open_vignette: yes
    check: no
    document: yes
    overwrite: ask
