---
title: "flat_new_one.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

# nom_composant_shiny_dsfr_template
    
```{r function-nom_composant_shiny_dsfr_template}
#' nom_composant_shiny_dsfr_template
#' 
#' @importFrom htmltools htmlTemplate
#' @return html
nom_composant_shiny_dsfr_template <- function(
  # ajouter vos params  
  ){
  
  htmltools::htmlTemplate(
    filename = system.file(
      "chemin vers le fichier",
      package = "shinygouv"
    )
    # ajouter vos params
    )
}

```
  
  
```{r tests-nom_composant_shiny_dsfr_template}
test_that("nom_composant_shiny_dsfr_template works", {
  expect_true(inherits(nom_composant_shiny_dsfr_template, "function")) 
  
    htmlfile <- readLines(
    system.file(
      "chemin vers le fichier",
      package = "shinygouv"
    )
  )
  
  #' @description Comparer les parametres par rapport a ceux de la version precedente
  
  purrr::walk(
    c(
      # ajouter vos params
      ),
    function(param){
      with_moustache <- paste0("\\{\\{",param,"\\}\\}")
      message(with_moustache)
      expect_true(any(grepl(pattern = with_moustache, htmlfile)))
      message("test passed :-)")
    })
  
  
    test <- nom_composant_shiny_dsfr_template(
      # ajouter vos params
    )
  
  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))
  
  
  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
        # ajouter les valeurs de vos params passes à test
      ),
    function(param){
      message(param)
      expect_true(any(grepl(pattern = param, test)))
      message("test passed :-)")
    })
  
 ## lecture snapshot
  snapshot <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate), 
      #"tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate), 
                     "Date_du_snapshot-nom_composant_shiny_dsfr_template.Rda")
  )
  
  #' @description Verifie la presence du parametre class
  expect_equal(htmlfile, snapshot) 
  
    # Si erreur au précedent test deux cas possible :
    #
    # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
    #
    # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
    #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
    #                              dans la fonction nom_composant_shiny_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

 # saveRDS(htmlfile,
 #         file = file.path("tests/testthat/snapshot",
 #                          paste0(Sys.Date(), "-","nom_composant_shiny_dsfr_template.Rda")
 #                          )
 #         )

  
})
```
  

# nom_composant_shiny_dsfr

```{r function-nom_composant_shiny_dsfr}
#' nom_composant_shiny_dsfr
#' 
#' 
#' @return html
#' 
#' @export
#'
#' @examples
nom_composant_shiny_dsfr <- function(
  # ajouter vos paramètres  
  ) {
  
  # check les params
  # assertthat::assert_that(is.character(params))
  
    nom_composant_shiny_dsfr_template(
      # ajouter vos params
    ) %>%
      parse_html()

}
```

```{r examples-nom_composant_shiny_dsfr}
nom_composant_shiny_dsfr(
  # ajouter vos params
)
```

```{r tests-nom_composant_shiny_dsfr}
test_that("nom_composant_shiny_dsfr works", {
  test <- nom_composant_shiny_dsfr(
    # ajouter vos params
  )
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag")
  
  # Rajouter des tests pour controler le type des parametres
  
  #' @description tester le type du param `monparam`
  expect_error( nom_composant_shiny_dsfr(
    # ajouter vos params 
    # changer le type de `monparam` 
  ))
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly

fusen::inflate(flat_file = "dev/flat_composants/chemin à modifier", 
                vignette_name = "nom_composant_shiny_dsfr")
```

