---
title: "flat_data_filtre.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

# data_filtre

La fonction prend en argument la table `iris` et renvoie une table filtree selon une espece et le maximum d une des caracterisique (Sepal.Lenght ou Petal.Length), passés en arguments.

```{r function-data_filtre}
#' data_filtre 
#' 
#' 
#' @param df dataframe iris a filtrer
#' @param species character "setosa", "versicolor" ou  "virginica"
#' @param sepal_petal character "Sepal.Length" ou "Petal.Length"
#' @param max numeric maximum de "sepal" ou "petal" Length
#' @return dataframe
#' @export
#' @examples
data_filtre <- function(df, species, sepal_petal, max) {
  res <- df[df[["Species"]] == species & df[[sepal_petal]] <= max, ]
  return(res)
}
```

```{r examples-data_filtre}
data_filtre(iris, "setosa", "Sepal.Length", 6.2)
```

```{r tests-data_filtre}
test_that("data_filtre works", {
  expect_s3_class(data_filtre(iris, "setosa", "Sepal.Length", 6.2), "data.frame")
  res <- data_filtre(iris, "setosa", "Sepal.Length", 6.2)
  expect_equal(nrow(res), 50)
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/flat_data_filtre.Rmd", vignette_name = "fonction demo")
```

