# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkboxInput.Rmd: do not edit by hand

test_that("checkboxInput_dsfr", {
  test <- checkboxInput_dsfr(
    inputId = "test1", label = "Test1", choices = c("A","B")
  )
  
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag")
  
  # with choice
  test_with_choice <- checkboxInput_dsfr(
    inputId = "test", label = "Test", choices = c("A" = "a", "B" = "b"), selected = "b"
  )
  # with choice_values and choice_name
  test_witch_choice_value <- checkboxInput_dsfr(
    inputId = "test", label = "Test", choice_values = c("a", "b"), choice_names = c("A", "B"), selected = "b"
  )
  
  expect_equal(test_with_choice, test_witch_choice_value)
  
  # error when choice and choice_values are NULL
  test_error_no_choices <- function() {
    checkboxInput_dsfr(inputId = "test", choice = NULL, choice_values = NULL)
  }
  
  expect_error(test_error_no_choices())
  
  # error if character vector choice_values and choice_names are not the same length
  test_error_choice_values_name_different_length <- function(){
    checkboxInput_dsfr(inputId = "test", choice = NULL, choice_values = c('a', 'b'), choice_names = c('A'))
  }
  
  expect_error(test_error_choice_values_name_different_length())
})
