# WARNING - Generated by {fusen} from dev/flat_composants/flat_panels.Rmd: do not edit by hand

test_that("tabsetPanel_dsfr works", {
  test_html <- tabsetPanel_dsfr(
    "coucou",
    tabPanel_dsfr(
      id = "tab1",
      title = "Une prems tab",
      content = tagList(
        h3("Coucou"),
        plotOutput("plot")
      )
    ),
    tabPanel_dsfr(
      id = "tab2",
      title = "Une deuxieme tab",
      content = tagList(
        h3("Salut"),
        plotOutput("plot2")
      )
    )
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag.list")
})
