# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_actionButton.Rmd: do not edit by hand

test_that("actionButton_dsfr_template works", {
  expect_true(inherits(actionButton_dsfr_template, "function"))

  test <- actionButton_dsfr_template("test", "test", NULL)

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))
})
