# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_radioButtons.Rmd: do not edit by hand

test_that("updateRadioButtons_dsfr works", {
  expect_true(inherits(updateRadioButtons_dsfr, "function")) 
})
