# WARNING - Generated by {fusen} from dev/flat_composants/flat_navbarPage.Rmd: do not edit by hand

test_that("navbarPage_dsfr works", {
  ui <- navbarPage_dsfr(
    title = "Welcome to the Jungle",
    id = "nav",
    header = header_dsfr(
      intitule = "République Française",
      nom_site_service = "Nom du site / service",
      baseline = "Baseline - pr\u00E9cisions sur l organisation"
    ),
    # First tab
    navbarPanel_dsfr(
      title = "actionButton_dsfr()",
      fluidRow_dsfr(
        column_dsfr(
          12,
          h3("Demo actionButton_dsfr()"),
          # Adding space to the column
          # https://www.systeme-de-design.gouv.fr/elements-d-interface/fondamentaux-techniques/espacement
          extra_class = "fr-my-6w"
        ),
        column_dsfr(
          4,
          actionButton_dsfr(
            "go",
            label = "Un bouton avec un \u00E9!"
          )
        ),
        column_dsfr(
          8,
          p("Salut les gens!"),
          verbatimTextOutput(
            "output1"
          )
        )
      )
    )
  )
  #' @description tester si shiny.tag
  expect_s3_class(ui, "shiny.tag.list")
  #' @description Est-ce qu'on retrouve les éléments
  expect_true(
    grepl("actionButton_dsfr", ui)
  )
  #' @description Est-ce qu'on retrouve les éléments
  expect_true(
    grepl("navbarPanel_dsfr", ui)
  )
})
