# WARNING - Generated by {fusen} from /dev/flat_composants/flat_actionButton.Rmd: do not edit by hand

test_that("actionButton_dsfr_template works", {
  expect_true(inherits(actionButton_dsfr_template, "function")) 
  
  
    
  htmlfile <- readLines(
    system.file(
      "v1.7.2",
      "composant", 
      "bouton.html",
      package = "shinygouv"
    )
  )
  
  #' @description Comparer les parametres par rapport a ceux de la version precedente
  
  purrr::walk(
    c("inputId","class","label"),
    function(param){
      with_moustache <- paste0("\\{\\{",param,"\\}\\}")
      message(with_moustache)
      expect_true(grepl(pattern = with_moustache, htmlfile))
      message("test passed :-)")
    })
  
  test <- actionButton_dsfr_template(inputId = "testId",
                                     label = "test", 
                                     class = "fr-btn--icon-left fr-icon-checkbox-circle-line")
  
  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))
  
  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
      "testId",
      "fr-btn--icon-left fr-icon-checkbox-circle-line",
      "test"
      ),
    function(param){
      message(param)
      expect_true(grepl(pattern = param, test))
      message("test passed :-)")
    })

  ## lecture snapshot
  snapshot <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate), 
      #"tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate), 
                     "2022-08-12-actionButton_dsfr_template.Rda")
  )
  
  #' @description Verifie la presence du parametre class
  expect_equal(htmlfile, snapshot) 
  
    # Si erreur au précedent test deux cas possible :
    #
    # - nouveau composant: Lancer le saveRDS et relancer le test
    #
    # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
    #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
    #                              dans la fonction actionButton_dsfr_template puis lancer le saveRDS et relancer le test

 # saveRDS(htmlfile,
 #         file = file.path("tests/testthat/snapshot",
 #                          paste0(Sys.Date(), "-","actionButton_dsfr_template.Rda")
 #                          )
 #         )
  
})
