# WARNING - Generated by {fusen} from /dev/tools/flat_convert_to_dsfr.Rmd: do not edit by hand

test_that("get_dsfr_version works", {
  expect_true(inherits(get_dsfr_version, "function"))
  # A changer a chaque fois que 'shinygouv' met a jour le dsfr
  expect_equal(get_dsfr_version(), "1.9.3")
  expect_equal(get_dsfr_version(with_v = TRUE), "v1.9.3")
})
