# WARNING - Generated by {fusen} from dev/flat_composants/flat_withSpinner.Rmd: do not edit by hand

test_that("addWithSpinner works", {
  spinner <- addWithSpinner()
  expect_true(inherits(spinner, "html"))
})

test_that("showSpinner_dsfr works", {
  expect_true(inherits(showSpinner_dsfr, "function"))
})

test_that("hideSpinner_dsfr works", {
  expect_true(inherits(hideSpinner_dsfr, "function"))
})

test_that("withSpinner_dsfr works", {
  expect_true(inherits(withSpinner_dsfr, "function"))
})
