# WARNING - Generated by {fusen} from /dev/flat_composants/flat_footer.Rmd: do not edit by hand

test_that("footer_extra_url_body_dsfr works", {
  expect_true(inherits(footer_extra_url_body_dsfr, "function")) 
  
    test_html <- footer_extra_url_body_dsfr()
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag.list")
 
  
  test_html <- footer_extra_url_body_dsfr(footer_li_dsfr(href = "http://siteinternet.fr", texte = "siteinternet.fr"))
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag.list") 
})

test_that("footer_extra_url_bottom_dsfr works", {
  expect_true(inherits(footer_extra_url_bottom_dsfr, "function")) 
  
    test_html <-footer_extra_url_bottom_dsfr(accessibilite = "non", lien_accessibilite = "url_accessibilite", footer_li_dsfr(href = "http://siteinternet.fr", texte = "siteinternet.fr"))

  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag.list")
  
})

test_that("footer_li_dsfr works", {
  expect_true(inherits(footer_li_dsfr, "function")) 
  
  test_html <- footer_li_dsfr(href = "http://siteinternet.fr", texte = "siteinternet.fr")
  #' @description tester si tagList
    expect_s3_class(test_html, "shiny.tag")
  
  
})

test_that("footer_dsfr works", {
  test_html <-
    footer_dsfr(
      intitule = "Territoire",
      description = "une description",
      accessibilite = "partiellement",
      add_extra_url_body =
        footer_extra_url_body_dsfr(
          footer_li_dsfr(
            href = "https://siteinternet.fr",
            titre = "siteinternet.fr.fr - nouvelle fenêtre",
            texte = "siteinternet.fr.fr"
          )
        ),
      add_extra_url_bottom =  footer_extra_url_bottom_dsfr(accessibilite = "non")
    )
  
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "footer_dsfr.Rda")
  )

  #' @description Verifer que le HTML est correct en sortie
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html))

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #  dans la fonction footer_dsfr puis lancer le saveRDS, relancer le test et recommenter le saveRDS
  # 
  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "footer_dsfr.Rda"
  #                          )
  #         )

})
