# WARNING - Generated by {fusen} from /dev/flat_composants/flat_toggleswitch.Rmd: do not edit by hand

test_that("toggleSwitch_dsfr_template works", {
    expect_true(inherits(toggleSwitch_dsfr_template, "function"))

    htmlfile <- readLines(
        system.file(
            get_dsfr_version(with_v = TRUE),
            "composant",
            "toggleswitch.html",
            package = "shinygouv"
        )
    )

    #' @description Comparer les parametres par rapport a ceux de la version precedente

    purrr::walk(
        c(
            "inputId",
            "label",
            "activate",
            "deactivate" # ajouter vos params
        ),
        function(param) {
            with_moustache <- paste0("\\{\\{", param, "\\}\\}")
            expect_true(any(grepl(pattern = with_moustache, htmlfile)),
                label = paste0("sans moustache '", param, "'"))
        })


    test_html <- toggleSwitch_dsfr_template(
        inputId = "test",
        label = "test",
        activate = "act",
        deactivate = "deact" # ajouter vos params
    )

    #' @description tester si tous les params sont remplaces
    expect_false(grepl(pattern = "\\{\\{", test_html))


    #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

    purrr::walk(
        c(
            inputId = "test",
            label = "test",
            activate = "act",
            deactivate = "deact"
        ),
        function(param) {
            expect_true(any(grepl(pattern = param, test_html)),
                label = paste0("remplacement de '", param, "'"))
        })

    ## lecture snapshot
    snapshot_html <- readRDS(
        file = file.path(
            "snapshot", # pour passer les tests en production (apres le inflate),
            # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
            "toggleSwitch_dsfr_template.Rda")
    )

    #' @description Verifie le HTML créé
    # Retire tous les espaces et saut de ligne pour la comparaison
    # Pour eviter les problèmes inter-OS
    expect_equal(gsub("\\s|\\n", "", test_html),
        gsub("\\s|\\n", "", snapshot_html))

    # Si erreur au précedent test deux cas possible :
    #
    # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
    #
    # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
    #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
    #  dans la fonction toggleSwitch_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

    # saveRDS(test_html,
    #         file = file.path("tests/testthat/snapshot",
    #                          "toggleSwitch_dsfr_template.Rda"
    #                          )
    #         )


})
