# WARNING - Generated by {fusen} from dev/flat_composants/flat_panels.Rmd: do not edit by hand

test_that("tabsetPanel_dsfr works", {
  test_html <- tabsetPanel_dsfr(
    "coucou",
    tabPanel_dsfr(
      id = "tab1",
      title = "Une prems tab",
      content = tagList(
        h3("Coucou"),
        plotOutput("plot")
      )
    ),
    tabPanel_dsfr(
      id = "tab2",
      title = "Une deuxieme tab",
      content = tagList(
        h3("Salut"),
        plotOutput("plot2")
      )
    )
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag.list")

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "tabsetPanel_dsfr.Rda"
    )
  )

  #' @description Verifer que le HTML est correct en sortie
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(
    gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html)
  )

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #  dans la fonction tabsetPanel_dsfr puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "tabsetPanel_dsfr.Rda"
  #                          )
  #         )


  # Ajouter des tests pour controler le type des parametres d'entree
  # Cela verifie que les 'assertthat' fonctionnent correctement

  #' @description tester le type du param `monparam`
  expect_error(tabsetPanel_dsfr(
    # ajouter vos params
    # changer le type de `monparam`
  ))
})
