# WARNING - Generated by {fusen} from dev/flat_composants/flat_withSpinner.Rmd: do not edit by hand

test_that("addWithSpinner works", {
  spinner <- addWithSpinner()
  expect_true(inherits(spinner, "html"))
})
