# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkboxInput.Rmd: do not edit by hand

test_that("updateCheckboxInput_dsfr works", {
  expect_true(inherits(updateCheckboxInput_dsfr, "function")) 
  sessA <- createModuleSession("modA")
  updateCheckboxInput_dsfr(
      session = sessA, 
      inputId = "inCheckboxInput",
      label = "Un nouveau label",
      choices = c("choice-a" = "a"),
      selected = "a"
    )
  
    resultA <- sessA$lastInputMessage
    # inputId
    expect_equal("inCheckboxInput", resultA$id)
    # label
    expect_equal("Un nouveau label", resultA$message$label)
    # HTML content
    expect_true(grepl('id\\s*=\\s*\"modA-inCheckboxInput-1\"', resultA$message$options))
    expect_true(grepl('value\\s*=\\s*"a"', resultA$message$options))
    expect_true(grepl('choice-a', resultA$message$options))
    #expect_true(grepl('checked\\s*=\\s*""', resultA$message$options))
    expect_true(grepl('checked', resultA$message$options))
})
