# WARNING - Generated by {fusen} from dev/flat_composants/flat_radioGroupButtons.Rmd: do not edit by hand

test_that("updateRadioGroupButtons_dsfr works", {
  expect_true(inherits(updateRadioGroupButtons_dsfr, "function"))

  # sessA <- createModuleSession("modA")
  #
  # updateRadioGroupButtons_dsfr(
  #     session = sessA,
  #     inputId = "inradioGroupButtons",
  #     label = "Un nouveau label",
  #     choices = c("choice-a" = "a"),
  #     selected = "a"
  #   )
  #
  #   resultA <- sessA$lastInputMessage
  #   # inputId
  #   expect_equal("modA-inradioGroupButtons", resultA$id)
  #   # label
  #   expect_equal("Un nouveau label", resultA$message$label)
  #   # HTML content
  #   expect_true(grepl('id\\s*=\\s*\"modA-inradioGroupButtons-1\"', resultA$message$options))
  #   expect_true(grepl('value\\s*=\\s*"a"', resultA$message$options))
  #   expect_true(grepl('choice-a', resultA$message$options))
  #   expect_true(grepl('checked\\s*=\\s*""', resultA$message$options))
})
