# WARNING - Generated by {fusen} from dev/flat_composants/flat_actionButton.Rmd: do not edit by hand

test_that("actionButton_dsfr works", {

  test_html <- actionButton_dsfr(
    inputId = "test",
    label = "test",
    class = "fr-btn--icon-left fr-icon-checkbox-circle-line"
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")

  #' @description Verifer que le HTML est correct en sortie
    ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "actionButton_dsfr.Rda")
  )

  #' @description Verifie la presence du parametre class
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
               gsub("\\s|\\n", "", snapshot_html))

    # Si erreur au précedent test deux cas possible :
    #
    # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
    #
    # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
    #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
    #                              dans la fonction actionButton_dsfr puis lancer le saveRDS, relancer le test et recommenter le saveRDS

 # saveRDS(test_html,
 #         file = file.path("tests/testthat/snapshot",
 #                          "actionButton_dsfr.Rda"
 #                          )
 #         )
})
