# WARNING - Generated by {fusen} from dev/flat_composants/flat_selectInput.Rmd: do not edit by hand

test_that("updateSelectInput_dsfr works", {
  expect_true(inherits(updateSelectInput_dsfr, "function"))

  sessA <- createModuleSession("modA")

  updateSelectInput_dsfr(
    session = sessA,
    inputId = "variable",
    label = "Nouveau label",
    choices = LETTERS[1:5],
    selected = LETTERS[4]
  )

  resultA <- sessA$lastInputMessage
  # inputId
  expect_equal("modA-variable", resultA$id)
  # label
  expect_equal("Nouveau label", resultA$message$label)
  # HTML content
  expect_equal(
    resultA$message$options,
    structure(
      "<option value=\"A\">A</option>\n<option value=\"B\">B</option>\n<option value=\"C\">C</option>\n<option value=\"D\" selected>D</option>\n<option value=\"E\">E</option>",
      html = TRUE,
      class = c(
        "html",
        "character"
      )
    )
  )
})
