# WARNING - Generated by {fusen} from /dev/flat_convert_to_dsfr.Rmd: do not edit by hand

test_that("convert_to_dsfr works", {
  mydir <- tempfile(pattern = "app")
  dir.create(mydir)
  golem::install_dev_deps(
    force_install = TRUE
  )
  golem::create_golem(
    mydir,
    overwrite = TRUE,
    open = FALSE
  )

  file.copy(
    from = file.path(mydir, "R", "app_ui.R"),
    to = file.path(mydir, "R", "module_ui.R")
  )

  #' @description Retourne une erreur si le numero de version est NULL
  expect_error(convert_to_dsfr(path = file.path(mydir, "R"), version = NULL))

  #' @description Retourne une erreur si le tableau de correspondance n'existe pas pour la version specifiee
  expect_error(convert_to_dsfr(path = file.path(mydir, "R"), version = "A.A.A.A"), msg = "Le dossier 'vA.A.A.A' n'existe pas")

  expect_error(convert_to_dsfr(path = file.path(mydir, "R")), regexp = NA)
  app_ui <- readLines(file.path(mydir, "R", "app_ui.R"))

  #' @description la dependance a shinygouv a ete ajoute a app_ui.R
  expect_true(any(stringr::str_detect(string = app_ui, pattern = "@import shinygouv")))


  #' @description les composants dsfr n ayant pas d equivalent en shiny ne sont pas remplaces, par exemple header_dsfr

  expect_false(any(stringr::str_detect(app_ui, pattern = "header_dsfr\\(")))
})
