# WARNING - Generated by {fusen} from dev/flat_composants/flat_numericInput.Rmd: do not edit by hand

test_that("updateNumericInput_dsfr works", {
  expect_true(inherits(updateNumericInput_dsfr, "function"))

  sessA <- createModuleSession("modA")

  updateNumericInput_dsfr(
    session = sessA,
    inputId = "myid",
    label = "Numeric input",
    value = 12,
    min = 0,
    max = NA,
    step = 2
  )


  resultA <- sessA$lastInputMessage
  # inputId
  expect_equal("modA-myid", resultA$id)
  # label
  expect_equal("Numeric input", resultA$message$label)
  # value
  expect_equal("12", resultA$message$value)
  # min
  expect_equal("0", resultA$message$min)
  # max
  expect_equal("NA", resultA$message$max)
  # step
  expect_equal("2", resultA$message$step)
})
