# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_fluidpage.Rmd: do not edit by hand

test_that("fluidPage_dsfr works", {
  test <- fluidPage_dsfr(
      title = "Gouv",
      body = htmltools::div("test")
  )
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag.list")
})
