# WARNING - Generated by {fusen} from /dev/flat_composants/flat_fileInput.Rmd: do not edit by hand

test_that("fileInput_dsfr works", {
  test_html <- fileInput_dsfr(
    inputId = "file1", 
    label = "Importer vos données", 
    message = "seul le format csv est pris en charge"
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "fileInput_dsfr.Rda")
  )

  #' @description Verifer que le HTML est correct en sortie
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html))

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #  dans la fonction fileInput_dsfr puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "fileInput_dsfr.Rda"
  #                          )
  #         )


  # Ajouter des tests pour controler le type des parametres d'entree
  # Cela verifie que les 'assertthat' fonctionnent correctement


})
