# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkboxInput.Rmd: do not edit by hand

test_that("checkboxInput_dsfr_template works", {
  expect_true(inherits(checkboxInput_dsfr_template, "function")) 
  
    test <- checkboxInput_dsfr_template(
      inputId = 'test',
      label = 'label',
      choices = c('a', 'b'),
      selected = NULL,
      inline = FALSE
    )
  
  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))
})
