# WARNING - Generated by {fusen} from dev/flat_composants/flat_radioGroupButtons.Rmd: do not edit by hand

test_that("radioGroupButtons_dsfr works", {
  test_html <- radioGroupButtons_dsfr(
    inputId = "test",
    label = "Test",
    choices = c("A", "B"),
    selected = "A"
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")

  expect_error(
    radioGroupButtons_dsfr(
      inputId = "test",
      label = "Test error selected with more than one element",
      choices = c("A", "B"),
      selected = c("A", "B")
    ),
    regexp = "selected"
  )

  # test selected
  test_html_selected <- radioGroupButtons_dsfr(
    inputId = "test-selected",
    label = "Selected",
    choices = c("A", "B"),
    selected = "A"
  )

  snapshot_html_selected <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "radioGroupButtons_dsfr_selected.Rda"
    )
  )
  #' @description Verifie le parametre selected dans le HTML
  expect_equal(
    gsub("\\s|\\n", "", test_html_selected),
    gsub("\\s|\\n", "", snapshot_html_selected)
  )


  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioGroupButtons_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html_selected,
  #         file = file.path("tests/testthat/snapshot",
  #                          "radioGroupButtons_dsfr_selected.Rda"
  #                          )
  #         )
  #
})
