# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkboxInput.Rmd: do not edit by hand

test_that("checkboxInput_unique_dsfr_template works", {
  expect_true(inherits(checkboxInput_unique_dsfr_template, "function")) 
  
    test <- checkboxInput_unique_dsfr_template(inputId = 'test-1', name = 'test', choice_value = 'a', value = FALSE)
  
  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))
})
