# WARNING - Generated by {fusen} from /dev/flat_composants/flat_fluidpage.Rmd: do not edit by hand

test_that("fluidPage_dsfr works", {
  test <- fluidPage_dsfr(
    header = header_dsfr(
      intitule = "Prefet de",
      officiel = "Bretagne",
    ),
    title = "Gouv",
    body = htmltools::div("test")
  )
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag.list")
})
