# WARNING - Generated by {fusen} from /dev/flat_tools.Rmd: do not edit by hand

test_that("parse_to_xml works", {
  expect_true(inherits(parse_to_xml, "function")) 
  html_code <- '<button id="test" type="button" class="btn btn-default action-button">test</button>'
  
   
  test <- parse_to_xml(html_code)
  
  #' @description tester la classe du resultat de la fonction sur un caractere
  expect_s3_class(test, "XMLInternalElementNode")
  
  #' @description tester l'erreur si le code est déjà du XML
  expect_error(parse_to_xml(test))
  
  test2 <- parse_to_xml(
    htmltools::tagList(
      tags$div(id = "ok", name = "jean", "pierre")
    )
  )
  
  #' @description tester la classe du resultat de la fonction sur un shiny.tag
  expect_s3_class(test2, "XMLInternalElementNode")
  
  })
