# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkboxInput.Rmd: do not edit by hand

test_that("checkboxInput_dsfr works", {
  test_html <- checkboxInput_dsfr(
    inputId = "test", label = "Test", choices = c("A","B")
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")
  
  
   ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate), 
      #"tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate), 
      "checkboxInput_dsfr.Rda")
  )
  
  #' @description Verifie le HTML créé
  expect_equal(gsub("\\s|\\n", "", test_html),
               gsub("\\s|\\n", "", snapshot_html)) 

    # test selected
  test_html_selected <- checkboxInput_dsfr(
      inputId = "test-selected", 
      label = "Selected", 
      choices = c("A","B"),
      selected = "A")
  
  snapshot_html_selected <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate), 
      #"tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate), 
      "checkboxInput_dsfr_selected.Rda")
  )
  #' @description Verifie le parametre selected dans le HTML
  expect_equal(gsub("\\s|\\n", "", test_html_selected),
               gsub("\\s|\\n", "", snapshot_html_selected)) 
  
  
    # Si erreur au précedent test deux cas possible :
    #
    # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
    #
    # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
    #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
    #                              dans la fonction checkboxInput_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

 # saveRDS(test_html,
 #         file = file.path("tests/testthat/snapshot",
 #                          "checkboxInput_dsfr.Rda"
 #                          )
 #         )
 # saveRDS(test_html_selected,
 #         file = file.path("tests/testthat/snapshot",
 #                          "checkboxInput_dsfr_selected.Rda"
 #                          )
 #         )

})
#
test_that("checkboxInput_dsfr", {
  test <- checkboxInput_dsfr(
    inputId = "test1", label = "Test1", choices = c("A","B")
  )
  
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag")
  
  # with choice
  test_with_choice <- checkboxInput_dsfr(
    inputId = "test", label = "Test", choices = c("A" = "a", "B" = "b"), selected = "b"
  )
  # with choice_values and choice_name
  test_witch_choice_value <- checkboxInput_dsfr(
    inputId = "test", label = "Test", choice_values = c("a", "b"), choice_names = c("A", "B"), selected = "b"
  )
  
  expect_equal(test_with_choice, test_witch_choice_value)
  
  # error when choice and choice_values are NULL
  expect_error(
    checkboxInput_dsfr(inputId = "test", choice = NULL, choice_values = NULL)
  )
  
  # error if character vector choice_values and choice_names are not the same length
  expect_error(
    checkboxInput_dsfr(inputId = "test", choice = NULL, choice_values = c('a', 'b'), choice_names = c('A'))
  )
})
