# WARNING - Generated by {fusen} from dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

test_that("updateCheckboxInput_dsfr works", {
  expect_true(inherits(updateCheckboxInput_dsfr, "function"))
  sessA <- createModuleSession("modA")
  updateCheckboxInput_dsfr(
    session = sessA,
    inputId = "inCheckboxInput",
    label = "Un nouveau label",
    value = TRUE
  )
  
  resultA <- sessA$lastInputMessage
  # inputId
  expect_equal("inCheckboxInput", resultA$id)
  # label
  expect_equal("Un nouveau label", resultA$message$label)
  expect_equal(TRUE, resultA$message$value)
})
