# WARNING - Generated by {fusen} from dev/flat_composants/flat_panels.Rmd: do not edit by hand

test_that("tabsetPanel_dsfr_template works", {
  expect_true(inherits(tabsetPanel_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "tabsetPanel.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  nms <- names(
    as.list(
      args(tabsetPanel_dsfr_template)
    )
  )
  purrr::walk(
    nms[nms != ""],
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      expect_true(
        any(grepl(pattern = with_moustache, htmlfile)),
        label = paste0("sans moustache '", param, "'")
      )
    }
  )


    test_html <- tabsetPanel_dsfr_template(
      li = panel_one_li(
        "tab-1",
        "Tab 1"
      ),
      divs = panel_one_body(
        "tab-1",
        "Tab 1"
      )
    )


  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))

})
