# WARNING - Generated by {fusen} from /dev/flat_composants/flat_dateRangeInput.Rmd: do not edit by hand

test_that("dateRangeInput_dsfr works", {
  expect_true(inherits(dateRangeInput_dsfr, "function"))

  test_html <- dateRangeInput_dsfr(inputId = "daterange1",
                          label = "Date range:", start = "2001-01-01",
                          end = "2003-01-01")

  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")


  expect_error(
    dateRangeInput_dsfr(
      inputId = 123,
      label = "Date range:",
      start = "2001-01-01",
      end = "2003-01-01"
    )
  )

  expect_error(
    dateRangeInput_dsfr(
      inputId = "daterange1",
      label = 123,
      start = "2001-01-01",
      end = "2003-01-01"
    )
  )
  
  expect_error(
    dateRangeInput_dsfr(
      inputId = "daterange1",
      label = "Date range:",
      start = 123,
      end = "2003-01-01"
    )
  )

  expect_error(
    dateRangeInput_dsfr(
      inputId = "daterange1",
      label = "Date range:",
      end = 123,
      start = "2003-01-01"
    )
  )

  expect_error(
        dateRangeInput_dsfr(
      inputId = "daterange1",
      label = "Date range:"
    ),
    regexp = NA
  )

  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "dateRangeInput_dsfr.Rda"
    )
  )
  #' @description Verifie le parametre selected dans le HTML
  expect_equal(
    gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html)
  )


  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioButtons_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

   # saveRDS(test_html,
   #         file = file.path("tests/testthat/snapshot",
   #                          "dateRangeInput_dsfr.Rda"
   #                          )
   #         )

})
