# WARNING - Generated by {fusen} from /dev/flat_tools.Rmd: do not edit by hand

test_that("render_node works", {
  expect_true(inherits(render_node, "function"))
  html_code <- '<button id="test" type="button" class="btn btn-default action-button">test</button>'
  test <- parse_to_xml(html_code)


  result <- render_node(test, prefix = TRUE)

  #' @description tester le resultat de render_node
  expect_type(result, "character")
})
