# WARNING - Generated by {fusen} from dev/flat_composants/flat_selectInput.Rmd: do not edit by hand

test_that("selectInput_dsfr works", {
  expect_true(inherits(selectInput_dsfr, "function"))

  test_html <- selectInput_dsfr(
    inputId = "variable",
    label = "Variable:",
    choices = c(
      "Cylinders" = "cyl",
      "Transmission" = "am",
      "Gears" = "gear"
    )
  )

  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")


  expect_error(
    selectInput_dsfr(
      inputId = 1234,
      label = "Variable:",
      choices = c(
        "Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear"
      )
    )
  )

  expect_error(
    selectInput_dsfr(
      inputId = "variable",
      label = 1234,
      choices = c(
        "Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear"
      )
    )
  )

  expect_error(
    selectInput_dsfr(
      inputId = "variable",
      label = "Variable:",
      choices = c(1234, 5678)
    )
  )

  expect_error(
    selectInput_dsfr(
      inputId = "variable",
      label = "Variable:",
      choices = c(
        "Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear"
      ),
      selected = c("gear", "am")
    )
  )


  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "sliderInput_dsfr.Rda"
    )
  )
  #' @description Verifie le parametre selected dans le HTML
  expect_equal(
    gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html)
  )


  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioButtons_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  #  saveRDS(test_html,
  #          file = file.path("tests/testthat/snapshot",
  #                           "sliderInput_dsfr.Rda"
  #                           )
  #          )
  #
})
