# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_fluidpage.Rmd: do not edit by hand

test_that("fluidRow_dsfr works", {
  expect_true(inherits(fluidRow_dsfr, "function")) 
  test <- fluidRow_dsfr(
    shiny::p("Voici un exemple")
  )
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag.list")
})
