# WARNING - Generated by {fusen} from dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

test_that("checkboxGroupInput_dsfr works", {
  test_html <- checkboxGroupInput_dsfr(
    "variable",
    "Variables to show:",
    c("Cylinders" = "cyl",
      "Transmission" = "am",
      "Gears" = "gear")
  )

  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")


  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "checkboxGroupInput_dsfr.Rda")
  )
  #' @description Verifie le parametre selected dans le HTML
  expect_equal(
    gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html)
  )


  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioButtons_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "checkboxGroupInput_dsfr.Rda"
  #                          )
  #         )


  expect_error(
    checkboxGroupInput_dsfr(
      111,
      "Variables to show:",
      c("Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear")
    ),
    regexp = "inputId is not a character vector")


  expect_error(
    checkboxGroupInput_dsfr(
      "variable",
      444,
      c("Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear")
    ),
    regexp = "label is not a character vector")

  expect_error(
    checkboxGroupInput_dsfr(
      "variable",
      "A label",
      c("Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear"),
      inline = "fake"),
    regexp = "is.logical\\(inline\\) is not TRUE")
})
