# WARNING - Generated by {fusen} from /dev/flat_convert_to_dsfr.Rmd: do not edit by hand

test_that("convert_file_to_dsfr works", {

library(tibble)
  
mydir <- tempfile(pattern = "app")
dir.create(mydir)
golem::create_golem(
  mydir,
  overwrite = TRUE,
  open = FALSE
)

table_passage <- tibble(composant_shiny = c("actionButton","fluidPage"),
                        composant_dsfr = c("actionButton_dsfr","fluidPage_dsfr"))

fichier <- file.path(mydir,"R", "app_ui.R")
convert_file_to_dsfr(file = fichier, table_passage) 
fichier_transform <- readLines(fichier)

  #' @description le fluidPage de shiny a bien ete remplace

  expect_false(any(stringr::str_detect(fichier_transform, pattern = "fluidPage\\(")))
  
})
