# WARNING - Generated by {fusen} from dev/tools/flat_favicon.Rmd: do not edit by hand

test_that("use_favicon_dsfr works", {
  app <- file.path(tempdir(), "app")
  dir.create(app)
  # version shiny basique
  path_shiny_base <- paste0(app, "/www/favicon.ico")
  use_favicon_dsfr(path_app = app, golem_app = FALSE)
  expect_true(file.exists(path_shiny_base))
  
})
