# WARNING - Generated by {fusen} from /dev/flat_composants/flat_radioButtons.Rmd: do not edit by hand

test_that("radioButtons_dsfr works", {
  test <- radioButtons_dsfr(
    inputId = "test",
    label = "Test",
    choices = c("A", "B"),
    class = NULL
  )
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag")
})
