# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_header.Rmd: do not edit by hand

test_that("header_dsfr_template works", {
  expect_true(inherits(header_dsfr_template, "function")) 
  
    test <- header_dsfr_template(
     class = NULL,
     intitule = "Prefet de", 
     officiel = "Bretagne",
     url = "https://www.prefectures-regions.gouv.fr/bretagne",
     titre = "Accueil - Préfecture de Bretagne", 
     nom_site_service = "DREAL Bretagne", 
     baseline = "description"
    )
  
  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))
})
