# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_fluidpage.Rmd: do not edit by hand

test_that("fluidPage_dsfr_template works", {
  expect_true(inherits(fluidPage_dsfr_template, "function")) 
  
  test <- fluidPage_dsfr_template(
    title = "titre",
    body = NULL
  )
  
  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))
})
