# WARNING - Generated by {fusen} from /dev/flat_composants/flat_actionButton.Rmd: do not edit by hand

test_that("actionButton_dsfr works", {
  
  test <- actionButton_dsfr(
    inputId = "test",
    label = "test",
    class = "fr-btn--icon-left fr-icon-checkbox-circle-line"
  )
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag")
})
