# WARNING - Generated by {fusen} from /dev/flat_composants/flat_fluidpage.Rmd: do not edit by hand

test_that("fluidPage_dsfr_template works", {
  expect_true(inherits(fluidPage_dsfr_template, "function"))

  test <- fluidPage_dsfr_template(
    header = NULL,
    title = "titre",
    body = NULL
  )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))
})
