# WARNING - Generated by {fusen} from dev/flat_composants/flat_panels.Rmd: do not edit by hand

test_that("updateTabsetPanel_dsfr works", {
  expect_true(inherits(updateTabsetPanel_dsfr, "function"))

  sessA <- createModuleSession("modA")

  expect_error(
  updateTabsetPanel_dsfr(
    session = sessA,
    inputId = "myid",
    selected = NULL
  ),
  regexp = "Vous devez sp\u00e9cifier"
  )
})
