# WARNING - Generated by {fusen} from dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

test_that("updateCheckboxGroupInput_dsfr works", {
  expect_true(inherits(updateCheckboxGroupInput_dsfr, "function"))

  sessA <- createModuleSession("modA")

  updateCheckboxGroupInput_dsfr(
    session = sessA,
    inputId = "variable",
    label = "Un nouveau label",
    choices = c("choice-a" = "a", "B" = "b"),
    selected = "a"
  )


  resultA <- sessA$lastInputMessage
  # inputId
  expect_equal("modA-variable", resultA$id)
  # label
  expect_equal("Un nouveau label", resultA$message$label)
  # HTML content
  # expect_true(grepl('id\\s*=\\s*\"modA-variable-1\"', resultA$message$options))
  # expect_true(grepl('value\\s*=\\s*"a"', resultA$message$options))
  # expect_true(grepl('choice-a', resultA$message$options))
  # expect_true(grepl('checked', resultA$message$options))
})
