# WARNING - Generated by {fusen} from /dev/flat_composants/flat_numericInput.Rmd: do not edit by hand

test_that("numericInput_dsfr works", {
  test_html <- numericInput_dsfr(
    inputId = "mynumericinput",
    label = "Numeric input",
    value = 12,
    min = 0,
    max = NA,
    step = 2
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "numericInput_dsfr.Rda"
    )
  )

  #' @description Verifer que le HTML est correct en sortie
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(
    gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html)
  )

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #  dans la fonction numericInput_dsfr puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "numericInput_dsfr.Rda"
  #                          )
  #         )


  # Ajouter des tests pour controler le type des parametres d'entree
  # Cela verifie que les 'assertthat' fonctionnent correctement

  #' @description tester le type du param `inputId`
  expect_error(
    numericInput_dsfr(
      inputId = 1234,
      label = "toto",
      value = 1
    )
  )

  #' @description tester le type du param `label`
  expect_error(
    numericInput_dsfr(
      inputId = "1234",
      label = 1234,
      value = 1
    )
  )

  #' @description tester le type du param `value`
  expect_error(
    numericInput_dsfr(
      inputId = "1234",
      label = "1234",
      value = "aaaa"
    )
  )

  #' @description tester le type du param `min`
  expect_error(
    numericInput_dsfr(
      inputId = "1234",
      label = "1234",
      value = 1,
      min = "aaaa"
    )
  )

  #' @description tester le type du param `max`
  expect_error(
    numericInput_dsfr(
      inputId = "1234",
      label = "1234",
      value = 1,
      max = "aaaa"
    )
  )

  #' @description tester le type du param `step`
  expect_error(
    numericInput_dsfr(
      inputId = "1234",
      label = "1234",
      value = 1,
      step = "aaaa"
    )
  )
})
