# WARNING - Generated by {fusen} from /dev/flat_composants/flat_fluidpage.Rmd: do not edit by hand

test_that("fluidPage_dsfr_template works", {
  expect_true(inherits(fluidPage_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      "v1.7.2",
      "composant",
      "fluidpage.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  purrr::walk(
    c(
      "header",
      "title",
      "body"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      message(with_moustache)
      expect_true(any(grepl(pattern = with_moustache, htmlfile)))
      message("test passed :-)")
    }
  )


  test <- fluidPage_dsfr_template(
    header = "header",
    title = "titre",
    body = "body"
  )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
      header = "header",
      title = "titre",
      body = "body"
    ),
    function(param) {
      message(param)
      expect_true(any(grepl(pattern = param, test)))
      message("test passed :-)")
    }
  )

  ## lecture snapshot
  snapshot <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "2022-08-12-fluidPage_dsfr_template.Rda"
    )
  )

  #' @description Verifie la presence du parametre class
  expect_equal(htmlfile, snapshot)

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction fluidPage_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(htmlfile,
  #         file = file.path("tests/testthat/snapshot",
  #                          paste0(Sys.Date(), "-","fluidPage_dsfr_template.Rda")
  #                          )
  #         )
  #
  #
})
