# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_header.Rmd: do not edit by hand

test_that("header_dsfr works", {
  test <- header_dsfr(
     intitule = "Prefet de", 
     officiel = "Bretagne",
  )
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag")
})
