# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_fluidpage.Rmd: do not edit by hand

test_that("column_dsfr works", {
  expect_true(inherits(column_dsfr, "function")) 
  test <- column_dsfr(
    3,
    shiny::p("Voici un exemple")
  )
  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag.list")
})
