# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_radioButtons.Rmd: do not edit by hand

test_that("radioButtons_dsfr_template works", {
  expect_true(inherits(radioButtons_dsfr_template, "function"))

  test <- radioButtons_dsfr_template(
    inputId = "test",
    label = "Test",
    choix = c("A", "B"),
    class = NULL
  )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))
})
