# WARNING - Generated by {fusen} from /dev/flat_composants/flat_header.Rmd: do not edit by hand

test_that("header_dsfr_template works", {
  expect_true(inherits(header_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      "v1.7.2",
      "composant",
      "entete.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  purrr::walk(
    c(
      "class",
      "intitule",
      "officiel",
      "url",
      "titre",
      "nom_site_service",
      "baseline"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      message(with_moustache)
      expect_true(any(grepl(pattern = with_moustache, htmlfile)))
      message("test passed :-)")
    }
  )


  test <- header_dsfr_template(
    class = "class",
    intitule = "Prefet de",
    officiel = "Bretagne",
    url = "https://www.prefectures-regions.gouv.fr/bretagne",
    titre = "Accueil - Préfecture de Bretagne",
    nom_site_service = "DREAL Bretagne",
    baseline = "description"
  )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
      class = "class",
      intitule = "Prefet de",
      officiel = "Bretagne",
      url = "https://www.prefectures-regions.gouv.fr/bretagne",
      titre = "Accueil - Préfecture de Bretagne",
      nom_site_service = "DREAL Bretagne",
      baseline = "description"
    ),
    function(param) {
      message(param)
      expect_true(any(grepl(pattern = param, test)))
      message("test passed :-)")
    }
  )

  ## lecture snapshot
  snapshot <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "2022-08-12-header_dsfr_template.Rda"
    )
  )

  #' @description Verifie la presence du parametre class
  expect_equal(htmlfile, snapshot)

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction header_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(htmlfile,
  #         file = file.path("tests/testthat/snapshot",
  #                          paste0(Sys.Date(), "-","header_dsfr_template.Rda")
  #                          )
  #         )
})
