# WARNING - Generated by {fusen} from /dev/flat_composants/flat_radioButtons.Rmd: do not edit by hand

test_that("updateRadioButtons_dsfr works", {
  expect_true(inherits(updateRadioButtons_dsfr, "function"))
})
