# WARNING - Generated by {fusen} from /dev/flat_data_filtre.Rmd: do not edit by hand

#' data_filtre 
#' 
#' 
#' @param df dataframe iris a filtrer
#' @param species character "setosa", "versicolor" ou  "virginica"
#' @param sepal_petal character "Sepal.Length" ou "Petal.Length"
#' @param max numeric maximum de "sepal" ou "petal" Length
#' @return dataframe
#' @export
#' @examples
#' data_filtre(iris, "setosa", "Sepal.Length", 6.2)
data_filtre <- function(df, species, sepal_petal, max) {
  res <- df[df[["Species"]] == species & df[[sepal_petal]] <= max, ]
  return(res)
}
