---
title: "flat_new_one.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

# actionButton_dsfr_template
    
```{r function-actionButton_dsfr_template}
#' actionButton_dsfr_template
#' 
#' @param inputId id de l'input
#' @param label label du bouton
#' @param class des classes a ajouter si necessaire
#'
#' @importFrom htmltools htmlTemplate
#' @return html
actionButton_dsfr_template <- function(
    inputId,
    label,
    class
){
  
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant", 
      "bouton.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    class = class
  )
}

```
  
  
```{r tests-actionButton_dsfr_template}
test_that("actionButton_dsfr_template works", {
  expect_true(inherits(actionButton_dsfr_template, "function")) 
  
  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE), 
      "composant", 
      "bouton.html",
      package = "shinygouv"
    )
  )
  
  #' @description Comparer les parametres par rapport a ceux de la version precedente
  
  purrr::walk(
    c("inputId","class","label"),
    function(param){
      with_moustache <- paste0("\\{\\{",param,"\\}\\}")
      expect_true(any(grepl(pattern = with_moustache, htmlfile)),
                  label = paste0("sans moustache '", param, "'"))
    })
  
  test_html <- actionButton_dsfr_template(inputId = "testId",
                                     label = "test", 
                                     class = "fr-btn--icon-left fr-icon-checkbox-circle-line")
  
  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))
  
  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
      "testId",
      "fr-btn--icon-left fr-icon-checkbox-circle-line",
      "test"
      ),
    function(param){
      expect_true(any(grepl(pattern = param, test_html)), 
                  label = paste0("remplacement de '", param, "'"))
    })

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
                     "actionButton_dsfr_template.Rda")
  )
  
  #' @description Verifie la presence du parametre class
  expect_equal(gsub("\\s|\\n", "", test_html),
               gsub("\\s|\\n", "", snapshot_html)) 
  
    # Si erreur au précedent test deux cas possible :
    #
    # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
    #
    # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
    #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
    #                              dans la fonction actionButton_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

 # saveRDS(test_html,
 #         file = file.path("tests/testthat/snapshot",
 #                          "actionButton_dsfr_template.Rda"
 #                          )
 #         )
  
})
```
  

# actionButton_dsfr

```{r function-actionButton_dsfr}
#' actionButton_dsfr
#' 
#' @param inputId id de l'input
#' @param label label du bouton
#' @param class des classes a ajouter si necessaire
#' 
#' @return html
#' 
#' @export
#'
#' @examples
actionButton_dsfr <- function(
    inputId,
    label,
    class = NULL
  ) {
  
  
  actionButton_dsfr_template(
    inputId,
    label,
    class
  ) %>%
    parse_html()

}
```

```{r examples-actionButton_dsfr}
actionButton_dsfr(
  inputId = "test",
  label = "test",
  class = "fr-btn--icon-left fr-icon-checkbox-circle-line"
)
```

```{r tests-actionButton_dsfr}
test_that("actionButton_dsfr works", {
  
  test_html <- actionButton_dsfr(
    inputId = "test",
    label = "test",
    class = "fr-btn--icon-left fr-icon-checkbox-circle-line"
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")
  
  #' @description Verifer que le HTML est correct en sortie
    ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "actionButton_dsfr.Rda")
  )
  
  #' @description Verifie la presence du parametre class
  # Retire tous les espaces et saut de ligne pour la comparaison 
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
               gsub("\\s|\\n", "", snapshot_html)) 
  
    # Si erreur au précedent test deux cas possible :
    #
    # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
    #
    # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
    #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
    #                              dans la fonction actionButton_dsfr puis lancer le saveRDS, relancer le test et recommenter le saveRDS

 # saveRDS(test_html,
 #         file = file.path("tests/testthat/snapshot",
 #                          "actionButton_dsfr.Rda"
 #                          )
 #         )
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly

fusen::inflate(flat_file = "dev/flat_composants/flat_actionButton.Rmd", 
                vignette_name = "actionButton_dsfr")
```

