---
title: "flat_new_one.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

# withSpinner html

```{r function-addWithSpinner}
#' spinner-specific html code
#' @importFrom htmltools HTML
#' @return an html code
#' @examples addWithSpinner()
#' @filename withSpinner_dsfr
#' @noRd
addWithSpinner <- function() {
  HTML('<div class="lds-ring" id = "lds-ring" style="display:none"><div></div><div></div><div></div><div></div></div>')
}
```

```{r tests-addWithSpinner}
test_that("addWithSpinner works", {
  spinner <- addWithSpinner()
  expect_true(inherits(spinner, "html"))
})
```


# showSpinner_dsfr
    
```{r function-showSpinner_dsfr}
#' Affiche le spinner
#'
#' Affiche le spinner dans le cadre d'un appel à `shinygouv::withSpinner_dsfr()`
#' @param inputId id du spinner
#' @param session session
#' @return side effect. Affiche le spinner
#' @filename withSpinner_dsfr
#' @noRd
showSpinner_dsfr <- function(
  inputId,
  session = shiny::getDefaultReactiveDomain()
    ) {
  session$sendCustomMessage("show_spinner", inputId)
}
```

```{r tests-showSpinner_dsfr}
test_that("showSpinner_dsfr works", {
  expect_true(inherits(showSpinner_dsfr, "function"))
})
```
  
  
# hideSpinner_dsfr
    
```{r function-hideSpinner_dsfr}
#' Masque le spinner
#'
#' Masque le spinner dans le cadre d'un appel à `shinygouv::withSpinner_dsfr()`
#' @param inputId id du spinner
#' @param session session
#' @return side effect. Masque le spinner
#' @filename withSpinner_dsfr
#' @noRd
hideSpinner_dsfr <- function(
  inputId,
  session = shiny::getDefaultReactiveDomain()
    ) {
  session$sendCustomMessage("hide_spinner", inputId)
}
```

```{r tests-hideSpinner_dsfr}
test_that("hideSpinner_dsfr works", {
  expect_true(inherits(hideSpinner_dsfr, "function"))
})
```  

# withSpinner_dsfr

```{r function-withSpinner_dsfr}
#' withSpinner_dsfr
#'
#' Permet d'afficher un spinner lors d'un calcul prenant du temps, s'inspire du fonctionnement de [shiny::withProgress()]
#'
#' @param expr L'opération a réaliser.
#' @param session session shiny
#' @filename withSpinner_dsfr
#' @return html#'
#' @export
withSpinner_dsfr <- function(
  expr,
  session = shiny::getDefaultReactiveDomain()
    ) {
  showSpinner_dsfr(inputId = "lds-ring", session = session)
  force(expr)
  on.exit(hideSpinner_dsfr(inputId = "lds-ring", session = session))
}
```

```{r examples-withSpinner_dsfr, eval = FALSE}
#' \dontrun{
library(shiny)
library(shinygouv)

ui <- fluidPage_dsfr(
  header = header_dsfr(
    intitule = "Intitule",
    officiel = "Officiel",
    nom_site_service = "Nom du site / service",
    baseline = "baseline - precisions sur l organisation",
    class = "fr-m-1w"
  ),
  title = "Exemple",
  fluidRow_dsfr(
    column_dsfr(
      0,
      shiny::p("Exemple colonne")
    ),
    actionButton_dsfr(
      inputId = "showspinner",
      label = "Afficher le spinner"
    )
  )
)

server <- function(input, output, session) {
  observeEvent(
    input$showspinner,
    {
      withSpinner_dsfr(
        expr = {
          message("Je vais m'afficher pendant 5 secondes")
          Sys.sleep(5)
        }
      )
    }
  )
}

shinyApp(ui, server)
#' }
```

```{r tests-withSpinner_dsfr}
test_that("withSpinner_dsfr works", {
  expect_true(inherits(withSpinner_dsfr, "function"))
})
```

```{r development-inflate, eval=FALSE}
fusen::inflate(
  flat_file = "dev/flat_composants/flat_withSpinner.Rmd",
  vignette_name = "withSpinner_dsfr",
  check = FALSE,
  overwrite = TRUE,
  open_vignette = FALSE
)
```
