---
title: "toggleSwitch_dsfr"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

# toggleSwitch_dsfr_template
    
```{r function-toggleSwitch_dsfr_template}
#' toggleSwitch_dsfr_template
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
toggleSwitch_dsfr_template <- function(
    inputId,
    label,
    activate,
    deactivate # ajouter vos params
    ) {

    htmltools::htmlTemplate(
        filename = system.file(
            get_dsfr_version(with_v = TRUE),
            "composant",
            "toggleswitch.html",
            package = "shinygouv"
        ),
        inputId = inputId,
        label = label,
        activate = activate,
        deactivate = deactivate
        # ajouter vos params
    )
}
```
  
  
```{r tests-toggleSwitch_dsfr_template}
test_that("toggleSwitch_dsfr_template works", {
    expect_true(inherits(toggleSwitch_dsfr_template, "function"))

    htmlfile <- readLines(
        system.file(
            get_dsfr_version(with_v = TRUE),
            "composant",
            "toggleswitch.html",
            package = "shinygouv"
        )
    )

    #' @description Comparer les parametres par rapport a ceux de la version precedente

    purrr::walk(
        c(
            "inputId",
            "label",
            "activate",
            "deactivate" # ajouter vos params
        ),
        function(param) {
            with_moustache <- paste0("\\{\\{", param, "\\}\\}")
            expect_true(any(grepl(pattern = with_moustache, htmlfile)),
                label = paste0("sans moustache '", param, "'"))
        })


    test_html <- toggleSwitch_dsfr_template(
        inputId = "test",
        label = "test",
        activate = "act",
        deactivate = "deact" # ajouter vos params
    )

    #' @description tester si tous les params sont remplaces
    expect_false(grepl(pattern = "\\{\\{", test_html))


    #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

    purrr::walk(
        c(
            inputId = "test",
            label = "test",
            activate = "act",
            deactivate = "deact"
        ),
        function(param) {
            expect_true(any(grepl(pattern = param, test_html)),
                label = paste0("remplacement de '", param, "'"))
        })

    ## lecture snapshot
    snapshot_html <- readRDS(
        file = file.path(
            "snapshot", # pour passer les tests en production (apres le inflate),
            # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
            "toggleSwitch_dsfr_template.Rda")
    )

    #' @description Verifie le HTML créé
    # Retire tous les espaces et saut de ligne pour la comparaison
    # Pour eviter les problèmes inter-OS
    expect_equal(gsub("\\s|\\n", "", test_html),
        gsub("\\s|\\n", "", snapshot_html))

    # Si erreur au précedent test deux cas possible :
    #
    # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
    #
    # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
    #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
    #  dans la fonction toggleSwitch_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

    # saveRDS(test_html,
    #         file = file.path("tests/testthat/snapshot",
    #                          "toggleSwitch_dsfr_template.Rda"
    #                          )
    #         )


})
```
  

# toggleSwitch_dsfr

```{r function-toggleSwitch_dsfr}
#' toggleSwitch_dsfr
#'
#'
#' @return html
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param activate sous texte quand activé
#' @param deactivate sous texte quand desactivé
#'
#' @export
#'
#' @examples
toggleSwitch_dsfr <- function(
    inputId,
    label,
    activate = "",
    deactivate = ""
    ) {

    # check les params
    assertthat::assert_that(is.character(label))
    assertthat::assert_that(is.character(inputId))
    assertthat::assert_that(is.character(activate))
    assertthat::assert_that(is.character(deactivate))


    toggleSwitch_dsfr_template(
        inputId = inputId,
        label = label,
        activate = activate,
        deactivate = deactivate
    ) %>%
        parse_html()

}
```

```{r examples-toggleSwitch_dsfr}
if (interactive()) {
    library(shiny)
    ui <- fluidPage_dsfr(
        toggleSwitch_dsfr(inputId = "test", label = "test")
    )

    server <- function(input, output, session) {
        observeEvent(input$test, {
            message(input$test)
            message("coucou")
        })
    }

    shinyApp(ui, server)
}
```

```{r tests-toggleSwitch_dsfr}
test_that("toggleSwitch_dsfr works", {
    test_html <- toggleSwitch_dsfr(
        inputId = "test",
        label = "test",
        activate = "test",
        deactivate = "test"
    )

    #' @description tester si shiny.tag
    expect_s3_class(test_html, "shiny.tag")

    ## lecture snapshot
    snapshot_html <- readRDS(
        file = file.path(
            "snapshot", # pour passer les tests en production (apres le inflate),
            # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
            "toggleSwitch_dsfr.Rda")
    )

    #' @description Verifer que le HTML est correct en sortie
    # Retire tous les espaces et saut de ligne pour la comparaison
    # Pour eviter les problèmes inter-OS
    expect_equal(
        gsub("\\s|\\n", "", test_html),
        gsub("\\s|\\n", "", snapshot_html)
    )

    # Si erreur au précedent test deux cas possible :
    #
    # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
    #
    # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
    #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
    #  dans la fonction toggleSwitch_dsfr puis lancer le saveRDS, relancer le test et recommenter le saveRDS

    # saveRDS(test_html,
    #         file = file.path("tests/testthat/snapshot",
    #                          "toggleSwitch_dsfr.Rda"
    #                          )
    #         )


    # Ajouter des tests pour controler le type des parametres d'entree
    # Cela verifie que les 'assertthat' fonctionnent correctement

    #' @description tester le type du param `monparam`
    expect_error(
        toggleSwitch_dsfr(
            inputId = 12
        )
    )
})
```

# update_toggleSwitch_dsfr

Pour les fonctions de type `update_*`, voir l'exemple de "flat_radioButtons.Rmd"

```{r function-update_toggleSwitch_dsfr}
#' Update ToggleSwitch
#'
#' @importFrom shiny updateCheckboxInput
#' @inheritParams shiny::updateCheckboxInput
#' @inheritParams toggleSwitch_dsfr
updateToggleSwitch_dsfr <- function(
    session,
    inputId,
    label = NULL,
    value = NULL,
    activate = NULL,
    deactivate = NULL

    ) {
    shiny:::validate_session_object(session)
  
    ns <- session$ns
  
    message <- utils::getFromNamespace("dropNulls", "shiny")(
        list(
            label = label,
            value = value
        )
    )

    session$sendInputMessage(
        inputId,
        message
    )

    session$sendCustomMessage(
        "activate_toggle",
        list(
            inputId = ns(inputId),
            activate = activate
        )
    )

    session$sendCustomMessage(
        "deactivate_toggle",
        list(
            inputId = ns(inputId),
            deactivate = deactivate
        )
    )
}
```

```{r examples-update_toggleSwitch_dsfr}
if (interactive()) {
    library(shiny)
    ui <- fluidPage_dsfr(
        toggleSwitch_dsfr(inputId = "test", label = "test"),
        actionButton_dsfr("update", "Update toggle")
    )

    server <- function(input, output, session) {
        observeEvent(input$test, {
            message(input$test)
            message("coucou")
        })

        observeEvent(input$update, {
            updateToggleSwitch_dsfr(
                session = session,
                inputId = "test",
                value = TRUE,
                label = "Update",
                activate = "test",
                deactivate = ""
            )
        })
    }

    shinyApp(ui, server)
}
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly

fusen::inflate(
    flat_file = "dev/flat_composants/flat_toggleswitch.Rmd",
    vignette_name = NA,
    check = FALSE
)
```

