---
title: "flat_new_one.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

# radioGroupButtons_unique_dsfr_template

```{r function-radioGroupButtons_unique_dsfr_template}
#' radioGroupButtons_unique_dsfr_template
#'
#' @param inputId id de l'input avec indexation
#' @param choix choix une valeur a selectionner
#' @param nom_choix le nom de la valeur a selectionner/afficher
#' @param name nom de l'inputId sans indexation
#' @param selected Bouton sélectionné ou non
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#'
#' @importFrom htmltools htmlTemplate
#' @return html
radioGroupButtons_unique_dsfr_template <-
  function(
      inputId,
      choix,
      nom_choix,
      name,
      selected = FALSE,
      inline = FALSE
      ) {
    htmltools::htmlTemplate(
      filename = system.file(
        get_dsfr_version(with_v = TRUE),
        "composant",
        "radiogroupbutton_unique.html",
        package = "shinygouv"
      ),
      inputId = inputId,
      name = name,
      nom_choix = nom_choix,
      value_choix = choix,
      selected = if (isTRUE(selected)) "" else "fr-btn--secondary",
      checked = if (isTRUE(selected)) 'checked=""' else NULL,
      inline = inline
    )
  }
```
  
  
```{r tests-radioGroupButtons_unique_dsfr_template}
test_that("radioGroupButtons_unique_dsfr_template works", {
  expect_true(inherits(radioGroupButtons_unique_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "radiogroupbutton_unique.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  purrr::walk(
    c(
      "inputId",
      "name",
      "nom_choix",
      "selected"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      expect_true(
        any(grepl(pattern = with_moustache, htmlfile)),
        label = paste0("sans moustache '", param, "'")
      )
    }
  )


  test_html <- radioGroupButtons_unique_dsfr_template(
    inputId = "test-1",
    name = "test",
    choix = c("A"),
    nom_choix = "Choix A"
  )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
      inputId = "test-1",
      name = "test",
      choix = c("A"),
      nom_choix = "Choix A"
    ),
    function(param) {
      expect_true(
        any(grepl(pattern = param, test_html)),
        label = paste0("remplacement de '", param, "'")
      )
    }
  )

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "radioGroupButtons_unique_dsfr_template.Rda"
    )
  )

  #' @description Verifie le HTML créé
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(
    gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html)
  )

  # Test "checked"
  test_html_selected <- radioGroupButtons_unique_dsfr_template(
    inputId = "test-1",
    name = "test",
    choix = c("A"),
    nom_choix = "Choix A",
    selected = "A"
  )

  snapshot_html_selected <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "radioGroupButtons_unique_dsfr_template_selected.Rda"
    )
  )

  #' @description Verifie la presence du parametre selected
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(
    gsub("\\s|\\n", "", test_html_selected),
    gsub("\\s|\\n", "", snapshot_html_selected)
  )

  # Si erreur au précedent test deux cas possibles :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioGroupButtons_unique_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "radioGroupButtons_unique_dsfr_template.Rda"
  #                          )
  #         )
  #
  # saveRDS(test_html_selected,
  #         file = file.path("tests/testthat/snapshot",
  #                          "radioGroupButtons_unique_dsfr_template_selected.Rda"
  #                          )
  #         )
})
```

# radioGroupButtons_sfr_template

```{r function-radioGroupButtons_dsfr_template}
#' radioGroupButtons_dsfr_template
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choix choix Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element sélectionné (NULL par defaut)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement). NON IMLPEMENTE
#'
#' @importFrom htmltools htmlTemplate tagList
#' @importFrom purrr pmap map_chr
#' @return html
radioGroupButtons_dsfr_template <- function(
    inputId,
    label,
    choix,
    selected = NULL,
    inline = FALSE
    ) {
  if (isTRUE(inline)) {
    inline_value <- "fr-fieldset__element--inline"
    container_inline <- "shiny-input-container-inline"
  } else {
    inline_value <- ""
    container_inline <- ""
  }


  if (is.null(names(choix))) {
    nom_choix <- choix
  } else {
    nom_choix <- names(choix)
  }

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "radiogroupbutton.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    container_inline = container_inline,
    choix = pmap(
      list(
        .x = choix,
        .y = nom_choix,
        .nb = seq_along(choix),
        .inline = rep(
          inline_value,
          length(choix)
        )
      ),
      function(.x, .y, .nb, .inline) {
        radioGroupButtons_unique_dsfr_template(
          # inputId = paste0(inputId, "-", .nb),
          inputId = paste0(inputId, "-", .x),
          name = inputId,
          choix = .x,
          nom_choix = .y,
          selected = identical(.x, selected),
          inline = .inline
        )
      }
    ) %>%
      htmltools::tagList()
  )
}
```
  
```{r tests-radioGroupButtons_dsfr_template}
test_that("radioGroupButtons_dsfr_template works", {
  expect_true(inherits(radioGroupButtons_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "radiogroupbutton.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  purrr::walk(
    c(
      "inputId",
      "label",
      "choix",
      "container_inline"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      expect_true(
        any(grepl(pattern = with_moustache, htmlfile)),
        label = paste0("sans moustache '", param, "'")
      )
    }
  )


  test_html <- radioGroupButtons_dsfr_template(
    inputId = "test",
    label = "Test",
    choix = c("A", "B"),
    selected = "A"
  )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
      inputId = "test",
      label = "Test",
      choix = c("A", "B"),
      selected = "B"
    ),
    function(param) {
      expect_true(
        any(grepl(pattern = param, test_html)),
        label = paste0("remplacement de '", param, "'")
      )
    }
  )

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "radioGroupButtons_dsfr_template.Rda"
    )
  )

  #' @description Verifie le HTML créé
  expect_equal(
    gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html)
  )


  # test selected
  test_html_selected <- radioGroupButtons_dsfr_template(
    inputId = "test",
    label = "Test",
    choix = c("A name" = "A", "B name" = "B"),
    selected = "B"
  )
  snapshot_html_selected <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "radioGroupButtons_dsfr_template_selected.Rda"
    )
  )
  #' @description Verifie le parametre selected dans le HTML
  expect_equal(
    gsub("\\s|\\n", "", test_html_selected),
    gsub("\\s|\\n", "", snapshot_html_selected)
  )


  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioGroupButtons_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "radioGroupButtons_dsfr_template.Rda"
  #                          )
  #         )
  #
  # saveRDS(test_html_selected,
  #         file = file.path("tests/testthat/snapshot",
  #                          "radioGroupButtons_dsfr_template_selected.Rda"
  #                          )
  #         )
})
```

L'implementation de la fonction `radioGroupButtons_dsfr()` reste quant à elle similaire à la suite de la procédure.

# radioGroupButtons_dsfr

```{r function-radioGroupButtons_dsfr}
#' radioGroupButtons_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element sélectionné (NULL par défaut)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @return html
#'
#' @export
#'
#' @examples
radioGroupButtons_dsfr <- function(
    inputId,
    label,
    choices,
    selected = NULL,
    inline = FALSE
    ) {
  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.character(choices))
  assertthat::assert_that(length(selected) <= 1)
  assertthat::assert_that(is.logical(inline))

  radioGroupButtons_dsfr_template(
    inputId = inputId,
    label = label,
    choix = choices,
    selected = selected,
    inline = inline
  ) %>%
    parse_html()
}
```

```{r examples-radioGroupButtons_dsfr}
if (interactive()) {
  library(shiny)
  library(shinygouv)

  ui <- fluidPage_dsfr(
    header = header_dsfr(
      intitule = "Intitule",
      officiel = "Officiel",
      nom_site_service = "Nom du site / service",
      baseline = "baseline - precisions sur l organisation",
      class = "fr-m-1w"
    ),
    title = "Exemple",
    fluidRow_dsfr(
      radioGroupButtons_dsfr(
        inputId = "espece_radiogroupbutton",
        label = "Especes (radio group button avec inline = FALSE)",
        choices = c("Setosa" = "setosa", "Versicolor" = "versicolor", "Virginica" = "virginica"),
        selected = "virginica",
        inline = FALSE
      )
    ),
    fluidRow_dsfr(
      radioGroupButtons_dsfr(
        inputId = "espece_radiogroupbutton2",
        label = "Especes (radio group button avec inline = TRUE)",
        choices = c("Setosa" = "setosa", "Versicolor" = "versicolor", "Virginica" = "virginica"),
        selected = "virginica",
        inline = TRUE
      )
    ),
    fluidRow_dsfr(
      verbatimTextOutput(outputId = "outputespece_radiogroupbutton"),
      verbatimTextOutput(outputId = "outputespece_radiogroupbutton2")
    )
  )

  server <- function(input, output, session) {
    output$outputespece_radiogroupbutton <- renderText({
      paste("Esp\u00e8ce radiogroupbutton avec inline = FALSE :", input$espece_radiogroupbutton)
    })
    output$outputespece_radiogroupbutton2 <- renderText({
      paste("Esp\u00e8ce radiogroupbutton avec inline = TRUE :", input$espece_radiogroupbutton2)
    })
  }

  shinyApp(ui, server)
}
```

```{r tests-radioGroupButtons_dsfr}
test_that("radioGroupButtons_dsfr works", {
  test_html <- radioGroupButtons_dsfr(
    inputId = "test",
    label = "Test",
    choices = c("A", "B"),
    selected = "A"
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")

  expect_error(
    radioGroupButtons_dsfr(
      inputId = "test",
      label = "Test error selected with more than one element",
      choices = c("A", "B"),
      selected = c("A", "B")
    ),
    regexp = "selected"
  )

  # test selected
  test_html_selected <- radioGroupButtons_dsfr(
    inputId = "test-selected",
    label = "Selected",
    choices = c("A", "B"),
    selected = "A"
  )

  snapshot_html_selected <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "radioGroupButtons_dsfr_selected.Rda"
    )
  )
  #' @description Verifie le parametre selected dans le HTML
  expect_equal(
    gsub("\\s|\\n", "", test_html_selected),
    gsub("\\s|\\n", "", snapshot_html_selected)
  )


  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioGroupButtons_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html_selected,
  #         file = file.path("tests/testthat/snapshot",
  #                          "radioGroupButtons_dsfr_selected.Rda"
  #                          )
  #         )
  #
})
```

# updateRadioGroupButtons_dsfr
    
```{r function-updateRadioGroupButtons_dsfr}
#' updateRadioGroupButtons_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element sélectionné (NULL par défaut)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#'
#' @importFrom htmltools tagList
#' @importFrom purrr pmap
#' @return html
#'
#' @export
updateRadioGroupButtons_dsfr <- function(
    inputId,
    label = NULL,
    choices = NULL,
    selected = NULL,
    inline = FALSE,
    session = shiny::getDefaultReactiveDomain()
    ) {
  ns <- session$ns

  if (is.null(names(choices))) {
    nom_choix <- choices
  } else {
    nom_choix <- names(choices)
  }

  if (!is.null(choices)) {
    tag <- radioGroupButtons_dsfr(
      inputId = ns(inputId),
      label = if (!is.null(label)) label else "",
      choices = choices,
      selected = selected,
      inline = inline
    ) %>%
      htmltools::tagQuery()

    choices <- tag$find(".shiny-options-group")$selectedTags()
    choices <- as.character(choices)
  }

  message <- utils::getFromNamespace("dropNulls", "shiny")(list(
    label = label,
    options = choices,
    value = selected
  ))

  if (!is.null(selected)) {
    selected <- as.character(selected)
    button_to_color <- paste0(ns(inputId), "-", selected)
    session$sendCustomMessage(
      "updateRadioGroupColorButton",
      list(inputId = button_to_color)
    )
  }
  session$sendInputMessage(inputId, message)

  # Choices have to changes to set up inline
  if (!is.null(choices)) {
    update_inline(ns(inputId), inline, session)
  }

}
```
  
```{r example-updateRadioGroupButtons_dsfr}
if (interactive()) {
  library(shiny)
  library(shinygouv)

  ui <- fluidPage_dsfr(
    header = header_dsfr(
      intitule = "Intitule",
      officiel = "Officiel",
      nom_site_service = "Nom du site / service",
      baseline = "baseline - precisions sur l organisation",
      class = "fr-m-1w"
    ),
    title = "Exemple",
    fluidRow_dsfr(
      radioGroupButtons_dsfr(
        inputId = "espece_radiogroupbutton",
        label = "Especes (radio group button avec inline = FALSE)",
        choices = c("Setosa" = "setosa", "Versicolor" = "versicolor", "Virginica" = "virginica"),
        selected = "virginica",
        inline = FALSE
      )
    ),
    fluidRow_dsfr(
      actionButton_dsfr(
        inputId = "update_radiogroupbutton_label",
        label = "Update label"
      ),
      actionButton_dsfr(
        inputId = "update_radiogroupbutton_choices",
        label = "Update choices and inline"
      ),
      actionButton_dsfr(
        inputId = "update_radiogroupbutton_selected",
        label = "Update selected"
      )
    ),
    fluidRow_dsfr(
      verbatimTextOutput(outputId = "outputespece_radiogroupbutton")
    )
  )

  server <- function(input, output, session) {
    output$numericinputvalue <- renderText({
      paste("La valeur de l'input est", input$mynumericinput)
    })

    r <- reactiveValues()

    output$outputespece_radiogroupbutton <- renderText({
      paste("Esp\u00e8ce radiogroupbutton :", input$espece_radiogroupbutton)
    })


    observeEvent(input$update_radiogroupbutton_label, {
      updateRadioGroupButtons_dsfr(
        inputId = "espece_radiogroupbutton",
        label = paste0(sample(LETTERS, size = 12), collapse = ""),
        session = session
      )
    })

    observeEvent(input$update_radiogroupbutton_choices, {
      r$radiogroupubutton_choices <- sapply(1:3, function(x) paste0(sample(LETTERS, size = 3), collapse = ""))

      updateRadioGroupButtons_dsfr(
        inputId = "espece_radiogroupbutton",
        choices = r$radiogroupubutton_choices,
        inline = TRUE,
        session = session
      )
    })

    observeEvent(input$update_radiogroupbutton_selected, {
      updateRadioGroupButtons_dsfr(
        inputId = "espece_radiogroupbutton",
        selected = sample(r$radiogroupubutton_choices, size = 1),
        session = session
      )
    })
  }

  shinyApp(ui, server)
}
```
  
```{r tests-updateRadioGroupButtons_dsfr}
test_that("updateRadioGroupButtons_dsfr works", {
  expect_true(inherits(updateRadioGroupButtons_dsfr, "function"))
  sessA <- createModuleSession("modA")

  updateRadioGroupButtons_dsfr(
    session = sessA,
    inputId = "inradioGroupButtons",
    label = "Un nouveau label"
  )

  resultA <- sessA$lastInputMessage
  # inputId
  expect_equal("modA-inradioGroupButtons", resultA$id)
  # # label
  expect_equal("Un nouveau label", resultA$message$label)
  # # # HTML content
  # expect_equal(
  #   resultA$message$options,
  #   "<div class=\"fr-fieldset__content shiny-options-group fr-btns-group\" data-toggle=\"buttons\" style=\"display: contents;\">\n  <div class=\"fr-fieldset__element \">\n    <button class=\"fr-btn fr-btn--secondary\" id=\"button-modA-inradioGroupButtons-a\">\n      <input style=\"display:none;\" type=\"radio\" data-id=\"modA-inradioGroupButtons-a\" onclick=\"colorButton(buttonId = &#39;modA-inradioGroupButtons-a&#39;)\" autocomplete=\"off\" id=\"modA-inradioGroupButtons-a\" name=\"modA-inradioGroupButtons\" value=\"a\"/>\n      <label for=\"modA-inradioGroupButtons-a\">choice-a</label>\n    </button>\n  </div>\n</div>"
  # )
})
```
  
```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_composants/flat_radioGroupButtons.Rmd",
  vignette_name = NA,
  check = FALSE,
  overwrite = TRUE,
  open_vignette = FALSE
)
```
