---
title: "flat_new_one.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```



# dateRangeInput_dsfr_template
    
```{r function-dateRangeInput_dsfr_template}
#' dateRangeInput_dsfr_template
#'
#' @param inputId inputId
#' @param start character La date de début au format aaaa-mm-jj. Si NULL (valeur par défaut), la date utilisée est la date du jour.
#' @param end character La date de fin au format aaaa-mm-jj. Si NULL (valeur par défaut), la date utilisée est la date du jour.
#' @param label label
#' @param separator character Chaîne à afficher entre les zones de saisie de début et de fin de dates.
#'
#' @importFrom htmltools htmlTemplate
#' @importFrom purrr pmap
#' @return html
#' @noRd
dateRangeInput_dsfr_template <- function(
  inputId,
  label,
  start,
  end,
  separator
    ) {
  
  
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "dateRangeInput.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    start = start,
    end = end,
    separator = separator
  )
  
  }
```
  
  
```{r tests-dateRangeInput_dsfr_template}
test_that("dateRangeInput_dsfr_template works", {
  expect_true(inherits(dateRangeInput_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "dateRangeInput.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente


  purrr::walk(
    c(
      "inputId",
      "label",
      "start",
      "end",
      "separator"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      expect_true(
        any(grepl(pattern = with_moustache, htmlfile)),
        label = paste0("sans moustache '", param, "'")
      )
    }
  )


  test_html <- dateRangeInput_dsfr_template(
    inputId = "toto",
    label = "titi",
    start  = "2001-01-01",
    end    = "2010-12-31",
    separator = "to"
  )


  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
    inputId = "toto",
    label = "titi",
    start  = "2001-01-01",
    end    = "2010-12-31",
    separator = "to"
    ),
    function(param) {
      expect_true(
        any(grepl(pattern = param, test_html)),
        label = paste0("remplacement de '", param, "'")
      )
    }
  )

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "dateRangeInput_dsfr_template.Rda"
    )
  )

  #' @description Verifie le HTML créé
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(
    gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html)
  )


  # Si erreur au précedent test deux cas possibles :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioButtons_unique_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "dateRangeInput_dsfr_template.Rda"
  #                          )
  #         )
  #
})
```
  

# dateRangeInput_dsfr

```{r function-dateRangeInput_dsfr}
#' dateRangeInput_dsfr
#'
#' @param inputId inputId
#' @param label label
#' @param start character La date de début au format aaaa-mm-jj. Si NULL (valeur par défaut), la date utilisée est la date du jour.
#' @param end character La date de fin au format aaaa-mm-jj. Si NULL (valeur par défaut), la date utilisée est la date du jour.
#' @param separator character Chaîne à afficher entre les zones de saisie de début et de fin de dates.
#' 
#' @importFrom assertthat assert_that
#' @importFrom purrr map
#' @return html
#'
#' @export
#'
#' @examples
dateRangeInput_dsfr <- function(
  inputId,
  label,
  start = NULL,
  end = NULL,
  separator = "to"
    ) {
  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(separator))
  assertthat::assert_that(is.character(label))

  
  if (isTRUE(is.null(start))) {
    start <- Sys.Date()
  } else {
    assertthat::assert_that(is.character(start))
  }
  
  if (isTRUE(is.null(end))) {
    end <- Sys.Date()
  } else {
    assertthat::assert_that(is.character(end))
  }
  
  dateRangeInput_dsfr_template(
    inputId = inputId,
    label = label,
    start = start,
    end = end,
    separator = separator
  ) #%>%
     #parse_html()


}
```


```{r examples-dateRangeInput_dsfr}
## Only run examples in interactive R sessions
if (interactive()) {
  library(shiny)
  library(shinygouv)
  
  ui <- fluidPage_dsfr(
    header = header_dsfr(
      intitule = "Intitule",
      officiel = "Officiel",
      nom_site_service = "Nom du site / service",
      baseline = "baseline - precisions sur l organisation",
      class = "fr-m-1w"
    ),
    title = "Exemple",
    fluidRow_dsfr(
      # sans vecteur nommé
      dateRangeInput_dsfr(inputId = "daterange1",
                          label = "Date range:", start = "2001-01-01",separator = "à")
    )
  )
  server <- function(input, output, session) {

  observeEvent(input$daterange1, {
    print(input$daterange1)
  })  

  }
  

  shinyApp(ui, server)
}
```

```{r tests-dateRangeInput_dsfr}
test_that("dateRangeInput_dsfr works", {
  expect_true(inherits(dateRangeInput_dsfr, "function"))

  test_html <- dateRangeInput_dsfr(inputId = "daterange1",
                          label = "Date range:", start = "2001-01-01",
                          end = "2003-01-01", separator = "à")


  expect_error(
    dateRangeInput_dsfr(
      inputId = 123,
      label = "Date range:",
      start = "2001-01-01",
      end = "2003-01-01"
    )
  )

  expect_error(
    dateRangeInput_dsfr(
      inputId = "daterange1",
      label = 123,
      start = "2001-01-01",
      end = "2003-01-01"
    )
  )
  
  expect_error(
    dateRangeInput_dsfr(
      inputId = "daterange1",
      label = "Date range:",
      start = 123,
      end = "2003-01-01"
    )
  )

  expect_error(
    dateRangeInput_dsfr(
      inputId = "daterange1",
      label = "Date range:",
      end = 123,
      start = "2003-01-01"
    )
  )

  expect_error(
    dateRangeInput_dsfr(
      inputId = "daterange1",
      label = "Date range:",
      end = "2003-02-01",
      start = "2003-01-01",
      separator = 456
    )
  )
  
  expect_error(
        dateRangeInput_dsfr(
      inputId = "daterange1",
      label = "Date range:"
    ),
    regexp = NA
  )

  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "dateRangeInput_dsfr.Rda"
    )
  )
  #' @description Verifie le parametre selected dans le HTML
  expect_equal(
    gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html)
  )


  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioButtons_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

   # saveRDS(test_html,
   #         file = file.path("tests/testthat/snapshot",
   #                          "dateRangeInput_dsfr.Rda"
   #                          )
   #         )

})
```



#  updateDateRangeInput_dsfr


```{r function-updateCheckboxInput_dsfr}
#'  updateDateRangeInput_dsfr
#'
#' @param inputId inputId
#' @param label label
#' @param start character La date de début au format aaaa-mm-jj. Si NULL (valeur par défaut), la date utilisée est la date du jour.
#' @param end character La date de fin au format aaaa-mm-jj. Si NULL (valeur par défaut), la date utilisée est la date du jour.
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#' @importFrom shiny updateCheckboxInput
#' @return html
#'
#' @export
updateDateRangeInput_dsfr <- function(inputId,
                                      label = NULL,
                                      start = NULL,
                                      end = NULL,
                                      session = shiny::getDefaultReactiveDomain()) {
  
  
  ns <- session$ns

  if (!is.null(label)) {
    session$sendCustomMessage("updateDateRangeInputLabel",
                              list(inputId = ns(inputId),
                                   label = label))
  }
  
  if (!is.null(start)) {
    session$sendCustomMessage("updateDateRangeInputStart",
                              list(inputId = ns(inputId),
                                   start = start))
  }
  
  if (!is.null(end)) {
    session$sendCustomMessage("updateDateRangeInputEnd",
                              list(inputId = ns(inputId),
                                   end = end))
  }
}
```

```{r examples-updateDateRangeInput_dsfr}
## Only run examples in interactive R sessions
if (interactive()) {
  
  library(shiny)
  
  ui <- fluidPage_dsfr(
      dateRangeInput_dsfr(inputId = "daterange1",
                          label = "Date range:", start = "2001-01-01",separator = "à"),
    actionButton_dsfr("go", "Change label"),
    actionButton_dsfr("go2", "Change start"),
    actionButton_dsfr("go3", "Change end")
  )
  
  server <- function(input, output, session) {
    observeEvent(input$daterange1, {
      print(input$daterange1)
    })
    
    
    observeEvent(input$go, {
       updateDateRangeInput_dsfr(
        session = session,
        inputId = "daterange1",
        label = "new label"
      )
      
    })
    
    
    observeEvent(input$go2, {
       updateDateRangeInput_dsfr(
        session = session,
        inputId = "daterange1",
        start = "2000-01-01"
      )
      
    })
   
    observeEvent(input$go3, {
       updateDateRangeInput_dsfr(
        session = session,
        inputId = "daterange1",
        end = "2020-01-01"
      )
      
    }) 
  }
  shinyApp(ui, server)
}
```

  
```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_composants/flat_dateRangeInput.Rmd",
  vignette_name = NA,
  check = FALSE
)
```
