---
title: "flat_checkBoxInput.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

# checkboxInput_dsfr_template

```{r function-checkboxInput_unique_dsfr_template}
#' checkboxInput_unique_dsfr_template
#'
#' @param inputId id de l'input avec indexation
#' @param value TRUE (coché) ou FALSE (non coché)
#' @param label id de l'input sans indexation
#'
#' @importFrom htmltools htmlTemplate
#' @return html
checkboxInput_dsfr_template <- function(inputId, label, value = FALSE) {

  if (isTRUE(value)) {
    checked = 'checked = "checked"'
  } else {
    checked = NULL
  }

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkbox.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    checked = checked
  )
}
```

```{r tests-checkboxInput_dsfr_template}
test_that("checkboxInput_dsfr_template works", {
  expect_true(inherits(checkboxInput_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkbox.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  purrr::walk(
    c(
      "inputId",
      "label",
      "checked"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      expect_true(any(grepl(pattern = with_moustache, htmlfile)),
        label = paste0("sans moustache '", param, "'"))
    })


  test_html <- checkboxInput_dsfr_template(
    inputId = "test-1",
    label = "Some Value",
    value = TRUE
  )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs
  purrr::walk(
    c(
      inputId = "test-1",
      label = "Some Value",
      checked = "checked"
    ),
    function(param) {
      expect_true(any(grepl(pattern = param, test_html)),
        label = paste0("remplacement de '", param, "'"))
    })

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "checkboxInput_dsfr_template.Rda")
  )

  #' @description Verifie le HTML créé
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html))


  # Si erreur au précedent test deux cas possibles :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction checkboxInput_unique_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS
  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "checkboxInput_dsfr_template.Rda"
  #                          )
  #         )


})
```


# checkboxInput_dsfr

La case à cocher permet à l’utilisateur de sélectionner ou désélectionner une seule option. Elle est utilisée pour effectuer un choix binaire.

```{r function-checkboxInput_dsfr}
#' checkboxInput_dsfr
#'
#' La case à cocher permet à l’utilisateur de sélectionner ou désélectionner une seule option. Elle est utilisée pour effectuer un choix binaire.
#'
#' @param inputId id de l'input avec indexation
#' @param value TRUE (coché) ou FALSE (non coché)
#' @param label id de l'input sans indexation
#'
#' @return html
#'
#' @export
#'
#' @examples
checkboxInput_dsfr <- function(inputId,
                               label,
                               value = FALSE) {

  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.logical(value))

  checkboxInput_dsfr_template(inputId,
    label = label,
    value = value) %>%
    parse_html()
}
```

```{r examples-checkboxInput_dsfr}
checkboxInput_dsfr(
  inputId = 'test', label = 'test', value = FALSE)
checkboxInput_dsfr(
  inputId = 'test', label = 'test', value = TRUE
)
```


```{r tests-checkboxInput_dsfr}
test_that("checkboxInput_dsfr works", {
  test_html <- checkboxInput_dsfr(
    inputId = 'test', label = 'test', value = FALSE)

  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")


  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "checkboxInput_dsfr.Rda")
  )

  #' @description Verifie le HTML créé
  expect_equal(gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html))

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction checkboxInput_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS
  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "checkboxInput_dsfr.Rda"
  #                          )
  #         )

})
#
test_that("checkboxInput_dsfr", {
  test <- checkboxInput_dsfr(
    inputId = 'test', label = 'test', value = FALSE)

  #' @description tester si shiny.tag
  expect_s3_class(test, "shiny.tag")

  expect_error(
    checkboxInput_dsfr(inputId = "test", label = 'test', value = "char")
  )

  expect_error(
    checkboxInput_dsfr(inputId = 'test', label = 11, value = FALSE)
  )

  expect_error(
    checkboxInput_dsfr(inputId = 11, label = 'test', value = FALSE)
  )
})
```

# updateCheckboxInput_dsfr


```{r function-updateCheckboxInput_dsfr}
#' updateCheckboxInput_dsfr
#'
#' Change la valeur d'un checkboxInput
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param value TRUE (coché) ou FALSE (non coché)
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#'
#' @importFrom shiny updateCheckboxInput
#' @return html
#'
#' @export
updateCheckboxInput_dsfr <- function(inputId,
                                     label = NULL,
                                     value = NULL,
                                     session = shiny::getDefaultReactiveDomain()) {

  ns <- session$ns

  updateCheckboxInput(session = session,
    inputId = ns(inputId),
    label = label,
    value = value)

}
```

```{r examples-updateCheckboxInput_dsfr}
## Only run examples in interactive R sessions
if (interactive()) {
  ui <- fluidPage_dsfr(
    checkboxInput_dsfr(inputId = 'inCheckboxInput', label = 'test', value = FALSE),
    actionButton_dsfr("go", "Change")
  )
  server <- function(input, output, session) {

    observeEvent(input$go, {
      updateCheckboxInput_dsfr(
        session = session,
        inputId = "inCheckboxInput",
        label = "Un nouveau label",
        value = TRUE
      )
    })

    observeEvent(input$inCheckboxInput, {
      message(input$inCheckboxInput)
    })
  }
  shinyApp(ui, server)
}
```


```{r tests-updateCheckboxInput_dsfr}
test_that("updateCheckboxInput_dsfr works", {
  expect_true(inherits(updateCheckboxInput_dsfr, "function"))
  sessA <- createModuleSession("modA")
  updateCheckboxInput_dsfr(
    session = sessA,
    inputId = "inCheckboxInput",
    label = "Un nouveau label",
    value = TRUE
  )

  resultA <- sessA$lastInputMessage
  # inputId
  expect_equal("modA-inCheckboxInput", resultA$id)
  # label
  expect_equal("Un nouveau label", resultA$message$label)
  expect_equal(TRUE, resultA$message$value)
})
```

# checkboxGroupInput_unique_dsfr_template

```{r function-checkboxGroupInput_unique_dsfr_template}
#' checkboxGroupInput_unique_dsfr_template
#'
#' @param inputId id de l'input avec indexation
#' @param value TRUE (coché) ou FALSE (non coché)
#' @param label id de l'input sans indexation
#' @param checked Element coché (NULL par defaut)
#'
#' @importFrom htmltools htmlTemplate
#' @return html
checkboxGroupInput_unique_dsfr_template <- function(inputId, name, label, value, checked = NULL, inline) {

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkboxgroup_option.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    name = name,
    value = value,
    value_label = label,
    checked = checked,
    inline = inline
  )
}
```



```{r tests-checkboxGroupInput_unique_dsfr_template}
test_that("checkboxGroupInput_unique_dsfr_template works", {
  expect_true(inherits(checkboxGroupInput_unique_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkboxgroup_option.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  purrr::walk(
    c(
      "inputId",
      "name",
      "value",
      "value_label",
      "checked",
      "inline"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      expect_true(any(grepl(pattern = with_moustache, htmlfile)),
        label = paste0("sans moustache '", param, "'"))
    })


  test_html <- checkboxGroupInput_unique_dsfr_template(
    inputId = "test",
    name = "test-1",
    label = "Some Value",
    value = "value",
    checked = "checked",
    inline = "--inline"
  )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs
  purrr::walk(
    c(
      inputId = "test",
      name = "test-1",
      label = "Some Value",
      value = "value",
      checked = "checked",
      inline = "--inline"
    ),
    function(param) {
      expect_true(any(grepl(pattern = param, test_html)),
        label = paste0("remplacement de '", param, "'"))
    })

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "checkboxGroupInput_unique_dsfr_template.Rda")
  )

  #' @description Verifie le HTML créé
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html))


  # Si erreur au précedent test deux cas possibles :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction checkboxInput_unique_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS
  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "checkboxGroupInput_unique_dsfr_template.Rda"
  #                          )
  #         )




})
```



# checkboxGroupInput_dsfr_template

```{r function-checkboxGroupInput_dsfr_template}
#' checkboxGroupInput_dsfr_template
#'
#' @param inputId id de l'input
#' @param label label de l'input
#' @param choix choix Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param checked Element coché (NULL par defaut)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @importFrom htmltools htmlTemplate tagList
#' @importFrom purrr pmap map_chr
#' @return html
checkboxGroupInput_dsfr_template <- function(inputId, label, choix, checked = NULL, inline = FALSE) {


  if (isTRUE(inline)) {
    inline_value <- "fr-fieldset__element--inline"
    container_inline <- "shiny-input-container-inline"
  } else {
    inline_value <- ""
    container_inline <- ""
  }

  if (is.null(names(choix))) {
    nom_choix <- choix
  } else {
    nom_choix <- names(choix)
  }

  checked_logical <- choix %in% checked
  checked_value <- gsub(x = as.character(checked_logical), pattern = "FALSE", replacement = "")
  checked_value <- gsub(x = checked_value, pattern = "TRUE", replacement = "checked")

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkboxgroup.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    container_inline = container_inline,
    choice = pmap(list(.x = choix,
      .y = nom_choix,
      .z = checked_value,
      .nb = seq_along(choix),
      .inline = rep(inline_value, length(choix))
    ),
    function(.x, .y, .z, .nb, .inline) {
      checkboxGroupInput_unique_dsfr_template(
        inputId = inputId,
        name = paste0(inputId, "-", .nb),
        label = .y,
        value = .x,
        checked = .z,
        inline = .inline
      )
    }) %>%
      htmltools::tagList()
  )
}
```


```{r}
checkboxGroupInput_dsfr_template(inputId = "variable",
  label = "Variables to show:",
  choix = c("Cylinders" = "cyl",
    "Transmission" = "am",
    "Gears" = "gear"),
  checked = "gear")
```


```{r tests-checkboxGroupInput_dsfr_template}
test_that("checkboxGroupInput_dsfr_template works", {
  expect_true(inherits(checkboxGroupInput_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkboxgroup.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  purrr::walk(
    c(
      "inputId",
      "label",
      "choice",
      "container_inline"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      expect_true(any(grepl(pattern = with_moustache, htmlfile)),
        label = paste0("sans moustache '", param, "'"))
    })


  test_html <- checkboxGroupInput_dsfr_template(inputId = "variable",
    label = "Variables to show:",
    choix = c("Cylinders" = "cyl",
      "Transmission" = "am",
      "Gears" = "gear"),
    checked = "gear", inline = TRUE)

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs
  purrr::walk(
    c(
      inputId = "variable",
      label = "Variables to show:",
      choix = c("Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear"),
      checked = "gear",
      container_inline = "shiny-input-container-inline"
    ),
    function(param) {
      expect_true(any(grepl(pattern = param, test_html)),
        label = paste0("remplacement de '", param, "'"))
    })

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "checkboxGroupInput_dsfr_template.Rda")
  )

  #' @description Verifie le HTML créé
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html))


  # Si erreur au précedent test deux cas possibles :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction checkboxInput_unique_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS
  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "checkboxGroupInput_dsfr_template.Rda"
  #                          )
  #         )




})
```



# checkboxGroupInput_dsfr

```{r function-checkboxGroupInput_dsfr}
#' checkboxGroupInput_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Valeurs préselectionnées
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @return html
#'
#' @export
#'
#' @examples
checkboxGroupInput_dsfr <- function(inputId,
                                    label, choices = NULL, selected = NULL, inline = FALSE) {

  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.logical(inline))

  # if choices is null then choices_value and choice_names must be not empty with the same length
  # assertthat::assert_that(!is.null(choices) | (length(choice_values) > 0 & length(choice_values) == length(choice_names)))
  #
  checkboxGroupInput_dsfr_template(inputId,
    label = label,
    choix = choices,
    checked = selected,
    inline = inline) %>%
    parse_html()
}
```

```{r examples-checkboxGroupInput_dsfr}
if (interactive()) {

  library(shiny)

  ui <- fluidPage_dsfr(
    checkboxGroupInput_dsfr("checkboxes", "Variables to show:",
      c("Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear"), inline = TRUE)
  )

  server <- function(input, output, session) {
    observeEvent(input$checkboxes, {
      print(input$checkboxes)
    })
  }

  shinyApp(ui, server)
}
```

```{r tests-checkboxGroupInput_dsfr}
test_that("checkboxGroupInput_dsfr works", {
  test_html <- checkboxGroupInput_dsfr("variable", "Variables to show:",
    c("Cylinders" = "cyl",
      "Transmission" = "am",
      "Gears" = "gear"))

  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")


  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "checkboxGroupInput_dsfr.Rda")
  )
  #' @description Verifie le parametre selected dans le HTML
  expect_equal(gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html))


  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #                              assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #                              dans la fonction radioButtons_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "checkboxGroupInput_dsfr.Rda"
  #                          )
  #         )


  expect_error(
    checkboxGroupInput_dsfr(111, "Variables to show:",
      c("Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear")),
    regexp = "inputId is not a character vector")


  expect_error(
    checkboxGroupInput_dsfr("variable", 444,
      c("Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear")),
    regexp = "label is not a character vector")

  expect_error(
    checkboxGroupInput_dsfr("variable", "A label",
      c("Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear"),
      inline = "fake"),
    regexp = "is.logical\\(inline\\) is not TRUE")
})
```

# updateCheckboxGroupInput_dsfr


```{r function-updateCheckboxInput_dsfr}
#' updateCheckboxGroupInput_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Valeurs préselectionnées
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @importFrom shiny updateCheckboxInput
#' @return html
#'
#' @export
updateCheckboxGroupInput_dsfr <- function(inputId,
                                          label = NULL,
                                          choices = NULL,
                                          selected = NULL,
                                          inline = FALSE,
                                          session = shiny::getDefaultReactiveDomain()) {

  ns <- session$ns

  if (!is.null(selected)) {
    selected <- as.character(selected)
  }

  if (is.null(names(choices))) {
    nom_choix <- choices
  } else {
    nom_choix <- names(choices)
  }

  if (!is.null(choices)) {
    tag <- checkboxGroupInput_dsfr(
      inputId = ns(inputId),
      label = label,
      choices = choices,
      inline = inline,
      selected = selected
    ) %>%
      htmltools::tagQuery()

    choices <- tag$find(".shiny-options-group")$selectedTags()
    choices <- as.character(choices)
  }

  message <- utils::getFromNamespace("dropNulls", "shiny")(list(
    label = label,
    options = choices,
    value = selected
  ))

  session$sendInputMessage(ns(inputId), message)

}
```

```{r examples-updateCheckboxGroupInput_dsfr}
## Only run examples in interactive R sessions

if (interactive()) {

  library(shiny)

  ui <- fluidPage_dsfr(
    checkboxGroupInput_dsfr("variable", "Variables to show:",
      c("Cylinders" = "cyl",
        "Transmission" = "am",
        "Gears" = "gear"),
      inline = TRUE),
    checkboxGroupInput("ok", "ok", c("test")),
    actionButton_dsfr("go", "Change")
  )

  server <- function(input, output, session) {
    observeEvent(input$variable, {
      print(input$variable)
    })


    observeEvent(input$go, {
      updateCheckboxGroupInput_dsfr(
        session = session,
        inputId = "variable",
        label = paste0("test", rnorm(1)),
        choices = c("A" = "a", "B" = "b"),
        selected = "a",
        inline = FALSE
      )

      updateCheckboxGroupInput(
        session = session,
        inputId = "ok",
        label = paste0("test", rnorm(1))
      )
    })
  }
  shinyApp(ui, server)
}
```


```{r}
shiny:::updateCheckboxGroupInput

checkboxGroupInput("inCheckboxGroup2", "Input checkbox 2",
  c("Item A", "Item B", "Item C"), inline = TRUE)
```
```{r tests-updateCheckboxGroupInput_dsfr}
test_that("updateCheckboxGroupInput_dsfr works", {
  expect_true(inherits(updateCheckboxGroupInput_dsfr, "function"))

  sessA <- createModuleSession("modA")

  updateCheckboxGroupInput_dsfr(
    session = sessA,
    inputId = "variable",
    label = "Un nouveau label",
    choices = c("choice-a" = "a", "B" = "b"),
    selected = "a"
  )


  resultA <- sessA$lastInputMessage
  # inputId
  expect_equal("modA-variable", resultA$id)
  # label
  expect_equal("Un nouveau label", resultA$message$label)
  # HTML content
  # expect_true(grepl('id\\s*=\\s*\"modA-variable-1\"', resultA$message$options))
  # expect_true(grepl('value\\s*=\\s*"a"', resultA$message$options))
  # expect_true(grepl('choice-a', resultA$message$options))
  # expect_true(grepl('checked', resultA$message$options))
})
```


```{r development-inflate, eval=FALSE}
spec_infalte <- function() {
  nom <- "checkboxInput dsfr"
  fusen::inflate(
    flat_file = "dev/flat_composants/flat_checkBoxInput.Rmd", check = FALSE,
    vignette_name = NA)

  nom_c <- gsub(x = tolower(nom), "\\s", "-")
  nom_file <- paste0(nom_c, ".Rmd")
  file.copy(
    file.path("vignettes", nom_file),
    file.path("dev", "documentation", nom_file)
  )

  unlink(file.path("vignettes", nom_file))
}
spec_infalte()
```
