---
title: "fileInput"
output: html_document
editor_options: 
  chunk_output_type: console
---


```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

# fileInput_dsfr_template
    
```{r function-fileInput_dsfr_template}
#' template pour fileInput_dsfr
#'
#' @param inputId id de l'input
#' @param label etiquette du bouton d'import, par exemple "choisir fichier"
#' @param message eventuelles indications complementaires, par exemple "seuls les fichiers csv sont acceptes"
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
fileInput_dsfr_template <- function(
                inputId,
                label,
                message
) {

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "fileInput.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    message = message
  )
}
```
  
  
```{r tests-fileInput_dsfr_template}
test_that("fileInput_dsfr_template works", {
  expect_true(inherits(fileInput_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "fileInput.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  purrr::walk(
    c(
      "inputId",
      "label",
      "message"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      expect_true(any(grepl(pattern = with_moustache, htmlfile)),
        label = paste0("sans moustache '", param, "'"))
    })


  test_html <- fileInput_dsfr_template(
                inputId = "1245",
                label = "étiquette",
                message = "csv seulement"
                )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
                inputId = "1245",
                label = "étiquette",
                message = "csv seulement"
    ),
    function(param) {
      expect_true(any(grepl(pattern = param, test_html)),
        label = paste0("remplacement de '", param, "'"))
    })

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "fileInput_dsfr_template.Rda")
  )

  #' @description Verifie le HTML créé
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html))

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #  dans la fonction fileInput_dsfr_template puis lancer le saveRDS, relancer le test et recommenter le saveRDS
# 
#   saveRDS(test_html,
#           file = file.path("tests/testthat/snapshot",
#                            "fileInput_dsfr_template.Rda"
#                            )
#           )


})
```
  

# fileInput_dsfr

```{r function-fileInput_dsfr}
#' fileInput_dsfr
#'
#'
#' @param inputId id de l'input
#' @param label etiquette du bouton d'import, par exemple "choisir fichier"
#' @param message eventuelles indications complementaires, par exemple "fichier images de moins de 2 Mo"
#'
#' @return html
#' @importFrom assertthat assert_that
#' @export
#'
#' @examples
fileInput_dsfr <- function(
                inputId,
                label,
                message
                ) {

  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.character(message))

  fileInput_dsfr_template(
    inputId = inputId,
    label = label,
    message = message
  ) %>%
    parse_html()

}
```

```{r examples-fileInput_dsfr}

if (interactive()) {
  ui <- fluidPage_dsfr(
    fluidRow_dsfr(
      column_dsfr(width = 4, 
        fileInput_dsfr(inputId = "file1", label = "Importez vos données", message = "seul le format csv est pris en charge"),
        br(),
        checkboxInput_dsfr(inputId = "header", label = "Utiliser les en-tetes du fichier")
      ),
      column_dsfr(width = 8,
        tableOutput_dsfr("contenu")
      )
    )
  )
  
  server <- function(input, output) {
    output$contenu <- renderTable({
      file <- input$file1
      ext <- tools::file_ext(file$datapath)
      
      req(file)
      validate(need(ext == "csv", "Veuillez choisir un fichier csv svp"))
      
      read.csv2(file$datapath, header = input$header, nrows = 12)
    })
  }
  
  shinyApp(ui, server)
}


```

```{r tests-fileInput_dsfr}
test_that("fileInput_dsfr works", {
  test_html <- fileInput_dsfr(
    inputId = "file1", 
    label = "Importer vos données", 
    message = "seul le format csv est pris en charge"
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "fileInput_dsfr.Rda")
  )

  #' @description Verifer que le HTML est correct en sortie
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
    gsub("\\s|\\n", "", snapshot_html))

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #  dans la fonction fileInput_dsfr puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "fileInput_dsfr.Rda"
  #                          )
  #         )


  # Ajouter des tests pour controler le type des parametres d'entree
  # Cela verifie que les 'assertthat' fonctionnent correctement


})
```

# update_fileInput_dsfr

Pour les fonctions de type `update_*`, voir l'exemple de "flat_radioButtons.Rmd"


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly

fusen::inflate(flat_file = "dev/flat_composants/flat_fileInput.Rmd",
  vignette_name = NA)
```

