---
title: "flat_new_one.Rmd empty"
output: html_document
editor_options:
  chunk_output_type: console
---


```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = TRUE)
```

Vous pouvez ajouter le header officiel dans votre application avec `header_dsfr()`. Par exemple avec un `fluidPage_dsfr()` :

```{r, eval=FALSE}
fluidPage_dsfr(
  header = header_dsfr(
    intitule = "Intitule",
    officiel = "Officiel",
    nom_site_service = "Nom du site / service",
    baseline = "baseline - precisions sur l organisation",
    class = "fr-m-1w"
  ),
  title = "Exemple shiny dsfr",
  h1("Exemple d'utilisation de {shinygouv}"),
)
```


# header_dsfr_template

```{r function-header_dsfr_template}
#' header_dsfr_template
#' @param intitule la partie "intitule" du bloc marque
#' @param officiel la partie "officiel" du bloc marque
#' @param url l url de redirection
#' @param titre le texte de description de l url
#' @param nom_site_service le nom du site ou du service - optionnel
#' @param baseline le texte sous le nom de site/service - optionnel
#' @param class un classe a ajouter si necessaire (".fr-m-1w" pour #TODO) - optionnel
#' @importFrom htmltools htmlTemplate
#' @return html
header_dsfr_template <- function(
 intitule, officiel, url, titre, nom_site_service, baseline, class
  ){

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "entete.html",
      package = "shinygouv"
    ),
    class = class,
    intitule = intitule,
    officiel = officiel,
    url = url,
    titre = titre,
    nom_site_service = nom_site_service,
    baseline = baseline
    )
}

```


```{r tests-header_dsfr_template}
test_that("header_dsfr_template works", {
  expect_true(inherits(header_dsfr_template, "function"))

  htmlfile <- readLines(
    system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "entete.html",
      package = "shinygouv"
    )
  )

  #' @description Comparer les parametres par rapport a ceux de la version precedente

  purrr::walk(
    c(
      "class",
      "intitule",
      "officiel",
      "url",
      "titre",
      "nom_site_service",
      "baseline"
    ),
    function(param) {
      with_moustache <- paste0("\\{\\{", param, "\\}\\}")
      expect_true(
        any(grepl(pattern = with_moustache, htmlfile)),
        label = paste0("sans moustache '", param, "'")
      )
    }
  )


  test_html <- header_dsfr_template(
    class = "class",
    intitule = "Prefet de",
    officiel = "Bretagne",
    url = "https://www.prefectures-regions.gouv.fr/bretagne",
    titre = "Accueil - Préfecture de Bretagne",
    nom_site_service = "DREAL Bretagne",
    baseline = "description"
  )

  #' @description tester si tous les params sont remplaces
  expect_false(grepl(pattern = "\\{\\{", test_html))


  #' @description Verifie que les parametres ont bien ete remplace par leurs valeurs

  purrr::walk(
    c(
      class = "class",
      intitule = "Prefet de",
      officiel = "Bretagne",
      url = "https://www.prefectures-regions.gouv.fr/bretagne",
      titre = "Accueil - Préfecture de Bretagne",
      nom_site_service = "DREAL Bretagne",
      baseline = "description"
    ),
    function(param) {
      expect_true(
        any(grepl(pattern = param, test_html)),
        label = paste0("remplacement de '", param, "'")
      )
    }
  )
})
```


# header_dsfr

```{r function-header_dsfr}
#' header_dsfr
#'
#' @param intitule la partie "intitule" du bloc marque
#' @param officiel la partie "officiel" du bloc marque
#' @param url l url de redirection - optionnel
#' @param titre le texte de description de l url - optionnel
#' @param nom_site_service le nom du site ou du service - optionnel
#' @param baseline le texte sous le nom de site/service - optionnel
#' @param class un classe a ajouter si necessaire ("fr-m-1w" correspond a une margin de 1w sur tous les cotés) - optionnel, par defaut "fr-container" (centré) (voir le Systeme de design de l'Etat "fondamentaux-techniques/espacements")
#' @return html
#' @export
#'
#' @examples
header_dsfr <- function(
  intitule,
  officiel,
  url = "/",
  titre = NULL,
  nom_site_service = NULL,
  baseline = NULL,
  class = "fr-container"
) {
  # check les params
  assertthat::assert_that(is.character(intitule))
  assertthat::assert_that(is.character(officiel))
  # TODO verifier que l url est valide

  res <- header_dsfr_template(
    class = class,
    intitule = intitule,
    officiel = officiel,
    url = url,
    titre = titre,
    nom_site_service = nom_site_service,
    baseline = baseline
  ) %>%
    parse_html()
  class(res) <- c("header_dsfr", class(res))
  res
}
```

```{r examples-header_dsfr}
 header_dsfr(
     intitule = "Prefet de",
     officiel = "Bretagne",
  )
```

```{r tests-header_dsfr}
test_that("header_dsfr works", {
  test_html <- header_dsfr(
     intitule = "Prefet de",
     officiel = "Bretagne",
  )
  #' @description tester si shiny.tag
  expect_s3_class(test_html, "shiny.tag")

  ## lecture snapshot
  snapshot_html <- readRDS(
    file = file.path(
      "snapshot", # pour passer les tests en production (apres le inflate),
      # "tests/testthat/snapshot", # pour passer les tests en developpement (avant le inflate),
      "header_dsfr.Rda")
  )

  #' @description Verifer que le HTML est correct en sortie
  # Retire tous les espaces et saut de ligne pour la comparaison
  # Pour eviter les problèmes inter-OS
  expect_equal(gsub("\\s|\\n", "", test_html),
               gsub("\\s|\\n", "", snapshot_html))

  # Si erreur au précedent test deux cas possible :
  #
  # - nouveau composant: Lancer le saveRDS, relancer le test et recommenter le saveRDS
  #
  # - composant a mettre a jour: si le test ne passe plus avant de changer le snapshot,
  #  assurez vous d'avoir bien pris en compte la nouvelle personnalisation
  #  dans la fonction header_dsfr puis lancer le saveRDS, relancer le test et recommenter le saveRDS

  # saveRDS(test_html,
  #         file = file.path("tests/testthat/snapshot",
  #                          "header_dsfr.Rda"
  #                          )
  #         )

})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly

spec_inflate <- function(){
  nom <- "header_dsfr"
  fusen::inflate(
    flat_file = "dev/flat_composants/flat_header.Rmd",
    vignette_name = nom, open_vignette = FALSE)

  nom_c <- gsub(x = tolower(nom), "\\s", "-")
  nom_file <- paste0(nom_c, ".Rmd")
  file.copy(
    file.path("vignettes", nom_file),
    file.path("dev","documentation", nom_file)
    )

  unlink(file.path("vignettes", nom_file))
}
spec_inflate()
fusen::inflate(
  flat_file = "dev/flat_composants/flat_header.Rmd",
  vignette_name = NA,
  open_vignette = FALSE,
  check = FALSE
)
```

