---
title: "flat_tools.Rmd empty"
output: html_document
editor_options:
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
library(purrr)
library(XML)
library(stringr)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# parse_to_xml

```{r function-parse_to_xml}
#' Traduit du code html de htmltools pour du code xml
#'
#' @param html_code resultat de la fonction htmlTemplate
#' @importFrom XML htmlParse getNodeSet
#'
parse_to_xml <- function(html_code, zone = "/html/body/*") {
  if (inherits(html_code, "XMLInternalElementNode")) {
    stop("Use this function with character or shiny.tag.list")
  }

  if (!is.character(html_code)) {
    html_code <- as.character(html_code)
  }
  html_code %>%
    XML::htmlParse(encoding = "UTF-8") %>%
    XML::getNodeSet(zone) %>%
    getElement(1)
}
```


```{r tests-parse_to_xml}
test_that("parse_to_xml works", {
  expect_true(inherits(parse_to_xml, "function"))
  html_code <- '<button id="test" type="button" class="btn btn-default action-button">test</button>'


  test <- parse_to_xml(html_code)

  #' @description tester la classe du resultat de la fonction sur un caractere
  expect_s3_class(test, "XMLInternalElementNode")

  #' @description tester l'erreur si le code est déjà du XML
  expect_error(parse_to_xml(test))

  test2 <- parse_to_xml(
    htmltools::tagList(
      tags$div(id = "ok", name = "jean", "pierre")
    )
  )

  #' @description tester la classe du resultat de la fonction sur un shiny.tag
  expect_s3_class(test2, "XMLInternalElementNode")

})
```


# render_node

```{r function-render_node}
#' render_node
#'
#' @param node node qui provient de parse_to_xml
#' @param indent ajout de l'indentation
#' @param prefix si TRUE alors le resultat sera prefixe par tags
#'
#' @importFrom XML xmlName xmlValue xmlChildren
#' @importFrom stringr str_pad
#' @importFrom purrr partial
#'
render_node <- function(node, indent = 0, prefix = FALSE) {
  if (xmlName(node) == "text") {
    txt <- xmlValue(node)
    if (nchar(trimws(txt)) > 0) {
      paste0("\"", trimws(txt), "\"")
    }
  } else {
    tagName <- if (prefix) {
      paste0("tags$", xmlName(node))
    } else {
      xmlName(node)
    }

    my_render <- partial(render_node, indent = newIndent,
      prefix = prefix)
    newIndent <- indent + length(tagName) + 1
    xmlChildren(node) %>%
      Keep(my_render, .) %>%
      append(make_attrs(node), .) %>%
      paste(collapse = str_pad(",\n", width = newIndent,
        side = c("right"))) %>%
      trimws(which = c("left")) %>%
      paste0(tagName, "(", ., ")")
  }
}

#' @noRd
#' @importFrom XML xmlAttrs
#' @importFrom stringr str_detect
make_attrs <- function(node) {
  attrs <- xmlAttrs(node)
  names(attrs) %>% Map(function(name) {
    val <- attrs[[name]]
    if (str_detect(string = name, pattern = "-") || str_detect(string = name,
      pattern = "for")) {
      name <- paste0("`", name, "`")
    }
    paste0(name, " = ", if (val == "") {"NA"} else { paste0("\"", val, "\"")})
  }, .)
}

#' @noRd
Keep <- function(fun, xs) {
  Map(fun, xs) %>% Filter(Negate(is.null), .)
}
```


```{r tests-render_node}
test_that("render_node works", {
  expect_true(inherits(render_node, "function"))
  html_code <- '<button id="test" type="button" class="btn btn-default action-button">test</button>'
  test <- parse_to_xml(html_code)


  result <- render_node(test, prefix = TRUE)

  #' @description tester le resultat de render_node
  expect_type(result, "character")
})
```


# parse_html

```{r function-parse_html}
#' Traduit du html en resultat shiny
#'
#' @param html_code resultat d'une fonction htmlTemplate ou une chaine de caractere
#' @param zone zone a garder pour parser
#'
#' @return shiny.tag
#' @export
#'
#' @examples
parse_html <- function(html_code, zone = "/html/body/*") {

  xml <- parse_to_xml(html_code, zone) %>% render_node(prefix = TRUE)

  eval(parse(text = xml))
}
```

```{r examples-parse_html}
html_code <- '<button id="test" type="button" class="btn btn-default action-button">test</button>'
parse_html(html_code)
```

```{r tests-parse_html}
test_that("tester parse_html", {
  html_code <- '<button id="test" type="button" class="btn btn-default action-button">test</button>'
  result <- parse_html(html_code)

  #' @description tester si la fonction renvoie bien un shiny.tag
  expect_s3_class(result, "shiny.tag")

  #' @description tester si on peut manipuler les attributs
  classes <- htmltools::tagGetAttribute(result, "class")
  expect_true(length(classes) != 0)
})
```


```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(flat_file = "dev/tools/flat_tools.Rmd", vignette_name = NA, check = FALSE, overwrite = TRUE)
```

