# WARNING - Generated by {fusen} from dev/flat_composants/flat_actionButton.Rmd: do not edit by hand

#' actionButton_dsfr_template
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param class des classes a ajouter si necessaire
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
actionButton_dsfr_template <- function(
    inputId,
    label,
    class
){

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "bouton.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    class = class
  )
}

