# WARNING - Generated by {fusen} from dev/flat_composants/flat_actionButton.Rmd: do not edit by hand

#' actionButton_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param class des classes a ajouter si necessaire
#'
#' @return html
#'
#' @export
#'
#' @examples
#' if (interactive()) {
#'   library(shiny)
#'   library(shinygouv)
#'
#'   ui <- fluidPage_dsfr(
#'     header = header_dsfr(
#'       intitule = "Intitule",
#'       officiel = "Officiel",
#'       nom_site_service = "Nom du site / service",
#'       baseline = "baseline - precisions sur l organisation",
#'       class = "fr-m-1w"
#'     ),
#'     title = "Exemple",
#'     fluidRow_dsfr(
#'       actionButton_dsfr(
#'         inputId = "test",
#'         label = "Cliquez moi",
#'         class = "fr-btn--icon-left fr-icon-checkbox-circle-line"
#'       ),
#'       verbatimTextOutput(outputId = "nbclic")
#'     )
#'   )
#'   server <- function(input, output, session) {
#'     output$nbclic <- renderText({
#'       paste("Vous avez cliqu\u00e9", input$test, "fois sur le bouton")
#'     })
#'   }
#'
#'   shinyApp(ui, server)
#' }
actionButton_dsfr <- function(
  inputId,
  label,
  class = NULL
    ) {
  actionButton_dsfr_template(
    inputId,
    label,
    class
  ) %>%
    parse_html()
}
