# WARNING - Generated by {fusen} from /dev/flat_composants/flat_actionButton.Rmd: do not edit by hand

#' actionButton_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param class des classes a ajouter si necessaire
#'
#' @return html
#'
#' @export
#'
#' @examples
#' actionButton_dsfr(
#'   inputId = "test",
#'   label = "test",
#'   class = "fr-btn--icon-left fr-icon-checkbox-circle-line"
#' )
actionButton_dsfr <- function(
  inputId,
  label,
  class = NULL
) {
  actionButton_dsfr_template(
    inputId,
    label,
    class
  ) %>%
    parse_html()
}
