# WARNING - Generated by {fusen} from dev/flat_composants/flat_withSpinner.Rmd: do not edit by hand

#' spinner-specific html code
#'
#' @param spinner_id id du spinner
#'
#' @importFrom htmltools HTML
#' @return an html code
#' @export
#' @examples addWithSpinner()
#' addWithSpinner()
addWithSpinner <- function(
    spinner_id = "lds-ring"
    ) {
HTML('<div class="lds-ring" id = "lds-ring" style="display:none"><div></div><div></div><div></div><div></div></div>')
}
