# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkboxInput.Rmd: do not edit by hand

#' checkboxInput_dsfr_template
#' 
#' @param label label du groupe de boite à cocher
#' @param choices les choix possibles
#' @param selected les cases éventuellement déjà cochées
#' @param inline pour aligner les cases à cocher horizontalement (FALSE par défaut)
#' @param inputId id de l'input avec indexation
#' @param choice_names les choix possibles (label)
#' @param choice_values les choix possible (valeur)
#'
#' @importFrom htmltools htmlTemplate tagList
#' @importFrom purrr pmap
#' @return html
#' @noRd
checkboxInput_dsfr_template <- function(inputId, 
                                        label, 
                                        choices = NULL, 
                                        selected = NULL, 
                                        inline = FALSE,
                                        choice_names = NULL,
                                        choice_values = NULL){
  
  if (isTRUE(inline)) {
    class_inline <- "fr-fieldset--inline"
  } else {
    class_inline <- NULL
  }
  
  # if choices is not null, we ignore choice_names and choice_values
  if (!is.null(choices)) {
    choice_values <- choices
    if (is.null(names(choices))) {
      choice_names <- choices
    } else {
      choice_names <- names(choices)
    }
  }

  htmltools::htmlTemplate(
    filename = system.file(
      "v1.7.2",
      "composant", 
      "checkbox_group.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    class_inline = class_inline,
    label = label,
    choice = purrr::pmap(list(.x = choice_values, 
                              .y = choice_names, 
                              .nb = seq_along(choice_values)),
                         function(.x, .y, .nb) { 
                           checkboxInput_unique_dsfr_template(
                           inputId = paste0(inputId,"-", .nb),
                           name = inputId,
                           choice_value = .x,
                           choice_name = .y,
                           value = .x %in% selected 
                           )
                         }
                         ) %>% 
      htmltools::tagList()
  )
}

