# WARNING - Generated by {fusen} from dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

#' checkboxInput_dsfr
#'
#' La case à cocher permet à l’utilisateur de sélectionner ou désélectionner une seule option. Elle est utilisée pour effectuer un choix binaire.
#'
#' @param inputId id de l'input avec indexation
#' @param value TRUE (coché) ou FALSE (non coché)
#' @param label id de l'input sans indexation
#'
#' @return html
#'
#' @export
#'
#' @examples
#' checkboxInput_dsfr(
#'   inputId = 'test', label = 'test', value = FALSE)
#' checkboxInput_dsfr(
#'   inputId = 'test', label = 'test', value = TRUE
#' )
checkboxInput_dsfr <- function(inputId,
                               label,
                               value = FALSE) {

  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.logical(value))

  checkboxInput_dsfr_template(
    inputId,
    label = label,
    value = value) %>%
    parse_html()
}
