# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkboxInput.Rmd: do not edit by hand

#' checkboxInput_dsfr
#' 
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Valeurs préselectionnées
#' @param choice_names Liste de labels (ignoré si choices est défini)
#' @param choice_values Liste des valeurs (ignoré si choices est défini)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement). 
#'
#' @return html
#' 
#' @export
#'
checkboxInput_dsfr <- function(inputId, 
                                        label, 
                                        choices = NULL, 
                                        selected = NULL, 
                                        inline = FALSE,
                                        choice_names = NULL,
                                        choice_values = NULL) {
  
  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.logical(inline))
  
  # if choices is null then choices_value and choice_names must be not empty with the same length
  assertthat::assert_that(!is.null(choices) | (length(choice_values) > 0 & length(choice_values) == length(choice_names)))
  
  checkboxInput_dsfr_template(inputId, 
                                label, 
                                choices, 
                                selected, 
                                inline,
                                choice_names,
                                choice_values) %>%
      parse_html()

}
