# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

#' checkboxGroupInput_unique_dsfr_template
#'
#' @param inputId id de l'input avec indexation
#' @param value TRUE (coché) ou FALSE (non coché)
#' @param label id de l'input sans indexation
#' @param checked Element coché (NULL par defaut)
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
checkboxGroupInput_unique_dsfr_template <- function(inputId, name, label, value, checked = NULL) {
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkboxgroup_option.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    name = name,
    value = value,
    value_label = label,
    checked = checked
  )
}
