# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

#' checkboxGroupInput_dsfr_template
#'
#' @param inputId id de l'input
#' @param label label de l'input
#' @param choix choix Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param checked Element coché (NULL par defaut)
#'
#' @importFrom htmltools htmlTemplate tagList
#' @importFrom purrr pmap map_chr
#' @return html
#' @noRd
checkboxGroupInput_dsfr_template <- function(inputId, label, choix, checked = NULL) {
  if (is.null(names(choix))) {
    nom_choix <- choix
  } else {
    nom_choix <- names(choix)
  }

  checked_logical <- choix %in% checked
  checked_value <- gsub(x = as.character(checked_logical), pattern = "FALSE", replacement = "")
  checked_value <- gsub(x = checked_value, pattern = "TRUE", replacement = "checked")

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkboxgroup.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    choice = pmap(
      list(
        .x = choix,
        .y = nom_choix,
        .z = checked_value,
        .nb = seq_along(choix)
      ),
      function(.x, .y, .z, .nb) {
        checkboxGroupInput_unique_dsfr_template(
          inputId = inputId,
          name = paste0(inputId, "-", .nb),
          label = .y,
          value = .x,
          checked = .z
        )
      }
    ) %>%
      htmltools::tagList()
  )
}
