# WARNING - Generated by {fusen} from dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

#' checkboxGroupInput_dsfr_template
#'
#' @param inputId id de l'input
#' @param label label de l'input
#' @param choix choix Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param checked Element coché (NULL par defaut)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @importFrom htmltools htmlTemplate tagList
#' @importFrom purrr pmap map_chr
#' @return html
#' @noRd
checkboxGroupInput_dsfr_template <- function(inputId, label, choix, checked = NULL, inline = FALSE) {


  if (isTRUE(inline)) {
    inline_value <- "fr-fieldset__element--inline"
    container_inline <- "shiny-input-container-inline"
  } else {
    inline_value <- ""
    container_inline <- ""
  }

  if (is.null(names(choix))) {
    nom_choix <- choix
  } else {
    nom_choix <- names(choix)
  }

  checked_logical <- choix %in% checked
  checked_value <- gsub(x = as.character(checked_logical), pattern = "FALSE", replacement = "")
  checked_value <- gsub(x = checked_value, pattern = "TRUE", replacement = "checked")

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkboxgroup.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    container_inline = container_inline,
    choice = pmap(list(.x = choix,
      .y = nom_choix,
      .z = checked_value,
      .nb = seq_along(choix),
      .inline = rep(inline_value, length(choix))
    ),
    function(.x, .y, .z, .nb, .inline) {
      checkboxGroupInput_unique_dsfr_template(
        inputId = inputId,
        name = paste0(inputId, "-", .nb),
        label = .y,
        value = .x,
        checked = .z,
        inline = .inline
      )
    }) %>%
      htmltools::tagList()
  )
}
