# WARNING - Generated by {fusen} from dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

#' checkboxInput_unique_dsfr_template
#'
#' @param inputId id de l'input avec indexation
#' @param value TRUE (coché) ou FALSE (non coché)
#' @param label id de l'input sans indexation
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
checkboxInput_dsfr_template <- function(inputId, label, value = FALSE) {

  if (isTRUE(value)) {
    checked = 'checked = "checked"'
  } else {
    checked = NULL
  }

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "checkbox.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    checked = checked
  )
}
