# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkboxInput.Rmd: do not edit by hand

#' checkboxInput_unique_dsfr_template
#' 
#' @param inputId id de l'input avec indexation
#' @param choice_value choix
#' @param choice_name label
#' @param value TRUE (coché) ou FALSE (non coché)
#' @param name id de l'input sans indexation
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
checkboxInput_unique_dsfr_template <- function(inputId, name, choice_value, choice_name = choice_value, value = FALSE){
  

  htmltools::htmlTemplate(
    filename = system.file(
      "v1.7.2",
      "composant", 
      "checkbox.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    name = name,
    choice_name = choice_name,
    choice_value = choice_value,
    checked = if (isTRUE(value)) 'checked=""' else NULL
    )
}

