# WARNING - Generated by {fusen} from dev/flat_composants/flat_fluidpage.Rmd: do not edit by hand

#' column_dsfr
#'
#'
#' @param width width par défaut est NULL, cela signifie que la taille de la colonne depend des autres colonnes. Vous pouvez aussi utiliser 0
#' @param ... differents tag pour construire la page
#' @param extra_class ajout de class pour la column_dsfr (voir la page officiel du CSS)
#'
#' @return shiny.tag.list
#'
#' @importFrom htmltools tagList
#'
#' @export
#' @examples
#'
#' if(interactive()){
#' shiny::shinyApp(
#'   ui = fluidPage_dsfr(
#'     title = "exemple",
#'     fluidRow_dsfr(
#'       column_dsfr(0, "test"),
#'       column_dsfr(0, "test"),
#'       column_dsfr(0, "test"),
#'       column_dsfr(0, "test")
#'     )
#'   ),
#'   server = function(input, output){}
#'   )
#' }
#'
column_dsfr <- function(
  width = NULL,
  ...,
  extra_class = NULL
    ) {
  if (is.null(width)) {
    add_width <- ""
  } else {
    if (width != 0) {
      add_width <- paste0("-", width)
    } else {
      add_width <- ""
    }
  }

  class <- paste0("fr-col", add_width)

  layout_dsfr_template(
    html = tagList(
      ...
    ),
    class = class,
    other_class = extra_class
  )
}
