# WARNING - Generated by {fusen} from /dev/flat_convert_to_dsfr.Rmd: do not edit by hand

#' convert_to_dsfr
#'
#' permet de convertir une application shiny en une application shiny suivant le DSFR
#'
#' @param path le chemin du dossier sur lequel faire la conversion, par defaut "R/"
#' @param version le numero de version du dsfr a utiliser, par exemple "1.7.2"
#' @importFrom purrr map
#' @importFrom readr read_csv2
#' @importFrom glue glue
#' @importFrom stringr  str_which
#' @importFrom dplyr filter
#' @return des fichiers modifies
#'
#' @export
#' @examples
#' mydir <- tempfile(pattern = "app")
#' dir.create(mydir)
#' golem::create_golem(
#'   mydir,
#'   overwrite = TRUE,
#'   open = FALSE
#' )
#' convert_to_dsfr(path = file.path(mydir, "R"), version = "1.7.2")
convert_to_dsfr <- function(path = "R/", version) {
  chem <- glue::glue("v{version}/table_correspondance_shiny_dsfr.csv")

  if (is.null(version)) {
    stop("Merci de preciser le numero de version a utiliser")
  }

  if (!file.exists(
    system.file(chem, package = "shinygouv")
  )) {
    stop(glue::glue("Le dossier 'v{version}' n existe pas"))
  }

  chemin_tab_corresp <- system.file(chem, package = "shinygouv")

  if (chemin_tab_corresp == "") {
    stop(glue::glue("Le fichier 'v{version}/table_correspondance_shiny_dsfr.csv' n existe pas"))
  }

  tab_corresp <- chemin_tab_corresp %>%
    readr::read_csv2() %>%
    filter(!is.na(composant_shiny))

  # recuperation de la table de correspondance
  fic <- list.files(path = path, full.names = TRUE)

  res <- purrr::map(
    .x = fic,
    ~ convert_file_to_dsfr(
      .x,
      tab_corresp
    )
  )

  # ajout de la dependance a app_ui.R si il existe
  if (file.exists(file.path(path, "app_ui.R"))) {
    file_read <- readLines(file.path(path, "app_ui.R"))
    local <- stringr::str_which(string = file_read, pattern = "@import shiny")
    for (i in local) {
      file_read <- append(file_read, "#' @import shinygouv", after = i)
    }
    message("la dependance a shinygouv a ete ajoute dans app_ui.R")
    writeLines(file_read, con = file.path(path, "app_ui.R"))
  }

  return("Conversion terminee")
}
