# WARNING - Generated by {fusen} from /dev/flat_composants/flat_dateRangeInput.Rmd: do not edit by hand

#' dateRangeInput_dsfr_template
#'
#' @param inputId inputId
#' @param start character La date de début au format aaaa-mm-jj. Si NULL (valeur par défaut), la date utilisée est la date du jour.
#' @param end character La date de fin au format aaaa-mm-jj. Si NULL (valeur par défaut), la date utilisée est la date du jour.
#' @param label label
#'
#' @importFrom htmltools htmlTemplate
#' @importFrom purrr pmap
#' @return html
#' @noRd
dateRangeInput_dsfr_template <- function(
  inputId,
  label,
  start,
  end
    ) {
  
  
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "dateRangeInput.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    start = start,
    end = end
  )
  
  }
