# WARNING - Generated by {fusen} from /dev/flat_composants/flat_fileInput.Rmd: do not edit by hand

#' template pour fileInput_dsfr
#'
#' @param inputId id de l'input
#' @param label etiquette du bouton d'import, par exemple "choisir fichier"
#' @param message eventuelles indications complementaires, par exemple "seuls les fichiers csv sont acceptes"
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
fileInput_dsfr_template <- function(
                inputId,
                label,
                message
) {

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "fileInput.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    message = message
  )
}
