# WARNING - Generated by {fusen} from /dev/flat_composants/flat_fileInput.Rmd: do not edit by hand

#' fileInput_dsfr
#'
#'
#' @param inputId id de l'input
#' @param label etiquette du bouton d'import, par exemple "choisir fichier"
#' @param message eventuelles indications complementaires, par exemple "fichier images de moins de 2 Mo"
#'
#' @return html
#' @importFrom assertthat assert_that
#' @export
#' @seealso [fileInput()] Pour en savoir plus sur la fonction originelle de Shiny.
#' [Documentation externe](https://shiny.posit.co/r/reference/shiny/latest/fileinput)
#' @examples
#'
#' if (interactive()) {
#'   ui <- fluidPage_dsfr(
#'     fluidRow_dsfr(
#'       column_dsfr(width = 4,
#'         fileInput_dsfr(inputId = "file1", label = "Importez vos données", message = "seul le format csv est pris en charge"),
#'         br(),
#'         checkboxInput_dsfr(inputId = "header", label = "Utiliser les en-tetes du fichier")
#'       ),
#'       column_dsfr(width = 8,
#'         tableOutput_dsfr("contenu")("contenu")
#'       )
#'     )
#'   )
#'
#'   server <- function(input, output) {
#'     output$contenu <- renderTable({
#'       file <- input$file1
#'       ext <- tools::file_ext(file$datapath)
#'
#'       req(file)
#'       validate(need(ext == "csv", "Veuillez choisir un fichier csv svp"))
#'
#'       read.csv2(file$datapath, header = input$header, nrows = 12)
#'     })
#'   }
#'
#'   shinyApp(ui, server)
#' }
#'
#'
fileInput_dsfr <- function(
                inputId,
                label,
                message
                ) {

  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.character(message))

  fileInput_dsfr_template(
    inputId = inputId,
    label = label,
    message = message
  ) %>%
    parse_html()

}
