# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_fluidpage.Rmd: do not edit by hand

#' fluidPage_dsfr
#'
#' @param ... element a inclure dans la page
#' @param header l entete de la page
#' @param theme pas implemente
#' @param lang pas implemente
#' @param title titre de la page
#'
#' @return html
#'
#' @importFrom htmltools tagList
#'
#' @export
#'
#' @examples
#' my_page <- fluidPage_dsfr(
#'   header = header_dsfr(
#'     intitule = "Prefet de",
#'     officiel = "Bretagne",
#'   ),
#'   title = "Gouv",
#'   htmltools::div("test")
#' )
#' if (interactive()) {
#'   shiny::shinyApp(
#'     my_page,
#'     server = function(input, output) {}
#'   )
#' }
fluidPage_dsfr <- function(
  ...,
  header = NULL,
  title = NULL,
  theme = NULL,
  lang = NULL
) {

  # TODO theme et lang
  # check les params
  ui <- fluidPage_dsfr_template(
    header = tagList(header),
    title = tagList(title),
    body = tagList(
      ...
    )
  ) %>%
    parse_html(zone = "/html") %>%
    add_dsfr_deps()
  ui
}
