# WARNING - Generated by {fusen} from dev/flat_composants/flat_fluidpage.Rmd: do not edit by hand

#' fluidRow_dsfr
#'
#'
#' @param ... differents tag pour construire la page
#' @param class ajout de class pour la fluidRow_dsfr (voir la page officiel du CSS)
#'
#' @return shiny.tag.list
#' @importFrom htmltools tagList
#'
#' @export
#' @examples
#'
#' if (interactive()) {
#'   shiny::shinyApp(
#'     ui = fluidPage_dsfr(
#'       title = "exemple",
#'       fluidRow_dsfr(
#'         shiny::p("Voici un exemple")
#'       )
#'     ),
#'     server = function(input, output) {}
#'   )
#' }
#'
fluidRow_dsfr <- function(..., class = NULL) {
  layout_dsfr_template(
    html = tagList(
      ...
    ),
    class = "fr-grid-row",
    other_class = class
  )
}
