# WARNING - Generated by {fusen} from dev/flat_composants/flat_fluidpage.Rmd: do not edit by hand

#' fluidPage_dsfr
#'
#' @param ... element a inclure dans la page
#' @param header l entete de la page (voir `header_dsfr()`)
#' @param footer contenu du pied de page
#' @param theme pas implemente
#' @param lang pas implemente
#' @param title titre de la page
#'
#' @return html
#'
#' @importFrom htmltools tagList
#'
#' @export
#'
#' @examples
#' if (interactive()) {
#' 
#'   library(shiny)
#'   my_page <- fluidPage_dsfr(
#'     header = header_dsfr(
#'       intitule = tags$span("Prefet", br(), "de", br(), "Bretagne")
#'     ),
#'     title = "Gouv",
#'     htmltools::div("test")
#'   )
#' 
#'   shiny::shinyApp(
#'     my_page,
#'     server = function(input, output) {}
#'   )
#' }
fluidPage_dsfr <- function(
  ...,
  header = NULL,
  title = NULL,
  footer = NULL,
  theme = NULL,
  lang = NULL
    ) {
  # TODO theme et lang
  # check les params
  ui <- fluidPage_dsfr_template(
    header = tagList(header),
    title = tagList(title),
    body = tagList(
      ...
    ),
    footer = footer
  ) %>%
    # parse_html(zone = "/html") %>%
    add_dsfr_deps()

  ui
}
