# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_fluidpage.Rmd: do not edit by hand

#' fluidPage_dsfr_template
#' 
#' @param title titre de la page
#' @param body body 
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
fluidPage_dsfr_template <- function(
    title,
    body
){
  
  htmltools::htmlTemplate(
    filename = system.file(
      "v1.7.2",
      "composant", 
      "fluidpage.html",
      package = "shinygouv"
    ),
    title = title,
    body = body
  )
}

