# WARNING - Generated by {fusen} from dev/flat_composants/flat_fluidpage.Rmd: do not edit by hand

#' fluidPage_dsfr_template
#' @param header entete de la page
#' @param title titre de la page
#' @param body body
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
fluidPage_dsfr_template <- function(
    header,
    title,
    body
    ) {

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "fluidpage.html",
      package = "shinygouv"
    ),
    header = header,
    title = title,
    body = body
  )
}
