# WARNING - Generated by {fusen} from dev/flat_composants/flat_footer.Rmd: do not edit by hand

#' footer_dsfr

#' Il se compose des éléments suivants:
#' - un bloc marque, voir la charte de marque
#' - un texte de présentation - optionnel.
#' - 4 liens de références de l'écosystème institutionnel - obligatoires.
#'- la liste de liens liés aux obligations légales. Cette liste doit être définie en fonction du site, toutefois les liens & contenus suivants sont obligatoires : “accessibilité : non/partiellement/totalement conforme”, mentions légales, données personnelles et gestion des cookies. - obligatoire.
#' - une mention de la licence - obligatoire “Sauf mention contraire, tous les contenus de ce site sont sous licence etalab-2.0”
#'
#' Il est possible d'ajouter des url supplémentaires dans le corps et le bas du pied de page.
#'
#' @param intitule la partie "intitule" du bloc marque. Utiliser un `shiny::tags$span()`pour mettre l'intitulé sur plusieurs lignes ou un vecteur. 
#' @param description un texte de présentation - optionnel
#' @param accessibilite le type d'accessibilité (non/partiellement/totalement conforme)
#' @param lien_accessibilite lien url vers l'accessibilite
#' @param lien_mentions_legales lien url vers les mentions légales
#' @param lien_donnees_personnelles lien url vers les données personnelles
#' @param lien_gestion_cookies lien url vers la gestion des cookies
#' @param add_extra_url_body url supplementaire a ajouter au corps du pied de page (voir `footer_extra_url_body_dsfr()`)
#' @param add_extra_url_bottom url supplementaire a ajouter au bas du pied de page (voir `footer_extra_url_bottom_dsfr()`)
#' 
#' @return html
#' @export
#' @rdname footer_dsfr
#' @examples
#' if (interactive()) {
#'   library(shiny)
#'   shinyApp(
#'     ui = fluidPage_dsfr(
#'       footer = footer_dsfr(
#'         intitule = c("Territoire", "Service"),
#'         description = "une description",
#'         accessibilite = "non",
#'         add_extra_url_body = footer_extra_url_body_dsfr(
#'           footer_li_dsfr(
#'             href = "https://siteinternet.fr",
#'             titre = "siteinternet.fr.fr - nouvelle fenêtre",
#'             texte = "siteinternet.fr.fr", type = "body"
#'           ),
#'           footer_li_dsfr(
#'             href = "https://siteinternet.fr",
#'             titre = "siteinternet.fr.fr - nouvelle fenêtre",
#'             texte = "siteinternet.fr.fr", type = "body"
#'           )
#'         ),
#'         add_extra_url_bottom = footer_extra_url_bottom_dsfr(
#'
#'           footer_li_dsfr(
#'             href = "https://siteinternet.fr",
#'             titre = "siteinternet.fr.fr - nouvelle fenêtre",
#'             texte = "siteinternet.fr.fr", type = "bottom"
#'           )
#'         )
#'       ),
#'       tabsetPanel_dsfr(
#'         "coucou",
#'         tabPanel_dsfr(
#'           id = "tab1",
#'           title = "Une prems tab",
#'           content = tagList(h3("Coucou"),
#'                             plotOutput("plot"))
#'         ),
#'         tabPanel_dsfr(
#'           id = "tab2",
#'           title = "Une deuxieme tab",
#'           content = tagList(h3("Salut"),
#'                             plotOutput("plot2"))
#'         )
#'       )
#'     ),
#'     server = function(input, output) {
#'       output$plot <- renderPlot({
#'         plot(cars)
#'       })
#'       output$plot2 <- renderPlot({
#'         plot(iris)
#'       })
#'     }
#'   )
#' }
footer_dsfr <- function(    
    intitule = NULL,
    description = NULL,
    accessibilite = "non",
    lien_accessibilite = "#",
    lien_mentions_legales = "#",
    lien_donnees_personnelles = "#",
    lien_gestion_cookies = "#",
    add_extra_url_body = NULL, 
    add_extra_url_bottom = NULL) {
  
  
  if ( isFALSE(accessibilite %in% c("non", "partiellement", "totalement conforme"))){
    stop("l accessibilite doit etre 'non', 'partiellement' ou 'totalement conforme'")
  }
  
  assertthat::assert_that(is.character(lien_accessibilite))
  assertthat::assert_that(is.character(lien_mentions_legales))
  assertthat::assert_that(is.character(lien_donnees_personnelles))
  assertthat::assert_that(is.character(lien_gestion_cookies))
  
  if(is.vector(intitule) & length(intitule) > 1){
    intitule <- span(HTML(paste0(intitule, collapse = "<br/>")))
  }
  
  
  footer_dsfr_template(
    intitule = intitule,
    description = description,
    footer_body = add_extra_url_body,
    footer_bottom = add_extra_url_bottom,
    accessibilite = accessibilite,
    lien_accessibilite = lien_accessibilite,
    lien_mentions_legales = lien_mentions_legales,
    lien_donnees_personnelles = lien_donnees_personnelles,
    lien_gestion_cookies = lien_gestion_cookies
  )
}


#' footer_extra_url_body_dsfr
#' 
#' Permet d'ajouter des liends/url dans le corps du pied de page
#' 
#' @param ... d'autres liens de références (voir `footer_li_dsfr()`)
#'
#' @return html
#' @rdname footer_dsfr
#' @export
#' @examples
#' footer_extra_url_body_dsfr(
#'                 footer_li_dsfr(href = "http://siteinternet.fr", texte = "siteinternet.fr", type = "body"),
#'                 footer_li_dsfr(href = "http://siteinternet.fr", texte = "siteinternet.fr", type = "body"))
footer_extra_url_body_dsfr <- function(...) {
    tagList(...) 

}



#' footer_extra_url_bottom_dsfr
#' 
#' Permet d'ajouter des liends/url dans le bas du pied de page
#' 
#' @param ... d'autre liens de références (voir `footer_li_dsfr()`)
#'
#' @return html
#' @rdname footer_dsfr
#' @export
#' @examples
#' footer_extra_url_bottom_dsfr(footer_li_dsfr(href = "http://siteinternet.fr", texte = "siteinternet.fr"))
footer_extra_url_bottom_dsfr <-
  function(...) {
      tagList(...)

  }


#' footer_li_dsfr
#' 
#' Permet de créer la balise html pour ajouter un lien en fonction de sa destination (body/bottom)
#' 
#' @param href une url
#' @param texte le texte
#' @param id un identifiant (optionnel)
#' @param titre le titre de l infobulle  (optionnel)
#' @param type le type de rendu de l url (body/bottom, par defaut body)
#' 
#' @rdname footer_dsfr
#' 
#' @return html
#' 
#' @export
#' @examples
#' footer_li_dsfr(href = "http://siteinternet.fr", texte = "siteinternet.fr", type = "body")
#' footer_li_dsfr(href = "http://siteinternet.fr", texte = "siteinternet.fr", type = "bottom")
footer_li_dsfr <- function(id = NULL,
                    href,
                    titre = NULL,
                    texte,
                    type = "body") {

  if (type == "body"){
    target = "target='_blank'"
    ttype = "content"
  } else if (type == "bottom"){
    target = NULL
    ttype = "bottom"
  } else {
    stop("Dans footer_li_dsfr, type doit etre 'body' ou 'bottom'")
  }
  
    htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "piedpage_content.html",
      package = "shinygouv"
    ),
    id = id,
    href = href,
    titre = titre,
    texte = texte,
    type = ttype,
    target = target
  ) |> parse_html()
}

