# WARNING - Generated by {fusen} from /dev/flat_composants/flat_footer.Rmd: do not edit by hand

#' footer_dsfr_template
#' 
#' @param intitule la partie "intitule" du bloc marque
#' @param description un texte de présentation - optionnel
#' @param footer_body le corps du footer
#' @param footer_bottom le bas du footer
#' @param accessibilite le type d'accessibilité (non/partiellement/totalement conforme)
#' @param lien_accessibilite lien url vers l'accessibilite
#' @param lien_mentions_legales lien url vers les mentions légales
#' @param lien_donnees_personnelles lien url vers les données personnelles
#' @param lien_gestion_cookies lien url vers la gestion des cookies
#' 
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
footer_dsfr_template <- function(
    intitule , 
    description , 
    footer_body, footer_bottom,
           accessibilite = "non",
           lien_accessibilite = "#",
           lien_mentions_legales = "#",
           lien_donnees_personnelles = "#",
           lien_gestion_cookies = "#"
    ) {

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "piedpage.html",
      package = "shinygouv"
    ),
    intitule = intitule , 
    description = description, 
    footer_body = footer_body,
    footer_bottom = footer_bottom,
      accessibilite = accessibilite,
      lien_accessibilite = lien_accessibilite,
      lien_mentions_legales = lien_mentions_legales,
      lien_donnees_personnelles = lien_donnees_personnelles,
      lien_gestion_cookies = lien_gestion_cookies
  ) |>  parse_html()
}





