# WARNING - Generated by {fusen} from /dev/flat_composants/flat_footer.Rmd: do not edit by hand

#' footer_extra_url_bottom_dsfr
#' 
#' Permet d'ajouter des liends/url dans le bas du pied de page
#' 
#' @param ... d'autre liens de références (voir `footer_li_dsfr()`)
#'
#' @return html
#' @rdname footer_dsfr
#' @export
footer_extra_url_bottom_dsfr <-
  function(...) {
      tagList(...)

  }

