# WARNING - Generated by {fusen} from /dev/flat_convert_to_dsfr.Rmd: do not edit by hand

#' Recuperer la version du dsfr de 'shinygouv'
#' 
#' @return Character. Numero de version
#' 
#' @export
#' @examples
#' get_dsfr_version()
get_dsfr_version <- function(){
    utils::packageDescription(pkg = 'shinygouv')[["VersionDsfr"]]
}
