# WARNING - Generated by {fusen} from /dev/flat_composants/flat_header.Rmd: do not edit by hand

#' header_dsfr
#' Vous pouvez ajouter le header officiel dans votre application avec `header_dsfr()`. 
#' @param intitule la partie "intitule" du bloc marque. Utiliser un `shiny::tags$span()`pour mettre l'intitulé sur plusieurs lignes ou un vecteur. 
#' @param url l url de redirection - optionnel
#' @param titre le texte de description de l url - optionnel
#' @param nom_site_service le nom du site ou du service - optionnel
#' @param baseline le texte sous le nom de site/service - optionnel
#' @param class un classe a ajouter si necessaire ("fr-m-1w" correspond a une margin de 1w sur tous les cotés) - optionnel, par defaut "fr-container" (centré) (voir le Systeme de design de l'Etat "fondamentaux-techniques/espacements")
#' @return html
#' @export
#'
#' @examples
#' if(interactive()) {
#'   library(shiny)
#'   header_dsfr(
#'     intitule = c("Pr\u00e9fet", "de", "Bretagne")
#'   )
#' }
header_dsfr <- function(
    intitule = c("intitul\u00e9", "du", 'bloc-marque'),
    url = "/",
    titre = NULL,
    nom_site_service = NULL,
    baseline = NULL,
    class = "fr-container"
    ) {
  # check les params
  # assertthat::assert_that(is.character(intitule))
  # TODO verifier que l url est valide
  
  if(is.vector(intitule) & length(intitule) > 1){
    intitule <- span(HTML(paste0(intitule, collapse = "<br/>")))
  }

  res <- header_dsfr_template(
    class = class,
    intitule = intitule,
    url = url,
    titre = titre,
    nom_site_service = nom_site_service,
    baseline = baseline
  ) %>%
    parse_html()
  class(res) <- c("header_dsfr", class(res))
  res
}
