# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_header.Rmd: do not edit by hand

#' header_dsfr_template
#' @param intitule la partie "intitule" du bloc marque
#' @param officiel la partie "officiel" du bloc marque
#' @param url l url de redirection
#' @param titre le texte de description de l url
#' @param nom_site_service le nom du site ou du service - optionnel
#' @param baseline le texte sous le nom de site/service - optionnel
#' @param class un classe a ajouter si necessaire (".fr-m-1w" pour #TODO) - optionnel
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
header_dsfr_template <- function(
  intitule,
  officiel,
  url,
  titre,
  nom_site_service,
  baseline,
  class
) {
  htmltools::htmlTemplate(
    filename = system.file(
      "v1.7.2",
      "composant",
      "entete.html",
      package = "shinygouv"
    ),
    class = class,
    intitule = intitule,
    officiel = officiel,
    url = url,
    titre = titre,
    nom_site_service = nom_site_service,
    baseline = baseline
  )
}
