# WARNING - Generated by {fusen} from dev/flat_composants/flat_header.Rmd: do not edit by hand

#' header_dsfr
#'
#' @param intitule la partie "intitule" du bloc marque
#' @param officiel la partie "officiel" du bloc marque
#' @param url l url de redirection - optionnel
#' @param titre le texte de description de l url - optionnel
#' @param nom_site_service le nom du site ou du service - optionnel
#' @param baseline le texte sous le nom de site/service - optionnel
#' @param class un classe a ajouter si necessaire ("fr-m-1w" correspond a une margin de 1w sur tous les cotés) - optionnel, par defaut "fr-container" (centré) (voir le Systeme de design de l'Etat "fondamentaux-techniques/espacements")
#' @return html
#' @export
#'
#' @examples
#' header_dsfr(
#'   intitule = "Prefet de",
#'   officiel = "Bretagne",
#' )
header_dsfr <- function(
  intitule,
  officiel,
  url = "/",
  titre = NULL,
  nom_site_service = NULL,
  baseline = NULL,
  class = "fr-container"
    ) {
  # check les params
  assertthat::assert_that(is.character(intitule))
  assertthat::assert_that(is.character(officiel))
  # TODO verifier que l url est valide

  res <- header_dsfr_template(
    class = class,
    intitule = intitule,
    officiel = officiel,
    url = url,
    titre = titre,
    nom_site_service = nom_site_service,
    baseline = baseline
  ) %>%
    parse_html()
  class(res) <- c("header_dsfr", class(res))
  res
}
