# WARNING - Generated by {fusen} from /dev/flat_composants/flat_fluidpage.Rmd: do not edit by hand

#' layout_dsfr_template
#'
#' @param html list de tag
#' @param class class de la div
#' @param other_class autre classes a ajouter
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
layout_dsfr_template <- function(
  html,
  class,
  other_class
) {
  htmltools::htmlTemplate(
    filename = system.file(
      "v1.7.2",
      "layout",
      "layout.html",
      package = "shinygouv"
    ),
    html = html,
    class = class,
    other_class = other_class
  )
}
