# WARNING - Generated by {fusen} from dev/flat_composants/flat_modal.Rmd: do not edit by hand

#' modalDialog_dsfr
#'
#'
#' @param ... element a inclure dans le modal
#' @param inputId inputId du modal
#' @param title titre du modal
#' @param footer footer du modal
#' @return html
#'
#' @export
#' @importFrom htmltools tagList
#' @examples
#' if (interactive()) {
#'   library(shiny)
#'   ui <- fluidPage_dsfr(
#'     actionButton_dsfr("show", "Show modal dialog")
#'   )
#'   server <- function(input, output, session) {
#'     observeEvent(input$show, {
#'       showModal_dsfr(
#'         ui = modalDialog_dsfr(
#'           tagList(
#'             htmltools::div("Le corps du texte"),
#'             actionButton_dsfr(
#'               inputId = "btn",
#'               label = "txt"
#'             )
#'           ),
#'           title = "Titre du modal",
#'           footer = "Footer du modal"
#'         )
#'       )
#'     })
#' 
#'     observe({
#'       print(input$btn)
#'     })
#'   }
#'   shinyApp(ui, server)
#' }
#' 
modalDialog_dsfr <- function(
  ...,
  inputId = "fr-modal-1",
  title,
  footer = NULL
    ) {
  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(title))

  modalDialog_dsfr_template(
    inputId = inputId,
    title = title,
    body = tagList(...),
    footer = tagList(footer)
  )
}


#' @export
showModal_dsfr <- function(
  ui,
  inputId = "fr-modal-1",
  session = shiny::getDefaultReactiveDomain()
    ) {
  session$sendCustomMessage(
    "show_dsfr_modal",
    list(
      ui = as.character(ui),
      inputId = inputId
    )
  )
}

#' @export
removeModal_dsfr <- function(
  inputId = "fr-modal-1",
  session = shiny::getDefaultReactiveDomain()
    ) {
  session$sendCustomMessage("hide_dsfr_modal", inputId)
}

