# WARNING - Generated by {fusen} from /dev/flat_composants/flat_modal.Rmd: do not edit by hand

#' modalDialog_dsfr
#'
#'
#' @param ... element a inclure dans le modal
#' @param inputId inputId du modal
#' @param title titre du modal
#' @param footer footer du modal
#' @return html
#'
#' @export
#' @importFrom htmltools tagList
#' @examples
#'
#' modalDialog_dsfr(
#'   htmltools::div("Le corps du texte"),
#'   title = "Titre du modal",
#'   footer = actionButton_dsfr(
#'     inputId = "Bouton",
#'     label = "Bouton"
#'   )
#' )
#'
modalDialog_dsfr <- function(
    ...,
    inputId = "fr-modal-1",
    title,
    footer = NULL) {
  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(title))

  modalDialog_dsfr_template(
    inputId = inputId,
    title = title,
    body = tagList(...),
    footer = tagList(footer)
  ) %>%
    # parse_html(zone = "/html") %>%
    add_dsfr_deps()
}


#' @export
showModal_dsfr <- function(inputId = "fr-modal-1", session = shiny::getDefaultReactiveDomain()) {
  session$sendCustomMessage("show_dsfr_modal", inputId)
}

#' @export
removeModal_dsfr <- function(inputId = "fr-modal-1", session = shiny::getDefaultReactiveDomain()) {
  session$sendCustomMessage("hide_dsfr_modal", inputId)
}
