# WARNING - Generated by {fusen} from dev/flat_composants/flat_modal.Rmd: do not edit by hand

#' modalDialog_dsfr_template
#'
#' @param inputId inputId du modal
#' @param title titre du modal
#' @param body body du modal
#' @param footer footer du modal
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
modalDialog_dsfr_template <- function(
    inputId = "fr-modal-1",
    title,
    body,
    footer = NULL
    ) {
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "modalDialog.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    title = title,
    body = body,
    footer = footer
  )
}
