# WARNING - Generated by {fusen} from /dev/flat_composants/flat_numericInput.Rmd: do not edit by hand

#' numericInput_dsfr
#'
#'
#' @return html
#'
#' @export
#'
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'   library(shiny)
#'   library(shinygouv)
#'
#'   ui <- fluidPage_dsfr(
#'     header = header_dsfr(
#'       intitule = "Intitule",
#'       officiel = "Officiel",
#'       nom_site_service = "Nom du site / service",
#'       baseline = "baseline - precisions sur l organisation",
#'       class = "fr-m-1w"
#'     ),
#'     title = "Exemple",
#'     fluidRow_dsfr(
#'       numericInput_dsfr(
#'         inputId = "mynumericinput",
#'         label = "Numeric input",
#'         value = 12,
#'         min = 0,
#'         max = NA,
#'         step = 2
#'       ),
#'       verbatimTextOutput(outputId = "numericinputvalue")
#'     )
#'   )
#'   server <- function(input, output, session) {
#'     output$numericinputvalue <- renderText({
#'       paste("La valeur de l'input est", input$mynumericinput)
#'     })
#'   }
#'
#'   shinyApp(ui, server)
#' }
numericInput_dsfr <- function(
  inputId = inputId,
  label = label,
  value = value,
  min = NA,
  max = NA,
  step = NA
    ) {
  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.numeric(value))
  assertthat::assert_that(is.na(min) | is.numeric(min))
  assertthat::assert_that(is.na(max) | is.numeric(max))
  assertthat::assert_that(is.na(step) | is.numeric(step))


  numericInput_dsfr_template(
    inputId = inputId,
    label = label,
    value = value,
    min = min,
    max = max,
    step = step
  ) %>%
    parse_html()
}
