# WARNING - Generated by {fusen} from /dev/flat_composants/flat_numericInput.Rmd: do not edit by hand

#' numericInput_dsfr_template
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
numericInput_dsfr_template <- function(
  inputId,
  label,
  value,
  min = NA,
  max = NA,
  step = NA
    ) {
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "numericinput.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    value = value,
    min = ifelse(is.na(min), "", min),
    max = ifelse(is.na(max), "", max),
    step = ifelse(is.na(step), "", step)
  )
}
