# WARNING - Generated by {fusen} from /dev/flat_tools.Rmd: do not edit by hand

#' Traduit du html en resultat shiny 
#'
#' @param html_code resultat d'une fonction htmlTemplate ou une chaine de caractere
#' @param zone zone a garder pour parser
#'
#' @return shiny.tag
#' @export
#'
#' @examples
#' html_code <- '<button id="test" type="button" class="btn btn-default action-button">test</button>'
#' parse_html(html_code)
parse_html <- function(html_code, zone = "/html/body/*") {
 
  xml <- parse_to_xml(html_code, zone) %>% render_node(prefix = TRUE)
  
  eval(parse(text = xml)) 
}
