# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_radioButtons.Rmd: do not edit by hand

#' radioButtons_unique_dsfr_template
#'
#' @param inputId id de l'input avec indexation
#' @param choix choix Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param name nom de l'inputId sans indexation
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
radioButtons_unique_dsfr_template <- function(
  inputId,
  choix,
  name,
  inline = FALSE
) {
  if (is.null(names(choix))) {
    name_choix <- choix
  } else {
    name_choix <- names(choix)
  }


  if (isTRUE(inline)) {
    class_inline <- "-inline"
  } else {
    class_inline <- NULL
  }

  htmltools::htmlTemplate(
    filename = system.file(
      "v1.7.2",
      "composant",
      "radiobouton.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    name = name,
    name_choix = name_choix,
    value_choix = choix,
    class_inline = class_inline
  )
}
