# WARNING - Generated by {fusen} from /dev/flat_composants/flat_radioButtons.Rmd: do not edit by hand

#' radioButtons_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @param class des classes a ajouter si necessaire
#' @return html
#'
#' @export
#'
#' @examples
#' radioButtons_dsfr(
#'   inputId = "test",
#'   label = "Test",
#'   choices = c("A", "B"),
#'   class = NULL
#' )
#'
#' # radioButtons_dsfr(
#' #       inputId = "test",
#' #       label = "Test",
#' #       choices = c("Choix A" = "A","Choix B" = "B"),
#' #       class = NULL
#' # )
radioButtons_dsfr <- function(
  inputId,
  label,
  choices,
  inline = FALSE,
  class = NULL
) {

  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.character(choices))
  assertthat::assert_that(is.logical(inline))

  radioButtons_dsfr_template(
    inputId = inputId,
    label = label,
    choix = choices,
    inline = inline,
    class = class
  ) %>%
    parse_html()
}
