# WARNING - Generated by {fusen} from dev/flat_composants/flat_radioGroupButtons.Rmd: do not edit by hand

#' radioGroupButtons_unique_dsfr_template
#'
#' @param inputId id de l'input avec indexation
#' @param choix choix une valeur a selectionner
#' @param nom_choix le nom de la valeur a selectionner/afficher
#' @param name nom de l'inputId sans indexation
#' @param selected Bouton sélectionné ou non
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
radioGroupButtons_unique_dsfr_template <-
  function(
  inputId,
  choix,
  nom_choix,
  name,
  selected = FALSE,
  inline = FALSE
      ) {
    htmltools::htmlTemplate(
      filename = system.file(
        get_dsfr_version(with_v = TRUE),
        "composant",
        "radiogroupbutton_unique.html",
        package = "shinygouv"
      ),
      inputId = inputId,
      name = name,
      nom_choix = nom_choix,
      value_choix = choix,
      selected = if (isTRUE(selected)) "" else "fr-btn--secondary",
      checked = if (isTRUE(selected)) 'checked=""' else NULL,
      inline = inline
    )
  }
