# WARNING - Generated by {fusen} from dev/flat_composants/flat_radioGroupButtons.Rmd: do not edit by hand

#' radioGroupButtons_dsfr_template
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choix choix Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element sélectionné (NULL par defaut)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement). NON IMLPEMENTE
#'
#' @importFrom htmltools htmlTemplate tagList
#' @importFrom purrr pmap map_chr
#' @return html
#' @noRd
radioGroupButtons_dsfr_template <- function(
  inputId,
  label,
  choix,
  selected = NULL,
  inline = FALSE
    ) {
  if (isTRUE(inline)) {
    inline_value <- "fr-fieldset__element--inline"
    container_inline <- "shiny-input-container-inline"
  } else {
    inline_value <- ""
    container_inline <- ""
  }


  if (is.null(names(choix))) {
    nom_choix <- choix
  } else {
    nom_choix <- names(choix)
  }

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "radiogroupbutton.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    container_inline = container_inline,
    choix = pmap(
      list(
        .x = choix,
        .y = nom_choix,
        .nb = seq_along(choix),
        .inline = rep(
          inline_value,
          length(choix)
        )
      ),
      function(.x, .y, .nb, .inline) {
        radioGroupButtons_unique_dsfr_template(
          # inputId = paste0(inputId, "-", .nb),
          inputId = paste0(inputId, "-", .x),
          name = inputId,
          choix = .x,
          nom_choix = .y,
          selected = identical(.x, selected),
          inline = .inline
        )
      }
    ) %>%
      htmltools::tagList()
  )
}
