# WARNING - Generated by {fusen} from /dev/flat_composants/flat_radioButtons.Rmd: do not edit by hand

#' radioButtons_dsfr_template
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choix choix Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement). NON IMLPEMENTE
#' @param class des classes a ajouter si necessaire
#'
#' @importFrom htmltools htmlTemplate tagList
#' @importFrom purrr map2 map_chr
#' @return html
#' @noRd
radioButtons_dsfr_template <- function(
  inputId,
  label,
  choix,
  inline = FALSE,
  class = NULL
) {
  inline <- FALSE # TODO
  if (isTRUE(inline)) {
    class_inline <- "fr-fieldset--inline"
    class <- "shiny-input-container-inline"
  } else {
    class_inline <- NULL
  }

  if (is.null(names(choix))) {
    nom_choix <- choix
  } else {
    nom_choix <- names(choix)
  }


  x <- 0
  htmltools::htmlTemplate(
    filename = system.file(
      "v1.7.2",
      "composant",
      "radiobouton_group.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    choix = purrr::map2(
      .x = choix,
      .y = nom_choix,
      ~ {
        x <<- x + 1
        radioButtons_unique_dsfr_template(
          inputId = paste0(inputId, "-", x),
          name = inputId,
          choix = .x,
          nom_choix = .y,
          inline = inline
        )
      }
    ) %>%
      htmltools::tagList(),
    inline = class_inline,
    class = class
  )
}
