# WARNING - Generated by {fusen} from /dev/v1.7.2/composant/flat_radioButtons.Rmd: do not edit by hand

#' radioButtons_dsfr_template
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choix choix Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @param class des classes a ajouter si necessaire
#'
#' @importFrom htmltools htmlTemplate tagList
#' @importFrom purrr map map_chr
#' @return html
#' @noRd
radioButtons_dsfr_template <- function(
  inputId,
  label,
  choix,
  inline = FALSE,
  class = NULL
) {
  if (isTRUE(inline)) {
    class_inline <- "fr-fieldset--inline"
    class <- "shiny-input-container-inline"
  } else {
    class_inline <- NULL
  }

  htmltools::htmlTemplate(
    filename = system.file(
      "v1.7.2",
      "composant",
      "radiobouton_group.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    choix = purrr::map(
      .x = choix,
      ~ radioButtons_unique_dsfr_template(
        inputId = inputId,
        choix = .x,
        inline = inline
      )
    ) %>%
      htmltools::tagList(),
    inline = class_inline,
    class = class
  )
}
