# WARNING - Generated by {fusen} from dev/flat_composants/flat_radioGroupButtons.Rmd: do not edit by hand

#' radioGroupButtons_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element sélectionné (NULL par défaut)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @return html
#'
#' @export
#'
#' @examples
#' if (interactive()) {
#'   library(shiny)
#'   library(shinygouv)
#'
#'   ui <- fluidPage_dsfr(
#'     header = header_dsfr(
#'       intitule = "Intitule",
#'       officiel = "Officiel",
#'       nom_site_service = "Nom du site / service",
#'       baseline = "baseline - precisions sur l organisation",
#'       class = "fr-m-1w"
#'     ),
#'     title = "Exemple",
#'     fluidRow_dsfr(
#'       radioGroupButtons_dsfr(
#'         inputId = "espece_radiogroupbutton",
#'         label = "Especes (radio group button avec inline = FALSE)",
#'         choices = c("Setosa" = "setosa", "Versicolor" = "versicolor", "Virginica" = "virginica"),
#'         selected = "virginica",
#'         inline = FALSE
#'       )
#'     ),
#'     fluidRow_dsfr(
#'       actionButton_dsfr(
#'         inputId = "update_radiogroupbutton_label",
#'         label = "Update label"
#'       ),
#'       actionButton_dsfr(
#'         inputId = "update_radiogroupbutton_choices",
#'         label = "Update choices"
#'       ),
#'       actionButton_dsfr(
#'         inputId = "update_radiogroupbutton_selected",
#'         label = "Update selected"
#'       )
#'     ),
#'     fluidRow_dsfr(
#'       verbatimTextOutput(outputId = "outputespece_radiogroupbutton")
#'     )
#'   )
#'
#'   server <- function(input, output, session) {
#'     output$numericinputvalue <- renderText({
#'       paste("La valeur de l'input est", input$mynumericinput)
#'     })
#'
#'     r <- reactiveValues()
#'
#'     output$outputespece_radiogroupbutton <- renderText({
#'       paste("Esp\u00e8ce radiogroupbutton :", input$espece_radiogroupbutton)
#'     })
#'
#'
#'     observeEvent(input$update_radiogroupbutton_label, {
#'       updateRadioGroupButtons_dsfr(
#'         inputId = "espece_radiogroupbutton",
#'         label = paste0(sample(LETTERS, size = 12), collapse = ""),
#'         session = session
#'       )
#'     })
#'
#'     observeEvent(input$update_radiogroupbutton_choices, {
#'       r$radiogroupubutton_choices <- sapply(1:5, function(x) paste0(sample(LETTERS, size = 3), collapse = ""))
#'
#'       updateRadioGroupButtons_dsfr(
#'         inputId = "espece_radiogroupbutton",
#'         choices = r$radiogroupubutton_choices,
#'         session = session
#'       )
#'     })
#'
#'     observeEvent(input$update_radiogroupbutton_selected, {
#'       updateRadioGroupButtons_dsfr(
#'         inputId = "espece_radiogroupbutton",
#'         selected = sample(r$radiogroupubutton_choices, size = 1),
#'         session = session
#'       )
#'     })
#'   }
#'
#'   shinyApp(ui, server)
#' }
radioGroupButtons_dsfr <- function(
  inputId,
  label,
  choices,
  selected = NULL,
  inline = FALSE
    ) {
  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  assertthat::assert_that(is.character(choices))
  assertthat::assert_that(length(selected) <= 1)
  assertthat::assert_that(is.logical(inline))

  radioGroupButtons_dsfr_template(
    inputId = inputId,
    label = label,
    choix = choices,
    selected = selected,
    inline = inline
  ) %>%
    parse_html()
}
