# WARNING - Generated by {fusen} from dev/flat_tools.Rmd: do not edit by hand

#' render_node
#'
#' @param node node qui provient de parse_to_xml
#' @param indent ajout de l'indentation
#' @param prefix si TRUE alors le resultat sera prefixe par tags
#'
#' @importFrom XML xmlName xmlValue xmlChildren
#' @importFrom stringr str_pad
#' @importFrom purrr partial
#'
#' @noRd
render_node <- function(
  node,
  indent = 0,
  prefix = FALSE
    ) {
  if (xmlName(node) == "text") {
    txt <- xmlValue(node)
    if (nchar(trimws(txt)) > 0) {
      paste0("\"", trimws(txt), "\"")
    }
  } else {
    tagName <- if (prefix) {
      paste0("tags$", xmlName(node))
    } else {
      xmlName(node)
    }

    my_render <- partial(
      render_node,
      indent = newIndent,
      prefix = prefix
    )
    newIndent <- indent + length(tagName) + 1
    xmlChildren(node) %>%
      Keep(my_render, .) %>%
      append(make_attrs(node), .) %>%
      paste(collapse = str_pad(
        ",\n",
        width = newIndent,
        side = c("right")
      )) %>%
      trimws(which = c("left")) %>%
      paste0(tagName, "(", ., ")")
  }
}

#' @noRd
#' @importFrom XML xmlAttrs
#' @importFrom stringr str_detect
make_attrs <- function(node) {
  attrs <- xmlAttrs(node)
  names(attrs) %>% Map(function(name) {
    val <- attrs[[name]]
    if (str_detect(string = name, pattern = "-") || str_detect(
      string = name,
      pattern = "for"
    )) {
      name <- paste0("`", name, "`")
    }
    paste0(name, " = ", if (val == "") {
      "NA"
    } else {
      paste0("\"", val, "\"")
    })
  }, .)
}

#' @noRd
Keep <- function(fun, xs) {
  Map(fun, xs) %>% Filter(Negate(is.null), .)
}
