# WARNING - Generated by {fusen} from dev/flat_composants/flat_selectInput.Rmd: do not edit by hand

#' Template pour la liste des options du selectInput
#'
#' Template pour la liste des options du selectInput
#'
#' @param option_value value des options (futurs `choices` du selectInput)
#' @param option_label labels des options (en cas d'utilisation d'un vecteur nommé pour les futurs `choices` du selectInput)
#' @param selected la valeur est-elle sélectionnée par défaut ou non
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
selectInput_options_dsfr_template <- function(
  option_value,
  option_label,
  selected
    ) {
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "options.html",
      package = "shinygouv"
    ),
    option_value = option_value,
    option_label = option_label,
    selected = selected
  )
}
