# WARNING - Generated by {fusen} from /dev/flat_composants/flat_selectInput.Rmd: do not edit by hand

#' selectInput_dsfr_template
#'
#' @param inputId inputId
#' @param label label
#' @param options options pour les futurs choices
#' @param selected selected
#' @param multiple FALSE par defaut
#'
#' @importFrom htmltools htmlTemplate
#' @importFrom purrr pmap
#' @return html
#' @noRd
selectInput_dsfr_template <- function(
  inputId,
  label,
  options,
  selected = NULL,
  multiple = FALSE
    ) {
  if (is.null(names(options))) {
    option_label <- options
  } else {
    option_label <- names(options)
  }

  selected_logical <- options %in% selected
  selected_value <- gsub(x = as.character(selected_logical), pattern = "FALSE", replacement = "")
  selected_value <- gsub(x = selected_value, pattern = "TRUE", replacement = "selected")

  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "selectInput.html",
      package = "shinygouv"
    ),
    inputId = inputId,
    label = label,
    multiple = ifelse(isTRUE(multiple), 'multiple = "multiple"', ""),
    options = purrr::pmap(
      list(
        .x = options,
        .y = option_label,
        .z = selected_value
      ),
      function(.x, .y, .z) {
        selectInput_options_dsfr_template(
          option_value = .x,
          option_label = .y,
          selected = .z
        )
      }
    ) %>%
      htmltools::tagList()
  )
}
