# WARNING - Generated by {fusen} from /dev/flat_composants/flat_selectInput.Rmd: do not edit by hand

#' selectInput_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element selectionné
#' @importFrom assertthat assert_that
#' @return html
#'
#' @export
#'
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'   library(shiny)
#'   library(shinygouv)
#'
#'   ui <- fluidPage_dsfr(
#'     header = header_dsfr(
#'       intitule = "Intitule",
#'       officiel = "Officiel",
#'       nom_site_service = "Nom du site / service",
#'       baseline = "baseline - precisions sur l organisation",
#'       class = "fr-m-1w"
#'     ),
#'     title = "Exemple",
#'     fluidRow_dsfr(
#'       # sans vecteur nommé
#'       selectInput_dsfr(
#'         inputId = "myselectInput",
#'         label = "Mon label",
#'         choices = c(
#'           "cyl",
#'           "am",
#'           "gear"
#'         )
#'       ),
#'       fluidRow_dsfr(
#'         # avec un vecteur nommé et une valeur sélectionnée
#'         selectInput_dsfr(
#'           inputId = "myselectInput2",
#'           label = "Mon label2",
#'           choices = c(
#'             "Cylinders" = "cyl",
#'             "Transmission" = "am",
#'             "Gears" = "gear"
#'           ),
#'           selected = "gear"
#'         )
#'       )
#'     )
#'   )
#'   server <- function(input, output, session) {
#'   }
#'
#'   shinyApp(ui, server)
#' }
selectInput_dsfr <- function(
  inputId,
  label,
  choices,
  selected = NULL
    ) {
  # check les params
  assertthat::assert_that(is.character(inputId))
  assertthat::assert_that(is.character(label))
  # assertthat::assert_that(is.character(choices))
  purrr::map(choices, ~ assertthat::assert_that(is.character(.x)))
  assertthat::assert_that(length(selected) <= 1)


  selectInput_dsfr_template(
    inputId = inputId,
    label = label,
    options = choices,
    selected = selected,
    multiple = FALSE
  ) %>%
    parse_html()
}
