# WARNING - Generated by {fusen} from dev/flat_composants/flat_withSpinner.Rmd: do not edit by hand

#' Affiche le spinner
#' 
#' Affiche le spinner dans le cadre d'un appel à `shinygouv::withSpinner_dsfr()`
#' @param spinner_id id du spinner
#' @param session session
#' @importFrom golem invoke_js
#' @return html
#' 
#' @export
#' @examples
#' \dontrun{
#' showSpinner_dsfr()
#' }
showSpinner_dsfr <- function(
    spinner_id = "lds-ring",
    session = shiny::getDefaultReactiveDomain()
    ){
    invoke_js("showid", spinner_id, session = session)
}
