# WARNING - Generated by {fusen} from /dev/flat_composants/flat_slider.Rmd: do not edit by hand

#' Slider Input
#'
#' @inherit shiny::sliderInput
#' @inherit shiny::updateSliderInput
#' @export
sliderInput_dsfr <- shiny::sliderInput
updateSliderInput_dsfr <- shiny::updateSliderInput
