# WARNING - Generated by {fusen} from /dev/flat_composants/flat_tableOutput.Rmd: do not edit by hand

#' tableOutput_dsfr
#'
#' @param outputId 	nom d'output a partir duquel lire la table
#' @return html
#'
#' @export
#'
#' @examples
#' 
#' if (interactive()) {
#'   # table example
#'   shinyApp(
#'     ui = fluidPage_dsfr(
#'       fluidRow_dsfr(
#'         column_dsfr(12,
#'           tableOutput_dsfr('table')
#'         )
#'       )
#'     ),
#'     server = function(input, output) {
#'       output$table <- renderTable(iris)
#'     }
#'   )
#' }
tableOutput_dsfr <- function (outputId) {
  assertthat::assert_that(is.character(outputId))
  shiny::div(id = outputId, class = "fr-table shiny-html-output")
  }
