# WARNING - Generated by {fusen} from dev/flat_composants/flat_panels.Rmd: do not edit by hand

#' tabsetPanel_dsfr
#'
#' @param id id du tabset/du tabPanel
#' @param ... liste de tabPanel_dsfr
#' @param title titre du tabset
#' @param content contenu du tabset
#' @seealso [tabsetpanel() in Shiny](https://shiny.posit.co/r/reference/shiny/latest/tabsetpanel)
#' @return html
#' @export
#' @rdname tabPanel
#' @examples
#' if (interactive()){
#'   library(shiny)
#'   shinyApp(
#'     ui = fluidPage_dsfr(
#'       tabsetPanel_dsfr(
#'         "coucou",
#'         tabPanel_dsfr(
#'           id = "tab1",
#'           title = "Une prems tab",
#'           content = tagList(
#'             h3("Coucou"),
#'             plotOutput("plot")
#'           )
#'         ),
#'         tabPanel_dsfr(
#'           id = "tab2",
#'           title = "Une deuxieme tab",
#'           content = tagList(
#'             h3("Salut"),
#'             plotOutput("plot2")
#'           )
#'         )
#'       )
#'     ),
#'     server = function(input, output) {
#'       output$plot <- renderPlot({
#'         plot(cars)
#'       })
#'       output$plot2 <- renderPlot({
#'         plot(iris)
#'       })
#'     }
#'   )
#' }
tabsetPanel_dsfr <- function(
  id,
  ...
  ) {
    if (missing(id)){
      stop("id is required")
    }
    contenu <- list(...)
    tabsetPanel_dsfr_template(
      tabsetPanelId = id,
      li = purrr::map(contenu, ~ {
      panel_one_li(
        .x$id,
        .x$title
      )
    }),
      divs = purrr::map(contenu, ~ {
        panel_one_body(
          id = .x$id,
          content = .x$content
        )
      })
    )

}

#' @export
#' @rdname tabPanel
tabPanel_dsfr <- function(
  id,
  title,
  content
){
  list(
    id = id,
    title = title,
    content = content
  )
}

