# WARNING - Generated by {fusen} from dev/flat_composants/flat_panels.Rmd: do not edit by hand

#' tabSetPanel_dsfr_template
#'
#' @importFrom htmltools htmlTemplate
#' @return html
#' @noRd
tabSetPanel_dsfr_template <- function(
  li = NULL,
  divs = NULL
    ) {
  # Le tabset complet
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "tabsetPanel.html",
      package = "shinygouv"
    ),
    li = li,
    divs = divs
  )
}

#' @noRd
panel_one_li <- function(
  id,
  content
    ) {
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "tabsetHeader.html",
      package = "shinygouv"
    ),
    id = id,
    name = content
  )
}
#' @noRd
panel_one_body <- function(
    id,
  content
) {
  htmltools::htmlTemplate(
    filename = system.file(
      get_dsfr_version(with_v = TRUE),
      "composant",
      "tabBody.html",
      package = "shinygouv"
    ),
    id = id,
    content = content
  )
}
tabSetPanel_dsfr_template(
  li = panel_one_li(
    "tab-1",
    "Tab 1"
  ),
  divs = panel_one_body(
    "tab-1",
    "Tab 1"
  )
)

