# WARNING - Generated by {fusen} from dev/flat_composants/flat_toggleswitch.Rmd: do not edit by hand

#' toggleSwitch_dsfr
#'
#'
#' @return html
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param activate sous texte quand activé
#' @param deactivate sous texte quand desactivé
#'
#' @export
#'
#' @examples
#' if (interactive()) {
#'     library(shiny)
#'     ui <- fluidPage_dsfr(
#'         toggleSwitch_dsfr(inputId = "test", label = "test")
#'     )
#'
#'     server <- function(input, output, session) {
#'         observeEvent(input$test, {
#'             message(input$test)
#'             message("coucou")
#'         })
#'     }
#'
#'     shinyApp(ui, server)
#' }
toggleSwitch_dsfr <- function(
    inputId,
    label,
    activate = "",
    deactivate = ""
    ) {

    # check les params
    assertthat::assert_that(is.character(label))
    assertthat::assert_that(is.character(inputId))
    assertthat::assert_that(is.character(activate))
    assertthat::assert_that(is.character(deactivate))


    toggleSwitch_dsfr_template(
        inputId = inputId,
        label = label,
        activate = activate,
        deactivate = deactivate
    ) %>%
        parse_html()

}
