# WARNING - Generated by {fusen} from dev/flat_composants/flat_radioButtons.Rmd: do not edit by hand

#' updateRadioButtons_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element selectionné
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement). Seulement si les choix sont updates
#'
#' @importFrom htmltools tagList
#' @importFrom purrr pmap
#' @return html
#'
#' @export
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'   ui <- fluidPage_dsfr(
#'     radioButtons_dsfr(inputId = "inRadioButtons",
#'       label = "Input radio buttons",
#'       choices = c("Item A", "Item B", "Item C"),
#'       # ),
#'       inline = FALSE),
#'     actionButton_dsfr("go", "Change")
#'   )
#'
#'   server <- function(input, output, session) {
#'
#'     observeEvent(input$go, {
#'       updateRadioButtons_dsfr(
#'         session = session,
#'         inputId = "inRadioButtons",
#'         label = "Un nouveau label",
#'         choices = c("A" = "a", "B" = "b"),
#'         selected = "a",
#'         inline = TRUE
#'       )
#'     })
#'
#'     observeEvent(input$inRadioButtons, {
#'       message(input$inRadioButtons)
#'     })
#'   }
#'
#'   shinyApp(ui, server)
#' }
updateRadioButtons_dsfr <- function(inputId,
                                    label = NULL,
                                    choices = NULL,
                                    selected = NULL,
                                    inline = FALSE,
                                    session = shiny::getDefaultReactiveDomain()) {

  ns <- session$ns

  if (!is.null(selected)) {
    selected <- as.character(selected)
  }

  if (is.null(names(choices))) {
    nom_choix <- choices
  } else {
    nom_choix <- names(choices)
  }

  if (!is.null(choices)) {
    tag <- radioButtons_dsfr(
      inputId = ns(inputId),
      label = if (!is.null(label)) label else "",
      choices = choices,
      inline = inline,
      selected = selected
    ) %>%
      htmltools::tagQuery()

    choices <- tag$find(".shiny-options-group")$selectedTags()
    choices <- as.character(choices)

  }

  message <- utils::getFromNamespace("dropNulls", "shiny")(list(
    label = label,
    options = choices,
    value = selected
  ))

  session$sendInputMessage(inputId, message)

  # Choices have to changes to set up inline
  if (!is.null(choices)) {
    update_inline(ns(inputId), inline, session)
  }

}
