# WARNING - Generated by {fusen} from dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

#' updateCheckboxGroupInput_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Valeurs préselectionnées
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @importFrom shiny updateCheckboxInput
#' @return html
#'
#' @export
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'   
#'   library(shiny)
#'   
#'   ui <- fluidPage_dsfr(
#'     checkboxGroupInput_dsfr(
#'       "variable", "Variables to show:",
#'       c("Cylinders" = "cyl",
#'         "Transmission" = "am",
#'         "Gears" = "gear"),
#'       inline = FALSE),
#'     actionButton_dsfr("go", "Change for inline and choices"),
#'     actionButton_dsfr("go2", "Change without inline and choices")
#'   )
#'   
#'   server <- function(input, output, session) {
#'     observeEvent(input$variable, {
#'       print(input$variable)
#'     })
#'     
#'     
#'     observeEvent(input$go, {
#'       updateCheckboxGroupInput_dsfr(
#'         session = session,
#'         inputId = "variable",
#'         label = paste0("test", rnorm(1)),
#'         choices = c("A" = "a", "B" = "b"),
#'         selected = "a",
#'         inline = TRUE
#'       )
#'       
#'     })
#'     
#'     
#'     observeEvent(input$go2, {
#'       updateCheckboxGroupInput_dsfr(
#'         session = session,
#'         inputId = "variable",
#'         label = paste0("test", rnorm(1)),
#'         choices = c("A" = "a", "B" = "b"),
#'         selected = "a",
#'         inline = FALSE
#'       )
#'       
#'     })
#'     
#'   }
#'   shinyApp(ui, server)
#' }
updateCheckboxGroupInput_dsfr <- function(inputId,
                                          label = NULL,
                                          choices = NULL,
                                          selected = NULL,
                                          inline = FALSE,
                                          session = shiny::getDefaultReactiveDomain()) {
  
  ns <- session$ns
  
  if (!is.null(selected)) {
    selected <- as.character(selected)
  }
  
  if (is.null(names(choices))) {
    nom_choix <- choices
  } else {
    nom_choix <- names(choices)
  }
  
  if (!is.null(choices)) {
    tag <- checkboxGroupInput_dsfr(
      inputId = ns(inputId),
      label = if (!is.null(label)) label else "",
      choices = choices,
      inline = inline,
      selected = selected
    ) %>%
      htmltools::tagQuery()
    
    choices <- tag$find(".shiny-options-group")$selectedTags()
    choices <- as.character(choices)
  }
  
  message <- utils::getFromNamespace("dropNulls", "shiny")(list(
    label = label,
    options = choices,
    value = selected
  ))
  session$sendInputMessage(inputId, message)
  
  # Choices have to changes to set up inline
  if (!is.null(choices)) {
    update_inline(ns(inputId), inline, session)
  }
}
