# WARNING - Generated by {fusen} from dev/flat_composants/flat_radioButtons.Rmd: do not edit by hand

#' updateRadioButtons_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element selectionné
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#' @importFrom htmltools tagList
#' @importFrom purrr pmap
#' @return html
#'
#' @export
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'   ui <- fluidPage_dsfr(
#'     radioButtons_dsfr(
#'       inputId = "inRadioButtons",
#'       label = "Input radio buttons",
#'       choices = c("Item A", "Item B", "Item C")
#'     ),
#'     actionButton_dsfr("go", "Change")
#'   )
#'
#'   server <- function(input, output, session) {
#'     observeEvent(input$go, {
#'       updateRadioButtons_dsfr(
#'         session = session,
#'         inputId = "inRadioButtons",
#'         label = "Un nouveau label",
#'         choices = c("A" = "a"),
#'         selected = "a"
#'       )
#'     })
#'
#'     observeEvent(input$inRadioButtons, {
#'       message(input$inRadioButtons)
#'     })
#'   }
#'
#'   shinyApp(ui, server)
#' }
#'
updateRadioButtons_dsfr <- function(
  inputId,
  label = NULL,
  choices = NULL,
  selected = NULL,
  session = shiny::getDefaultReactiveDomain()
    ) {
  ns <- session$ns

  if (!is.null(choices)) {
    choices <- tags$div(
      class = "fr-fieldset__content shiny-options-group",
      tagList(
        choix = pmap(
          list(
            .x = choices,
            .y = names(choices),
            .nb = seq_along(choices)
          ),
          function(.x, .y, .nb) {
            radioButtons_unique_dsfr_template(
              inputId = paste0(ns(inputId), "-", .nb),
              name = ns(inputId),
              choix = .x,
              nom_choix = .y,
              checked = identical(.x, selected),
              inline = FALSE
            )
          }
        )
      )
    )
  }


  message <- utils::getFromNamespace("dropNulls", "shiny")(
    list(
      label = label,
      options = as.character(choices)
    )
  )

  session$sendInputMessage(ns(inputId), message)
}
