# WARNING - Generated by {fusen} from /dev/flat_composants/flat_toggleswitch.Rmd: do not edit by hand

#' Update ToggleSwitch
#'
#' @importFrom shiny updateCheckboxInput
#' @inheritParams shiny::updateCheckboxInput
#' @inheritParams toggleSwitch_dsfr
#' @noRd
#' @examples
#' if (interactive()) {
#'     library(shiny)
#'     ui <- fluidPage_dsfr(
#'         toggleSwitch_dsfr(inputId = "test", label = "test"),
#'         actionButton_dsfr("update", "Update toggle")
#'     )
#' 
#'     server <- function(input, output, session) {
#'         observeEvent(input$test, {
#'             message(input$test)
#'             message("coucou")
#'         })
#' 
#'         observeEvent(input$update, {
#'             updateToggleSwitch_dsfr(
#'                 session = session,
#'                 inputId = "test",
#'                 value = TRUE,
#'                 label = "Update",
#'                 activate = "test",
#'                 deactivate = ""
#'             )
#'         })
#'     }
#' 
#'     shinyApp(ui, server)
#' }
updateToggleSwitch_dsfr <- function(
    session,
    inputId,
    label = NULL,
    value = NULL,
    activate = NULL,
    deactivate = NULL

    ) {
    shiny:::validate_session_object(session)
  
    ns <- session$ns
  
    message <- utils::getFromNamespace("dropNulls", "shiny")(
        list(
            label = label,
            value = value
        )
    )

    session$sendInputMessage(
        ns(inputId),
        message
    )

    session$sendCustomMessage(
        "activate_toggle",
        list(
            inputId = ns(inputId),
            activate = activate
        )
    )

    session$sendCustomMessage(
        "deactivate_toggle",
        list(
            inputId = ns(inputId),
            deactivate = deactivate
        )
    )
}
