# WARNING - Generated by {fusen} from dev/tools/flat_tools.Rmd: do not edit by hand

#' @noRd
update_inline <- function(inputId, inline, session) {
  if (inline) {
    session$sendCustomMessage("inline", inputId)
  } else {
    session$sendCustomMessage("not_inline", inputId)
  }
}
