# WARNING - Generated by {fusen} from dev/flat_composants/flat_radioGroupButtons.Rmd: do not edit by hand

#' updateRadioGroupButtons_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element selectionné
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#' @importFrom htmltools tagList
#' @importFrom purrr pmap
#' @return html
#'
#' @export
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'   ui <- fluidPage_dsfr(
#'     radioGroupButtons_dsfr(
#'       inputId = "inradioGroupButtons",
#'       label = "Input radio buttons",
#'       choices = c("Item A", "Item B", "Item C")
#'     ),
#'     actionButton_dsfr("go", "Change")
#'   )
#'
#'   server <- function(input, output, session) {
#'     observeEvent(input$go, {
#'       updateRadioGroupButtons_dsfr(
#'         session = session,
#'         inputId = "inradioGroupButtons",
#'         label = "Un nouveau label",
#'         choices = c("A" = "a"),
#'         selected = "a"
#'       )
#'     })
#'
#'     observeEvent(input$inradioGroupButtons, {
#'       message(input$inradioGroupButtons)
#'     })
#'   }
#'
#'   shinyApp(ui, server)
#' }
#'
updateRadioGroupButtons_dsfr <- function(
  inputId,
  label = NULL,
  choices = NULL,
  selected = NULL,
  inline = FALSE,
  session = shiny::getDefaultReactiveDomain()
    ) {
  ns <- session$ns

  if (is.null(names(choices))) {
    nom_choix <- choices
  } else {
    nom_choix <- names(choices)
  }

  if (!is.null(choices)) {
    tag <- radioGroupButtons_dsfr(
      inputId = ns(inputId),
      label = if (!is.null(label)) label else "",
      choices = choices,
      selected = selected,
      inline = inline
    ) %>%
      htmltools::tagQuery()

    choices <- tag$find(".shiny-options-group")$selectedTags()
    choices <- as.character(choices)
  }

  message <- utils::getFromNamespace("dropNulls", "shiny")(list(
    label = label,
    options = choices,
    value = selected
  ))

  if (!is.null(selected)) {
    selected <- as.character(selected)
    button_to_color <- paste0(ns(inputId), "-", selected)
    session$sendCustomMessage(
      "updateRadioGroupColorButton",
      list(inputId = button_to_color)
    )
    print(button_to_color)
  }

  session$sendInputMessage(ns(inputId), message)
}
