# WARNING - Generated by {fusen} from dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

#' updateCheckboxGroupInput_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Valeurs préselectionnées
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @importFrom shiny updateCheckboxInput
#' @return html
#'
#' @export
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'
#'   library(shiny)
#'
#'   ui <- fluidPage_dsfr(
#'     checkboxGroupInput_dsfr("variable", "Variables to show:",
#'       c("Cylinders" = "cyl",
#'         "Transmission" = "am",
#'         "Gears" = "gear"),
#'       inline = FALSE),
#'     checkboxGroupInput("ok", "ok", c("test")),
#'     actionButton_dsfr("go", "Change"),
#'     actionButton_dsfr("inline", "Mettre en inline"),
#'     actionButton_dsfr("notinline", "Enlever le inline")
#'   )
#'
#'   server <- function(input, output, session) {
#'     observeEvent(input$variable, {
#'       print(input$variable)
#'     })
#'
#'
#'     observeEvent(input$go, {
#'       updateCheckboxGroupInput_dsfr(
#'         session = session,
#'         inputId = "variable",
#'         label = paste0("test", rnorm(1)),
#'         choices = c("A" = "a", "B" = "b"),
#'         selected = "a"
#'       )
#'
#'       updateCheckboxGroupInput(
#'         session = session,
#'         inputId = "ok",
#'         label = paste0("test", rnorm(1))
#'       )
#'     })
#'     
#'     
#'     observeEvent(input$inline, {
#'       updateCheckboxGroupInput_dsfr(
#'         session = session,
#'         inputId = "variable",
#'         inline = TRUE
#'       )
#'     })
#'     
#'     observeEvent(input$notinline, {
#'       updateCheckboxGroupInput_dsfr(
#'         session = session,
#'         inputId = "variable",
#'         inline = FALSE
#'       )
#'     })
#'     
#'   }
#'   shinyApp(ui, server)
#' }
updateCheckboxGroupInput_dsfr <- function(inputId,
                                          label = NULL,
                                          choices = NULL,
                                          selected = NULL,
                                          inline = FALSE,
                                          session = shiny::getDefaultReactiveDomain()) {

  ns <- session$ns

  if (!is.null(selected)) {
    selected <- as.character(selected)
  }

  if (is.null(names(choices))) {
    nom_choix <- choices
  } else {
    nom_choix <- names(choices)
  }

  if (!is.null(choices)) {
    tag <- checkboxGroupInput_dsfr(
      inputId = ns(inputId),
      label = if (!is.null(label)) label else "",
      choices = choices,
      inline = inline,
      selected = selected
    ) %>%
      htmltools::tagQuery()

    choices <- tag$find(".shiny-options-group")$selectedTags()
    choices <- as.character(choices)
  }

  message <- utils::getFromNamespace("dropNulls", "shiny")(list(
    label = label,
    options = choices,
    value = selected
  ))
  session$sendInputMessage(ns(inputId), message)
  update_inline(ns(inputId), inline, session)
}

#' @noRd 
update_inline <- function(inputId, inline, session) {
  if (inline) {
    session$sendCustomMessage("inline", inputId)
  } else {
    session$sendCustomMessage("not_inline", inputId)
  }
}
