# WARNING - Generated by {fusen} from dev/flat_composants/flat_radioGroupButtons.Rmd: do not edit by hand

#' updateRadioGroupButtons_dsfr
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Element sélectionné (NULL par défaut)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement).
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#'
#' @importFrom htmltools tagList
#' @importFrom purrr pmap
#' @return html
#'
#' @export
#' @examples
#' if (interactive()) {
#'   library(shiny)
#'   library(shinygouv)
#'
#'   ui <- fluidPage_dsfr(
#'     header = header_dsfr(
#'       intitule = "Intitule",
#'       officiel = "Officiel",
#'       nom_site_service = "Nom du site / service",
#'       baseline = "baseline - precisions sur l organisation",
#'       class = "fr-m-1w"
#'     ),
#'     title = "Exemple",
#'     fluidRow_dsfr(
#'       radioGroupButtons_dsfr(
#'         inputId = "espece_radiogroupbutton",
#'         label = "Especes (radio group button avec inline = FALSE)",
#'         choices = c("Setosa" = "setosa", "Versicolor" = "versicolor", "Virginica" = "virginica"),
#'         selected = "virginica",
#'         inline = FALSE
#'       )
#'     ),
#'     fluidRow_dsfr(
#'       actionButton_dsfr(
#'         inputId = "update_radiogroupbutton_label",
#'         label = "Update label"
#'       ),
#'       actionButton_dsfr(
#'         inputId = "update_radiogroupbutton_choices",
#'         label = "Update choices and inline"
#'       ),
#'       actionButton_dsfr(
#'         inputId = "update_radiogroupbutton_selected",
#'         label = "Update selected"
#'       )
#'     ),
#'     fluidRow_dsfr(
#'       verbatimTextOutput(outputId = "outputespece_radiogroupbutton")
#'     )
#'   )
#'
#'   server <- function(input, output, session) {
#'     output$numericinputvalue <- renderText({
#'       paste("La valeur de l'input est", input$mynumericinput)
#'     })
#'
#'     r <- reactiveValues()
#'
#'     output$outputespece_radiogroupbutton <- renderText({
#'       paste("Esp\u00e8ce radiogroupbutton :", input$espece_radiogroupbutton)
#'     })
#'
#'
#'     observeEvent(input$update_radiogroupbutton_label, {
#'       updateRadioGroupButtons_dsfr(
#'         inputId = "espece_radiogroupbutton",
#'         label = paste0(sample(LETTERS, size = 12), collapse = ""),
#'         session = session
#'       )
#'     })
#'
#'     observeEvent(input$update_radiogroupbutton_choices, {
#'       r$radiogroupubutton_choices <- sapply(1:3, function(x) paste0(sample(LETTERS, size = 3), collapse = ""))
#'
#'       updateRadioGroupButtons_dsfr(
#'         inputId = "espece_radiogroupbutton",
#'         choices = r$radiogroupubutton_choices,
#'         inline = TRUE,
#'         session = session
#'       )
#'     })
#'
#'     observeEvent(input$update_radiogroupbutton_selected, {
#'       updateRadioGroupButtons_dsfr(
#'         inputId = "espece_radiogroupbutton",
#'         selected = sample(r$radiogroupubutton_choices, size = 1),
#'         session = session
#'       )
#'     })
#'   }
#'
#'   shinyApp(ui, server)
#' }
updateRadioGroupButtons_dsfr <- function(
    inputId,
    label = NULL,
    choices = NULL,
    selected = NULL,
    inline = FALSE,
    session = shiny::getDefaultReactiveDomain()
    ) {
  ns <- session$ns

  if (is.null(names(choices))) {
    nom_choix <- choices
  } else {
    nom_choix <- names(choices)
  }

  if (!is.null(choices)) {
    tag <- radioGroupButtons_dsfr(
      inputId = ns(inputId),
      label = if (!is.null(label)) label else "",
      choices = choices,
      selected = selected,
      inline = inline
    ) %>%
      htmltools::tagQuery()

    choices <- tag$find(".shiny-options-group")$selectedTags()
    choices <- as.character(choices)
  }

  message <- utils::getFromNamespace("dropNulls", "shiny")(list(
    label = label,
    options = choices,
    value = selected
  ))

  if (!is.null(selected)) {
    selected <- as.character(selected)
    button_to_color <- paste0(ns(inputId), "-", selected)
    session$sendCustomMessage(
      "updateRadioGroupColorButton",
      list(inputId = button_to_color)
    )
  }
  session$sendInputMessage(ns(inputId), message)

  # Choices have to changes to set up inline
  if (!is.null(choices)) {
    update_inline(ns(inputId), inline, session)
  }

}
