# WARNING - Generated by {fusen} from /dev/flat_composants/flat_checkboxInput.Rmd: do not edit by hand

#' updateCheckboxInput_dsfr
#' 
#' @param inputId id de l'input
#' @param label label du bouton
#' @param choices Liste des valeurs à sélectionner (si les éléments de la liste portent un nom, c'est ce nom qui est affiché à l'utilisateur et non la valeur)
#' @param selected Valeurs préselectionnées
#' @param choice_names Liste de labels (ignoré si choices est défini)
#' @param choice_values Liste des valeurs (ignoré si choices est défini)
#' @param inline Si TRUE, positionne les choix en ligne (c'est-à-dire horizontalement). 
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#' 
#' @importFrom htmltools tagQuery
#' @return html
#' 
#' @export
updateCheckboxInput_dsfr <- function(inputId,
                                    label = NULL,
                                    choices = NULL,
                                    selected = NULL,
                                    inline = FALSE,
                                    choice_names = NULL,
                                    choice_values = NULL,
                                    session = shiny::getDefaultReactiveDomain()) {
  
  ns <- session$ns
  
  if (!is.null(selected)) selected <- as.character(selected)
  
  tag <- checkboxInput_dsfr(
    inputId = ns(inputId),
    label = label,
    choices = choices,
    selected = selected, 
    inline = inline,
    choice_names = choice_names,
    choice_values = choice_values
  ) %>% 
    htmltools::tagQuery()
  
  choices <- tag$find(".shiny-options-group")$selectedTags()
  
  message <- utils::getFromNamespace("dropNulls", "shiny")(
    list(
      label = label,
      options = as.character(choices),
      selected = selected
    )
  )

  session$sendInputMessage(inputId, message)
}

