# WARNING - Generated by {fusen} from dev/flat_composants/flat_checkBoxInput.Rmd: do not edit by hand

#' updateCheckboxInput_dsfr
#'
#' Change la valeur d'un checkboxInput
#'
#' @param inputId id de l'input
#' @param label label du bouton
#' @param value TRUE (coché) ou FALSE (non coché)
#' @param session la session, la valeur par défaut est getDefaultReactiveDomain().
#'
#' @importFrom shiny updateCheckboxInput
#' @return html
#'
#' @export
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'   ui <- fluidPage_dsfr(
#'     checkboxInput_dsfr(inputId = "inCheckboxInput", label = "test", value = FALSE),
#'     actionButton_dsfr("go", "Change")
#'   )
#'   server <- function(input, output, session) {
#'     observeEvent(input$go, {
#'       updateCheckboxInput_dsfr(
#'         session = session,
#'         inputId = "inCheckboxInput",
#'         label = "Un nouveau label",
#'         value = TRUE
#'       )
#'     })
#'
#'     observeEvent(input$inCheckboxInput, {
#'       message(input$inCheckboxInput)
#'     })
#'   }
#'   shinyApp(ui, server)
#' }
updateCheckboxInput_dsfr <- function(
  inputId,
  label = NULL,
  value = NULL,
  session = shiny::getDefaultReactiveDomain()
    ) {
  ns <- session$ns

  updateCheckboxInput(
    session = session,
    inputId = ns(inputId),
    label = label,
    value = value
  )
}
