# WARNING - Generated by {fusen} from dev/flat_composants/flat_panels.Rmd: do not edit by hand

#' updateSelectInput_dsfr
#'
#' @param inputId inputId
#' @param label label
#' @param value  valeur par défaut
#' @param min valeur minimale
#' @param max valeur maximale
#' @param step pas utilisé entre 2 valeurs
#' @param session session shiny
#'
#' @importFrom shiny updateNumericInput
#' @return html
#'
#' @export
#' @examples
#' ## Only run examples in interactive R sessions
#' if (interactive()) {
#'   library(shiny)
#'   library(shinygouv)
#'
#'   ui <- fluidPage_dsfr(
#'     header = header_dsfr(
#'       intitule = "Intitule",
#'       officiel = "Officiel",
#'       nom_site_service = "Nom du site / service",
#'       baseline = "baseline - precisions sur l organisation",
#'       class = "fr-m-1w"
#'     ),
#'     title = "Exemple",
#'     fluidRow_dsfr(
#'       TabsetPanel_dsfr(
#'         inputId = "mynumericinput",
#'         label = "Numeric input",
#'         value = 12,
#'         min = 0,
#'         max = NA,
#'         step = 2
#'       ),
#'       actionButton_dsfr(
#'         inputId = "updateLabel",
#'         label = "updateLabel"
#'       ),
#'       actionButton_dsfr(
#'         inputId = "updateValue",
#'         label = "updateValue"
#'       ),
#'       actionButton_dsfr(
#'         inputId = "updateMin",
#'         label = "updateMin à la valeur en cours"
#'       ),
#'       actionButton_dsfr(
#'         inputId = "updateMax",
#'         label = "updateMax à la valeur en cours"
#'       ),
#'       actionButton_dsfr(
#'         inputId = "updateStep",
#'         label = "updateStep"
#'       ),
#'       verbatimTextOutput(outputId = "numericinputvalue")
#'     )
#'   )
#'   server <- function(input, output, session) {
#'     output$numericinputvalue <- renderText({
#'       paste("La valeur de l'input est", input$mynumericinput)
#'     })
#'
#'     r <- reactiveValues()
#'
#'     observeEvent(input$mynumericinput, {
#'       r$current_value <- input$mynumericinput
#'     })
#'
#'     observeEvent(input$updateLabel, {
#'       updateTabsetPanel_dsfr(
#'         session = session,
#'         inputId = "mynumericinput",
#'         label = sample(LETTERS, 10)
#'       )
#'     })
#'
#'     observeEvent(input$updateValue, {
#'       updateTabsetPanel_dsfr(
#'         session = session,
#'         inputId = "mynumericinput",
#'         value = sample(1:1000, size = 1)
#'       )
#'     })
#'
#'     observeEvent(input$updateMin, {
#'       updateTabsetPanel_dsfr(
#'         session = session,
#'         inputId = "mynumericinput",
#'         min = r$current_value
#'       )
#'     })
#'
#'     observeEvent(input$updateMax, {
#'       updateTabsetPanel_dsfr(
#'         session = session,
#'         inputId = "mynumericinput",
#'         max = r$current_value
#'       )
#'     })
#'
#'     observeEvent(input$updateStep, {
#'       updateTabsetPanel_dsfr(
#'         session = session,
#'         inputId = "mynumericinput",
#'         step = sample(seq(0.1, 1, by = .1), size = 1)
#'       )
#'     })
#'   }
#'
#'   shinyApp(ui, server)
#' }
updateTabsetPanel_dsfr <- function(
    inputId,
    label = NULL,
    value = NULL,
    min = NULL,
    max = NULL,
    step = NULL,
    session = shiny::getDefaultReactiveDomain()
    ) {
  ns <- session$ns

  updateNumericInput(
    session = session,
    inputId = inputId,
    label = label,
    value = value,
    min = min,
    max = max,
    step = step
  )
}
