# WARNING - Generated by {fusen} from dev/flat_composants/flat_withSpinner.Rmd: do not edit by hand

#' withSpinner_dsfr
#' 
#' 
#' @param expr L'opération a réaliser.
#' @param session 
#'
#' @return html
#' 
#' @export
#' @examples
#' \dontrun{
#' # To be added in your app_server.R ou some server function on a module
#' withSpinner_dsfr(
#'   expr = {
#'     message("Je vais m'afficher pendant 5 secondes")
#'     Sys.sleep(5)
#'   }
#' )
#' }
withSpinner_dsfr <- function(
  expr, 
  session = shiny::getDefaultReactiveDomain()
  ) {

  showSpinner_dsfr(session = session)
  force(expr)
  on.exit(hideSpinner_dsfr(session = session))
}
