# WARNING - Generated by {fusen} from dev/flat_composants/flat_withSpinner.Rmd: do not edit by hand

#' spinner-specific html code
#' @importFrom htmltools HTML
#' @return an html code
#' @examples addWithSpinner()
#'
#' @noRd
addWithSpinner <- function() {
  HTML('<div class="lds-ring" id = "lds-ring" style="display:none"><div></div><div></div><div></div><div></div></div>')
}

#' Masque le spinner
#'
#' Masque le spinner dans le cadre d'un appel à `shinygouv::withSpinner_dsfr()`
#' @param inputId id du spinner
#' @param session session
#' @return side effect. Masque le spinner
#'
#' @noRd
hideSpinner_dsfr <- function(
  inputId,
  session = shiny::getDefaultReactiveDomain()
    ) {
  session$sendCustomMessage("hide_spinner", inputId)
}

#' Affiche le spinner
#'
#' Affiche le spinner dans le cadre d'un appel à `shinygouv::withSpinner_dsfr()`
#' @param inputId id du spinner
#' @param session session
#' @return side effect. Affiche le spinner
#'
#' @noRd
showSpinner_dsfr <- function(
  inputId,
  session = shiny::getDefaultReactiveDomain()
    ) {
  session$sendCustomMessage("show_spinner", inputId)
}

#' withSpinner_dsfr
#'
#' Permet d'afficher un spinner lors d'un calcul prenant du temps, s'inspire du fonctionnement de [shiny::withProgress()]
#'
#' @param expr L'opération a réaliser.
#' @param session session shiny
#'
#' @return html
#' @export
#' @examples
#' if(interactive()) {
#' library(shiny)
#' library(shinygouv)
#'
#' ui <- fluidPage_dsfr(
#'   header = header_dsfr(
#'     intitule = "Intitule",
#'     officiel = "Officiel",
#'     nom_site_service = "Nom du site / service",
#'     baseline = "baseline - precisions sur l organisation",
#'     class = "fr-m-1w"
#'   ),
#'   title = "Exemple",
#'   fluidRow_dsfr(
#'     column_dsfr(
#'       0,
#'       shiny::p("Exemple colonne")
#'     ),
#'     actionButton_dsfr(
#'       inputId = "showspinner",
#'       label = "Afficher le spinner pendant 5 secondes"
#'     )
#'   )
#' )
#'
#' server <- function(input, output, session) {
#'   observeEvent(
#'     input$showspinner,
#'     {
#'       withSpinner_dsfr(
#'         expr = {
#'           message("Je vais m'afficher pendant 5 secondes")
#'           Sys.sleep(5)
#'         }
#'       )
#'     }
#'   )
#' }
#'
#' shinyApp(ui, server)
#' }
withSpinner_dsfr <- function(
  expr,
  session = shiny::getDefaultReactiveDomain()
    ) {
  showSpinner_dsfr(inputId = "lds-ring", session = session)
  force(expr)
  on.exit(hideSpinner_dsfr(inputId = "lds-ring", session = session))
}
